### ISSUE TITLE
autoportal don't open 

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2.4#1573] opened 2021-04-24 05:55 UTC
they dont open even if you connect them,but it doesn't crush the game

**Comment by FrozenDragon0** [comment] 2021-04-24 06:33
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3672 Also you have posted in the wrong section.

**Closed by FrozenDragon0** 2021-04-24 06:33 UTC
Labels: Bug, Duplicate

**Comment by anymaker3333** [comment] 2021-04-24 07:07
ok


сб, 24 апр. 2021 г. в 08:33, >:FrozenDragon:< ***@***.***>:
