### ISSUE TITLE
 lags in flight and high speed

### ISSUE THREAD

**Issue by NeuroLise** [BEEmod/BEE2.4#1263] opened 2020-03-09 08:00 UTC
When you jump on a gel, accelerate, fly in a tunnel, then frames begin to sag.

**Comment by Luke18033** [comment] 2020-03-09 13:47
Try switching music tracks (to the default PTI music for example), there's a known issue where some tracks will inexplicably lag the game when you try to play them. In this case it'd be caused by the funnel/gel variants.

**Comment by NeuroLise** [comment] 2020-03-12 11:12
I mean, lags with FPS. So, with sound it too.

**Comment by Luke18033** [comment] 2020-03-13 02:21
That's not really helpful, have you tried what I said?

**Comment by NeuroLise** [comment] 2020-03-13 13:41
Yes. Porblem solved.
To word. You wanna add more items in mod?

**Comment by NeuroLise** [comment] 2020-03-13 13:49
And what you updated in last hours?

**Comment by CheezyPig** [comment] 2020-03-13 13:52
You can read the description of the commits, and comment if you want more information about them. This issue seems to be now solved, and should be closed. Try not to ask unrelated things in your issues.

**Comment by Luke18033** [comment] 2020-03-13 14:09
Well no the issue isn't solved, we'd want to figure out what's causing the problem and fix it. I guess I should have asked this earlier, but what music were you using originally?

**Comment by Luke18033** [comment] 2020-05-09 06:48
Closing due to lack of info, though this is still an issue. We'll want to go through all the music tracks at some point, see which ones have this problem. I know Mel's Story is affected, but I'm sure there are others.

**Closed by Luke18033** 2020-05-09 06:48 UTC
Labels: Bug, More Info Needed
