### ISSUE TITLE
Art Therapy causes "Failure To Compile"

### ISSUE THREAD

**Issue by wimklaver** [BEEmod/BEE2.4#746] opened 2017-09-24 20:06 UTC
VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0pr26 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'random_blackwall_scale': '0', 'voice_pack': 'BEE2_GLADOS_ART'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 2
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/clean/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/clean/items/barrier_hazard_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/clean/items/fr/fdf_model.vmf', 'instances/bee2/clean/items/physler/model.vmf', 'instances/bee2/clean/items/fr/csf_model.vmf', 'instances/bee2/clean/items/fr/mif_model.vmf', 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'instances/bee2/clean/items/barrier_hazard_model.vmf', 'instances/bee2/clean/items/paint_fizz/model.vmf', 'instances/bee2/clean/items/death_fizz/model.vmf'}, '[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[INFO] voiceLine.add_voice(): Adding Base instance!
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.find_group_quotes(): "ENTRY": 1/15 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GENERIC_INDULGENCE"
 | 	"File" "art/entry_generic.vmf"
 | 	}
 |_

[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): Line "??" is disabled..
[INFO] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[INFO] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "GENERIC_2"
 | 	"Choreo" "scenes/npc/glados/dlc1_mp_coop_2paints_1bridge_outrob01.vcd"
 | 	}
 |_

[INFO] voiceLine.add_quote(): End-commands: 
[INFO] voiceLine.find_group_quotes(): "MIDCHAMBER": 1/10 quotes..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2426, misses=279, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'doorcameras': False}
[INFO] cond.core.check_all(): Global instances: set()
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[WARNING] template.get_scaling_template(): Template "BEE2_ART_GOO_WALL_SCALE" used as scaling template, but is not really one!
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/art/sky/side_1.vmf', 'instances/BEE2/art/sky/side_2.vmf', 'instances/BEE2/art/sky/side_3.vmf', ''], <CONN_TYPES.corner: 3>: ['instances/BEE2/art/sky/corner.vmf', 'instances/BEE2/art/sky/corner.vmf', 'instances/BEE2/art/sky/corner.vmf', ''], <CONN_TYPES.straight: 2>: ['instances/BEE2/art/sky/side_1.vmf', 'instances/BEE2/art/sky/side_2.vmf', 'instances/BEE2/art/sky/side_3.vmf', ''], <CONN_TYPES.triple: 4>: ['instances/BEE2/art/sky/triple.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/art/sky/pillar.vmf']}
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.clump_walls(): Clumping: 160 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun 28 2017)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/art/elevator_sp/entrance_corridor_2.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by EwokPilot** [comment] 2017-09-24 21:29
How do you install the Art Therapy style?

**Comment by EwokPilot** [comment] 2017-09-24 21:30
How do you install the Art Therapy style?

**Comment by wimklaver** [comment] 2017-09-24 21:31
https://github.com/BEEmod/BEE2-items/wiki/Art-Therapy

**Comment by EwokPilot** [comment] 2017-09-24 21:49
I know where to download it I just want to know where to put the file

**Comment by wimklaver** [comment] 2017-09-24 22:27
i think i just mixed the files in a wrong way, somehow Art Therapy did show up in the editor but when i launch the game and make a Chamber this shows up

**Comment by Luke18033** [comment] 2017-09-24 22:32
This would be caused by a missing instance for entrance corridor 2, switch to 1 and see if it works.

**Comment by wimklaver** [comment] 2017-09-24 22:36
at this moment, im re-installing the most recent BEEmod including Art-Therapy so i'll try it in a moment

**Comment by wimklaver** [comment] 2017-09-24 22:54
ìt did't work again: (i did use corridor 1 btw)

VBSP failed.

[INFO] cond.core.x(): No name for module "voiceLine"!
[INFO] vbsp.main(): BEE2.4.0pr26 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'random_blackwall_scale': '0'}
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[WARNING] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 1
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 1
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: True
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[INFO] cond.fizzler.fizzler_out_relay(): Fizzler data: {'marker_inst': [], 'pos_to_name': {}, 'fizz_by_name': {}, 'model': 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'base': 'instances/bee2/clean/items/tdb/csfi_base.vmf', 'fizz_id': 'item_tdb_csfi', 'fizz_bases': {'instances/bee2/clean/items/barrier_hazard_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/paint_fizz/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/csf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/fdf_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/fr/mif_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/death_fizz/base.vmf': ItemConnections(in_act=('branch_fizz', 'ToggleTest'), in_deact=('branch_las', 'ToggleTest'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/physler/base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, '')), 'instances/bee2/clean/items/rex/pellet_field_base.vmf': ItemConnections(in_act=(None, ''), in_deact=(None, ''), out_act=('out', 'OnUser2'), out_deact=('out', 'OnUser1')), 'instances/bee2/clean/items/tdb/csfi_base.vmf': ItemConnections(in_act=('counter', 'Add'), in_deact=('counter', 'Subtract'), out_act=(None, ''), out_deact=(None, ''))}, 'fizz_models': {'instances/bee2/clean/items/paint_fizz/model.vmf', 'instances/bee2/clean/items/death_fizz/model.vmf', 'instances/bee2/clean/items/physler/model.vmf', 'instances/bee2/clean/items/tdb/csfi_model.vmf', 'instances/bee2/clean/items[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] vbsp.set_elev_videos(): Elevator type: NONE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] vbsp.add_screenshot_logic(): Added Screenshot Logic
[INFO] cond.core.check_all(): Map has attributes: ['spawn_dual']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=2910, misses=316, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'doorcameras': False}
[INFO] cond.core.check_all(): Global instances: set()
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[WARNING] template.get_scaling_template(): Template "BEE2_ART_GOO_WALL_SCALE" used as scaling template, but is not really one!
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: True
[INFO] vbsp.change_brush(): Goo heights: 0 <- Counter()
[INFO] vbsp.change_brush(): Creating Bottomless Pits...
[INFO] bottomlessPit.make_bottomless_pit(): Pit instances: {<CONN_TYPES.side: 1>: ['instances/BEE2/art/sky/side_1.vmf', 'instances/BEE2/art/sky/side_2.vmf', 'instances/BEE2/art/sky/side_3.vmf', ''], <CONN_TYPES.corner: 3>: ['instances/BEE2/art/sky/corner.vmf', 'instances/BEE2/art/sky/corner.vmf', 'instances/BEE2/art/sky/corner.vmf', ''], <CONN_TYPES.straight: 2>: ['instances/BEE2/art/sky/side_1.vmf', 'instances/BEE2/art/sky/side_2.vmf', 'instances/BEE2/art/sky/side_3.vmf', ''], <CONN_TYPES.triple: 4>: ['instances/BEE2/art/sky/triple.vmf'], <CONN_TYPES.all: 5>: ['instances/BEE2/art/sky/pillar.vmf']}
[INFO] vbsp.change_brush(): Done!
[INFO] vbsp.clump_walls(): Clumping: 160 clumps (+ 0 special)
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Jun 28 2017)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/bee2/art/elevator_sp/entrance_corridor_1.vmf
 | 
 |_

[INFO] BEE2_config.save(): Saving changes in config "C:\Users\Wim\Desktop\BEE2-items-art_therapy\config/compile.cfg"!
[ERROR] vbsp.run_vbsp(): VBSP failed! (1)


im going to bed for a few hours so i'll be back later incase you have something to say about this

**Comment by ZombiePwner1** [comment] 2017-09-25 00:53
@wimklaver Do not use art therapy style atm alot of files are mixed up and there are alot of missing instances.

**Comment by LautaroL20** [comment] 2017-09-25 01:00
This style is totally unstable.

**Comment by ZombiePwner1** [comment] 2017-09-25 05:40
@LautaroL20 Do not close it yet wheels let @TeamSpen210 deal with it.

**Comment by LautaroL20** [comment] 2017-09-25 13:59
@ZombiePwner1 - Alright wheels.

**Comment by HelloIamaPersonThatIsAliveAndHealthily** [comment] 2017-09-25 14:10
Hey guys, lets cross the fingers so the developer gets their hands on the almost dead art therapy branch.....

**Closed** 2017-10-07 05:00 UTC
Labels: Compile error

**Comment by Luke18033** [comment] 2020-04-22 06:19
Okay, I know this is an old issue but just look at this. Yet again, HelloIAmAPersonThatIsAlive conveniently shows up immediately after Lautaro posts to back up his argument. He's an alt, just admit it already.

**Comment by LautaroL20** [comment] 2020-04-22 13:54
> Luke18033 Said: "Okay, I know this is an old issue but just look at this. Yet again, HelloIAmAPersonThatIsAlive conveniently shows up immediately after Lautaro posts to back up his argument. He's an alt, just admit it already."

It is admirable to see everything you have tried in this regard, but for more "elements" that you try to see here and there to just try to shape a small conspiration, it is really funny but that does not prove i am the owner of that "alt"...

I have seen other conspiracies, there are people who thinks we have never stepped on the moon and that the film that there is about it was just a montage made by Stanley Kubrick, all this with the aim of winning the cold war against the Soviets.

More conspirations? Sure, there are people who also thinks that the 11-S event was just an auto-attack planned by the CIA to then justify the war in Afghanistan and the war in Iraq.

And of course, how could i leave out one of the most recent conspirations that there is about USA and China... a small percentage of people thinks that the COVID-19 is a biological weapon that was developed by the secret government behind the shadows (also known as the deep state) that governs the United States, with the aim of damaging the China´s economy after a trade war that both countries have had, so USA can still remain the world's leading power for a little longer.

Personally, i respect what each person wants to believe, but from my point of view, they are only conspiracies, no certainties. Everyone is free to believe in whatever they want, that's all i can say about this subject.

**Comment by Luke18033** [comment] 2020-04-23 00:03
The fact that you're comparing this to full-on government conspiracies kind of gives away that you're trying to hide something, and I think anyone else would agree with me in that regard. Also, I mentioned this in the other issue, but don't you find it a bit weird that *they* haven't come to defend themselves at all? I know that if I was being accused of being an alt of, I don't know, TeamSpen, I'd have a lot to say about that, I wouldn't just sit around while he did all the talking. And of course, that's not to mention how you're still completely ignoring the fact that the account is an [impo](https://cdn.discordapp.com/attachments/339794907587936256/702663079388905512/unknown.png)[stor](https://github.com/HelloIamapersonthatisalive).

Yes, you're correct in saying that there's no way to *truly* prove it, but does that really matter? Your behavior (and his/yours) is very much making it seem that way, and people aren't going to ignore that just because there's no concrete proof of it, at least not here. I don't know why you're still trying to hide this; if you just admitted it was your alt, we could be done with these arguments and move on. If it isn't your alt - well, I'm sure you'd be able to convince us of that as well, but I find it hard to believe at this point.
