### ISSUE TITLE
Portal 1 Style Doesn't Work

### ISSUE THREAD

**Issue by AcroGH1375** [BEEmod/BEE2.4#1347] opened 2020-07-17 23:52 UTC
I am trying to make a level with the Portal 1 style, but it keeps spitting out the same error whenever I try to build the puzzle, "There was an error building the puzzle." But, whenever I try any other style with the same exact level, it works with no issues.

**Comment by Luke18033** [comment] 2020-07-18 00:37
Immediately after the compile fails, open the console and copy the error log (big block of red text). Post it here, that generic error message is useless on its own.

**Comment by AcroGH1375** [comment] 2020-07-18 00:44
VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'bottomless_pit': '0', 'fizz_visiblity': '0', 'voice_pack': 'BEE2_GLADOS_P1'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (100 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] packing.pack_list(): Packlist "PACK_P1_DOOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CONC_RECESSED_LIGHTS" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CAMERA" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CAMERA" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_DOOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_CAMERA" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_OBS_ROOM" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_OBS_LIGHT" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_PANEL_CYLINDER" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_PANEL_SOUNDS" does not exist!
[W] packing.pack_list(): Packlist "PACK_P1_PIST_MOVE_SOUNDS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_P1_PLASTIC_NOPAINT" does not exist!
[E] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\template_brush.py", line 221, in visgrouped
KeyError: 'btm_ul'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 514, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 322, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 311, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\brushes.py", line 679, in res_import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 473, in import_template
  File "F:\Git\BEE2.4\src\template_brush.py", line 225, in visgrouped
ValueError: Unknown visgroup "btm_ul" for "bee2_track_scaffold_p1_top_horiz"! (valid: '', 'btm_ur')

**Comment by Luke18033** [comment] 2020-07-18 01:33
Duplicate of BEEmod/BEE2-items#3143

**Closed by Luke18033** 2020-07-18 01:33 UTC
Labels: Compile Error, More Info Needed
