### ISSUE TITLE
[suggestion] add an "appearifier"

### ISSUE THREAD

**Issue by helpihavebug** [BEEmod/BEE2.4#936] opened 2018-06-15 12:41 UTC
an appearifier would work the opposite way a sendificator would. it would transport cubes to wherever the laser is pointed. i just came up with this idea, because the sendificator comes from homestuck, and there's the appearifier in it, too.

**Comment by HugoBDesigner** [comment] 2018-06-15 12:54
Issues/suggestions about items go in [the BEE2-items repository](https://github.com/BEEmod/BEE2-items/issues). But even then, it'd be a duplicate of this: https://github.com/BEEmod/BEE2-items/issues/1537

**Closed by HugoBDesigner** 2018-06-15 12:54 UTC
