### ISSUE TITLE
Failed to execute script BEE2_launch

### ISSUE THREAD

**Issue by YuraSuper2048** [BEEmod/BEE2.4#1727] opened 2021-10-02 07:33 UTC
### BEE2 Application Version

4.40.2 64 bit

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
[INFO] utils.setup_localisations(): Language: 'ru_RU'
[DEBUG] utils.setup_localisations(): Language codes: ['ru_RU.UTF-8', 'ru_RU', 'ru.UTF-8', 'ru']
[INFO] BEE2_launch.<module>(): Arguments: ['C:\\Users\\murmj\\Downloads\\BEE2\\BEE2.exe']
[INFO] BEE2_launch.<module>(): Running "bee2", version 4.40.2:
[INFO] sound.load(): Loading sound "select" -> C:\Users\murmj\Downloads\BEE2\sounds\rollover.ogg
[WARNING] BEE2_config.load(): Config "C:\Users\murmj\AppData\Roaming\BEEMOD2\config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "C:\Users\murmj\AppData\Roaming\BEEMOD2\config\compile.cfg" not found! Using defaults...
[INFO] BEE2_config.save(): Saving changes in config "C:\Users\murmj\AppData\Roaming\BEEMOD2\config\compile.cfg"!
[ERROR] logger.except_handler(): Uncaught Exception:
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 117, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 332, in mkstemp
  File "tempfile.py", line 251, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\murmj\\AppData\\Roaming\\BEEMOD2\\config\\tmp8l21ozww'
[WARNING] BEE2_config.load(): Config "C:\Users\murmj\AppData\Roaming\BEEMOD2\config\config.cfg" not found! Using defaults...
[INFO] BEE2_config.save(): Saving changes in config "C:\Users\murmj\AppData\Roaming\BEEMOD2\config\config.cfg"!
```

**Comment by Konclan** [comment] 2021-10-02 07:58
Duplicate of #1624

**Closed by Konclan** 2021-10-02 07:58 UTC
Labels: Bug, App Crash
