### ISSUE TITLE
Can't launch Bee2Mod 2.39.2

### ISSUE THREAD

**Issue by cryingandten** [BEEmod/BEE2.4#1596] opened 2021-05-26 12:24 UTC
Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -2147024891] Аccess denied

**Comment by LautaroL20** [comment] 2021-05-26 14:38
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Closed** 2021-05-26 14:38 UTC
Labels: Duplicate
