### ISSUE TITLE
Error when compiling level with Sendificator Item

### ISSUE THREAD

**Issue by Notsoartificialintelligence** [BEEmod/BEE2.4#1437] opened 2020-12-21 13:31 UTC
Whenever I add a Sendificator Item (normal or slim) into my map, it refuses to compile. I have tried deleting the vrad and vbsp files and verifying cache.

Here is the error:

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 48 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'staticpan': 'instances/BEE2/over/static_panel/', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (2 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Exit to 2
[I] vbsp.mod_entryexit(): Setting SP Entry to 6
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (29 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.sendtor.res_sendificator(): Relay: <Entity>: 
 | {
 | 	 targetname = "@sendtor13_las_relay_1"
 | 	 origin = "8 448 32"
 | 	 angles = "-0 0 0"
 | 	 classname = "logic_relay"
 | 	 StartDisabled = "0"
 | 	<Output> OnTrigger -> !self -> RunScriptCode (::sendtor_source <- self;)
 | 	<Output> OnTrigger -> @sendtor_fire -> Trigger
 | }
 | 
 |___

[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[I] vbsp.set_elev_videos(): Elevator type: RAND
[W] cond.positioning.flag_brush_at_loc(): Using type=same in posIsSolid is deprecated, put this in mode!
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "ENTRY": 2/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "ENTRY_GEN_FUTURE_STARTER"
 | 	"Choreo" "npc/announcer/prehub17.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "EXIT_GEN_TECH_DIFF"
 | 	"Choreo" "ann_apoc/exit_tech_diff.vmf"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 3/4 quotes..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[W] packing.pack_list(): Packlist "PACK_HMW_SENDTOR_LOGIC" does not exist!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['fizzler', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'laseremitter', 'laser', 'deadly', 'sendificator', 'sendtor', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'pedestalbutton', 'needsportalman', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=5662, misses=392, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': False, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_4.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/bee2/logic/hmw/sendtor_manager.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] tiling.generate_brushes(): Generating tiles...
[I] tiling.generate_brushes(): Generating goop...
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): "materials/tools/toolsblack_cheap.vtf": cached version doesn't exist
[I] <valve>.vbsp(): fixing up env_cubemap materials on brush sides...
[I] <valve>.vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] <valve>.vbsp(): ProcessBlock_Thread: 0...1...2...3...4...5...6...7...8...9...10 (0)
[I] <valve>.vbsp(): Processing areas...done (0)
[I] <valve>.vbsp(): Building Faces...done (0)
[I] <valve>.vbsp(): Chop Details...done (0)
[I] <valve>.vbsp(): Find Visible Detail Sides...
[I] <valve>.vbsp(): Merged 606 detail faces...done (0)
[I] <valve>.vbsp(): Merging details...done (0)
[I] <valve>.vbsp(): FixTjuncs...
[I] <valve>.vbsp(): PruneNodes...
[I] <valve>.vbsp(): WriteBSP...
[I] <valve>.vbsp(): done (0)
[I] <valve>.vbsp(): writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.prt...Building visibility clusters...
[I] <valve>.vbsp(): done (0)
[I] <valve>.vbsp(): Finding displacement neighbors...
[I] <valve>.vbsp(): Finding lightmap sample positions...
[I] <valve>.vbsp(): Displacement Alpha : 0...1...2...3...4...5...6...7...8...9...10
[I] <valve>.vbsp(): Building Physics collision data...
[I] <valve>.vbsp(): done (2) (522962 bytes)
[I] <valve>.vbsp(): Placing detail props : 0...1...2...3...4...5...6...7...8...9...10
[I] <valve>.vbsp(): Water found with no water_lod_control entity, creating a default one.
[I] <valve>.vbsp(): Compacting texture/material tables...
[I] <valve>.vbsp(): Reduced 3179 texinfos to 774
[I] <valve>.vbsp(): Reduced 86 texdatas to 79 (2473 bytes to 2223)
[I] <valve>.vbsp(): Writing C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.bsp
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): nummapplanes:     (  9588 / 65536 )
[I] <valve>.vbsp(): nummapbrushes:    (  1440 /  8192 )
[I] <valve>.vbsp(): nummapbrushsides: ( 11149 / 65536 )
[I] <valve>.vbsp(): num_map_overlays: (    73 /   512 )
[I] <valve>.vbsp(): nummodels:        (    52 /  1024 )
[I] <valve>.vbsp(): num_entities:     (   500 / 16384 )
[I] <valve>.vbsp(): 
[I] <valve>.vbsp(): 4 seconds elapsed
[I] <valve>.vbsp(): CDynamicFunction: Loading library 'Kernel32.dll' (76970000)
[I] <valve>.vbsp(): CDynamicFunction: Lookup of 'TryEnterCriticalSection' in 'Kernel32.dll': 77E03B10
[I] <valve>.vbsp(): CDynamicFunction: Closing library 'Kernel32.dll' (76970000)
[I] vbsp.run_vbsp(): VBSP Done!
[I] vbsp.process_vbsp_log(): Retrieved counts: {'brush': ('1440', '8192'), 'overlay': ('73', '512'), 'entity': ('500', '16384')}
[I] BEE2_config.save(): Saving changes in config "C:\Users\nesss\AppData\Roaming\BEEMOD2\config\compile.cfg"!
[I] vbsp.make_vrad_config(): Generating VRAD config...
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\compiler_launch.py", line 13, in <module>
  File "F:\Git\BEE2.4\src\vbsp.py", line 2101, in main
  File "F:\Git\BEE2.4\src\vbsp.py", line 1754, in make_vrad_config
  File "F:\Git\BEE2.4\src\cubes.py", line 637, in write_vscripts
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/inject/cube_vscript_01.nut'
[528] Failed to execute script compiler_launch

**Comment by LautaroL20** [comment] 2020-12-21 16:12
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3307, also, you have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only.

**Closed by LautaroL20** 2020-12-21 16:12 UTC
Labels: Duplicate
