### ISSUE TITLE
Beemod v4.39.2 crash: "pyglet.media.exceptions.MediaDecodeException: [WinError -numbers]

### ISSUE THREAD

**Issue by zibrolta00** [BEEmod/BEE2.4#1521] opened 2021-02-28 12:53 UTC
[bee2.error.2.log](https://github.com/BEEmod/BEE2.4/files/6056806/bee2.error.2.log)
Right now i was trying to install the newest version on github. And after i start the .exe file it just crashes with some errors in log.
(the last line in russian is "Access denied")
I was running the .exe as Administrator

**Comment by LautaroL20** [comment] 2021-02-28 15:05
Are you using Windows 10?

**Comment by zibrolta00** [comment] 2021-02-28 15:14
> 
> 
> Are you using Windows 10?

windows 10 pro x64

**Comment by madame-rachelle** [comment] 2021-03-02 15:21
> I was running the .exe as Administrator

I saw this and I was like "hmm let me try without admin" and so I did and it worked.

**Comment by zibrolta00** [comment] 2021-03-02 16:03
> 
> 
> > I was running the .exe as Administrator
> 
> I saw this and I was like "hmm let me try without admin" and so I did and it worked.

Well, i tried that right now, the exact error log.

**Comment by KaziPlays** [comment] 2021-03-04 14:50
I use windows 7 and It does not work as well

**Comment by LautaroL20** [comment] 2021-03-04 15:04
@KaziPlays - Glad to see you are also a Windows 7 user as me, may i ask you if when you try to launch the 32-bit version of the latest release of BeeMod, you get the error that is reported in this issue: https://github.com/BEEmod/BEE2.4/issues/1520

**Comment by KaziPlays** [comment] 2021-03-04 15:12
Yes, and I think I found a hint on the Beemod logs
![Uploading 16148707440041904549016.jpg…]()

**Comment by KaziPlays** [comment] 2021-03-04 15:14
Wait there is more
![Uploading 1614870849720966273199.jpg…]()

**Comment by LautaroL20** [comment] 2021-03-04 15:27
Your image uploads seems to be broken, could you instead upload them to imgur instead?

**Comment by KaziPlays** [comment] 2021-03-04 15:49
It says a file does not start with RIFF id https://ibb.co/pfbSnKs

**Comment by zibrolta00** [comment] 2021-03-05 12:22
Right now was trying to launch x32 version - failed, same log. After that i tried previous version - that log again(+ my windows defender was denying to copy the .EXE file of BEEmod v4.39.0 from ZIP archive into another folder, saying about trojan virus).
Any ideas? Because i'm really surprized. Before reinstalling my system(got some system files missing/broken) it was going pretty fine, and i didn't change any hardware.

**Comment by zibrolta00** [comment] 2021-03-16 16:26
Sooo.... Any news?

**Comment by KaziPlays** [comment] 2021-03-16 16:31
I don't think so.

**Comment by zibrolta00** [comment] 2021-03-17 05:20
Well, i think it's... normal? Idk, judging by how many requests are here.

**Comment by LautaroL20** [comment] 2021-04-10 13:48
@zibrolta00 - There is an user who seem to have fixed this issue and he has written the solution in a comment that you can check, here: https://github.com/BEEmod/BEE2.4/issues/1554

Let me know if it worked btw.

**Comment by zibrolta00** [comment] 2021-04-11 09:54
Yeah, i saw that one. I don't have it installed at all, but still tried doing step about appData folder. Same log file on trying to install, no matter with administrator or not.

**Comment by LautaroL20** [comment] 2021-04-11 11:08
> zibrolta00 said:  "Edit: Btw, the edited heading of the issue is a bit wrong, that's the [WinError -2147024891] Access is denied']"

The "WinError -numbers" part is generic, the most important segment of the log is where it says that it fails on line 498, in __init__pyglet.media.exceptions.MediaDecodeException. This part is what will help to determine the cause of the issue.

**Comment by delete00** [comment] 2021-04-11 12:27
> @zibrolta00 - There is an user who seem to have fixed this issue and he has written the solution in a comment that you can check, here: #1554
> 
> Let me know if it worked btw.

I have same issue, it didnt work, same error, i really hope it will be fixed in next version.

**Comment by zibrolta00** [comment] 2021-04-11 12:53
> I have same issue, it didnt work, same error, i really hope it will be fixed in next version.

Same here

**Comment by Nyrif** [comment] 2021-04-22 05:41
I'm also having this issue. I've tried the appdata thing and it still happens, what's even weirder is it happens in previous versions too (except for BEE2 4.37.0, but everything in that one is an error model).

**Comment by zibrolta00** [comment] 2021-04-22 11:48
This is now surprisingly a big problem, i thought it's just something with my old dusty PC ;-;

**Comment by Swino4ka** [comment] 2021-04-28 06:15
Ok, I think I just gonna download oldest version of mod...

**Comment by zibrolta00** [comment] 2021-04-28 12:30
I don't think this is a good idea :|

**Comment by LautaroL20** [comment] 2021-05-07 14:19
I think that it would be a good idea to pin this issue, people doing lot of duplicates of this issue. Lets see if people now sees it.

**Comment by fisthefisman** [comment] 2021-05-19 08:57
Same issue for me too. Tried deleting all in appdata. Still the same error. 
More info:
I launch BEE2.exe
I get the first error (images below), the logs open and instantly close
Then I am either asked to locate the game exe file or just skip to the launch
And without the launch even starting I get the second error. (images below)
Images:
https://imgur.com/a/89BvsnZ

**Comment by Limeony** [comment] 2021-05-22 00:11
it seems like a lot of people have the same error, probably the only thing left is to wait for a new version with this fix
win10 x64 ltsc btw if it help in someway

**Comment by zibrolta00** [comment] 2021-05-23 09:33
And all this started just because i wanted to remember portal 2 again, wow

**Comment by zibrolta00** [comment] 2021-06-16 18:08
Any news?

**Comment by LautaroL20** [comment] 2021-06-16 23:22
Well, recently I was thinking that the cause of this and issue https://github.com/BEEmod/BEE2.4/issues/1520 may be both related, could you please try applying the solution given by Lieutenant-L-T-Smash on the comment section from that issue? If that fixes your issue, then both causes are definitely almost the same.

**Comment by zibrolta00** [comment] 2021-06-17 10:38
whoa, it really worked. Replaced the sounds folder and now it launches perfectly!

**Comment by zibrolta00** [comment] 2021-07-03 04:58
Okay, hope this solution helps other ppl too! Closing the issue.

**Comment by LautaroL20** [comment] 2021-07-03 05:33
The issue should stay open until the dev implements the fix on BEEmod.

**Comment by Nyrif** [comment] 2021-07-13 04:32
4.40.2 seems to of fixed this issue.

**Comment by TeamSpen210** [comment] 2021-07-13 07:25
It wouldn’t have fixed it, just allowed the app to still run without sound.

**Comment by LautaroL20** [comment] 2021-09-20 05:34
I have been reviewing some comments from here and Discord about this issue, and everything seems to indicate that this problem only happens to some Win10 users that upgraded from Windows 7/8.1 at some point without any reset. So, this means that the origin of the cause is #1520 (now renamed with a diff title and desc).

zibrolta00 has confirmed that once he applied the solution given on issue #1520 he solved this issue, so mergin this with #1520, as by solving that one, this issue will no longer happen.

**Closed by LautaroL20** 2021-09-20 05:34 UTC
Labels: Bug
