### ISSUE TITLE
Fizzlers still give compile errors in 4.38.1

### ISSUE THREAD

**Issue by KittySaya** [BEEmod/BEE2.4#1493] opened 2021-02-20 10:28 UTC
Placing any type of fizzler in the map gives an error while trying to compile. Removing all of them fixes it.
It said in the patch notes this was fixed in 4.38.1 but I still encounter it in said version.

**Comment by seagemgames** [comment] 2021-02-20 10:52
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3641. This was caused by the latest Portal 2 update.

**Comment by FrozenDragon0** [comment] 2021-02-20 11:00
Also you are posting in the wrong section.

**Closed** 2021-02-20 11:00 UTC
Labels: Duplicate
