### ISSUE TITLE
Bee mod glitch/issue

### ISSUE THREAD

**Issue by Guy77** [BEEmod/BEE2.4#935] opened 2018-06-14 01:47 UTC
Ok so I got a problem, so this just  started happening, so whenever I make a new map I spawn in the elevator room with every single asset I put into the map all shoved together in the elevator room, not to mention the elevator spawns under the room with me in it, and the elevator room isn't even connected to the test room itself

**Comment by LautaroL20** [comment] 2018-06-20 07:29
That is really mysterious...

**Comment by Konclan** [comment] 2019-08-28 21:23
Duplicate of #704

**Closed by Konclan** 2019-08-28 21:23 UTC
Labels: Bug
