### ISSUE TITLE
Incinerator pls?

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#861] opened 2018-03-08 15:44 UTC
Can you add an a Emergercy intelligence incinerator

**Comment by Luke18033** [comment] 2018-03-08 16:55
Duplicate of BEEmod/BEE2-items#95, and this is the wrong repository.

**Closed by Luke18033** 2018-03-08 16:55 UTC

**Comment by TeamSpen210** [comment] 2018-03-08 23:16
What exactly would it be useful for anyway, really?

**Comment by cartman1337** [comment] 2018-03-09 00:09
Level design mostly, and perhaps, in closed form, climbing, if it's possible to jump on it with or without the aid of a cube. Along with a fire pit it would make for some nice Portal 1 maps, at least.

**Comment by LautaroL20** [comment] 2018-03-09 10:42
@Luke18033 - Do not forget to apply the label after closing an issue.
