### ISSUE TITLE
Not Works AutoPortals

### ISSUE THREAD

**Issue by DarkGradient** [BEEmod/BEE2.4#1561] opened 2021-04-12 13:32 UTC
Not working AutoPortals. Portals can't activated by button etc

**Comment by FrozenDragon0** [comment] 2021-04-12 14:22
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3672.

Also you have posted in the wrong section.

**Closed by FrozenDragon0** 2021-04-12 14:22 UTC
Labels: Bug
