### ISSUE TITLE
Custom Music Packer/Tutorials?

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#585] opened 2017-04-22 00:52 UTC
Is there a possibility of a custom music packer for those of us who may just happen to be musicians (myself included)? It would be really nice to be able to add my own music into maps. Thanks!!

**Comment by TeamSpen210** [comment] 2017-04-22 01:13
There isn't a tool for it, but you can make the config file fairly easily. The only issue is making the WAV files in the right format and making them loop.

**Comment by peefTube** [comment] 2017-04-22 01:38
My main question is really if you could make a simple tutorial or program for packing the files into a .zip properly.

**Comment by peefTube** [comment] 2017-04-22 21:15
@TeamSpen210 How do I sync the excursion funnel music?

**Comment by peefTube** [comment] 2017-04-22 23:18
Okay, I think I've figured out how to get everything working. My only issue now is that Portal 2 refuses to load in the music.

**Comment by TeamSpen210** [comment] 2017-04-22 23:21
Make sure you put your music files in `bee2/` or `portal2_dlc2/`, otherwise the BEE2 won't pack them in properly. To sync funnel music, add `"sync_funnel" "1"` in the `SoundScript` block.

**Comment by peefTube** [comment] 2017-04-23 03:47
Which `BEE2/`? In the Portal 2 dir or the BEE2 dir?

**Comment by TeamSpen210** [comment] 2017-04-23 03:48
In the Portal 2 directory.

**Comment by LautaroL20** [comment] 2017-04-23 12:26
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1181

**Closed by LautaroL20** 2017-04-23 12:26 UTC
Labels: Duplicate, Enhancement
