### ISSUE TITLE
the button cube has no model in the overgrown style

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2.4#1575] opened 2021-04-24 06:00 UTC
if you try to place button cube in the overgrown style, there just no textures. an empty,  laggy hole

**Comment by FrozenDragon0** [comment] 2021-04-24 06:33
Duplicate of: https://github.com/BEEmod/BEE2-items/issues/3645 Also you have posted in the wrong section.

**Closed by FrozenDragon0** 2021-04-24 06:33 UTC
Labels: Bug, Duplicate
