### ISSUE TITLE
Ensure the PORTAL2 is not running......

### ISSUE THREAD

**Issue by homelessturret** [BEEmod/BEE2.4#728] opened 2017-08-31 22:09 UTC
I've been trying to export the pallet to portal 2 and it keeps on giving me that message, and, of course, portal 2 is not running: 

![Image](https://user-images.githubusercontent.com/31522977/29981357-6bb72eca-8f1b-11e7-9562-eeae3ff5df7a.PNG)

**Comment by homelessturret** [comment] 2017-08-31 22:13
Oh great, guess what, now i open portal 2 and it's there, but everything is errors, This is one broken mod.

**Comment by homelessturret** [comment] 2017-08-31 22:15
Ok, what the actual fuck, now i try to build the test chamber and there "has been an error"

**Comment by ZombiePwner1** [comment] 2017-09-01 00:57
@homelessturret There is no need to get pissed off prl 25 came with a lot of bugs fixed in previous releases and that is why prl 25 has issues talk to @TeamSpen210 to ask how to fix this.

**Comment by Luke18033** [comment] 2017-09-01 00:58
Or just get Pr26?

**Comment by homelessturret** [comment] 2017-09-01 11:40
what is that? Idk what pr26 is

**Comment by homelessturret** [comment] 2017-09-01 11:59
oh yeah, pre-release 26, i am using that

**Comment by LautaroL20** [comment] 2017-09-01 15:41
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by homelessturret** [comment] 2017-09-01 17:27
thank you, i am attempting this right now

**Comment by homelessturret** [comment] 2017-09-01 17:42
this is still happening 
![well this is happening](https://user-images.githubusercontent.com/31522977/29981357-6bb72eca-8f1b-11e7-9562-eeae3ff5df7a.PNG)

**Comment by LautaroL20** [comment] 2017-09-01 18:27
Make sure to have downloaded and unzipped the latest packages & application version of beemod, and **both must have to be from the same pre-release version, otherwise bugs may occur.** Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

**Comment by homelessturret** [comment] 2017-09-01 18:32
but there are not packages for beemod 26

**Comment by LautaroL20** [comment] 2017-09-01 19:37
Thats why you shouldn´t use the version 26 of the application, both packages and application must be of the same version. Also, version 26 is still work in progess.

**Comment by TeamSpen210** [comment] 2017-09-01 19:39
I did release PR26, but with no package changes - so you use PR25 packages.

**Comment by homelessturret** [comment] 2017-09-01 20:29
well crap, i accidentaly merged both 26 with 25

**Comment by homelessturret** [comment] 2017-09-01 22:16
FINALLY! i've got it, this was so hard to me because i've always been using the "press subscribe to install" addons on the workshop

**Closed** 2017-09-01 22:32 UTC
Labels: Bug
