### ISSUE TITLE
Changing language causes: <BEE.exe can't loading UI>

### ISSUE THREAD

**Issue by eloshima** [BEEmod/BEE2.4#669] opened 2017-06-20 17:57 UTC
I don't really know why, If someone could help me.. ://
Logs:

"[WARNING] utils.setup_localisations(): Can't find translation for codes: ['fr_FR.ISO8859-1', 'fr_FR', 'fr.ISO8859-1', 'fr']!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_cust_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\games.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\compile.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\config.cfg" not found! Using defaults...
[WARNING] packageLoader.__init__(): Template "BEE2_CUTOUT_TILE_FLOOR_SIDE_WORLD" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CUTOUT_TILE_FLOOR_SIDE_DETAIL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CUTOUT_TILE_FLOOR_PILLAR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_BTS_GRATING_TEMPLATE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FLOOR_BUTTON_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CUBE_BUTTON_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_BALL_BUTTON_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_EMBEDDED_VOXEL" has no config!
[WARNING] packageLoader.__init__(): Template "__TILING_TEMPLATE__" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_BOTTOM_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_TOP_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_TUNNEL_TILE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_BOTTOM_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_TOP_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_BOTTOM_PORTAL_1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_TOP_PORTAL_1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_RAIL_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FUTBOL_SURF_BACK" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FUTBOL_SURF_BACK_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FUTBOL_SURF_BACK_50S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_TOP" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_MIDDLE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_BOTTOM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_SINGLE" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE_REV" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_FLAT_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_WHITE_50S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_WHITE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BLACK_50S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BLACK_70S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BLACK_80S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_FLAT_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_DYNAMIC_PAN_ANGLED_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FLOOR_BUTTON_BASE_P1_WHITE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_BALL_BUTTON_BASE_P1_WHITE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_ROCKET_TURRET_CAP_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_ARROW_WALL_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_CLEAN_SMALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_CLEAN_MEDIUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_CLEAN_LARGE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_RETRO_MEDIUM" has no config!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\srctools\srctools\property_parser.py", line 616, in __getitem__
  File "F:\Git\srctools\srctools\property_parser.py", line 402, in _get_value
srctools.property_parser.NoKeyError: No key language!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 116, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 816, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 618, in __getitem__
IndexError: No key language!
[WARNING] utils.setup_localisations(): Can't find translation for codes: ['fr_FR.ISO8859-1', 'fr_FR', 'fr.ISO8859-1', 'fr']!
[WARNING] BEE2_config.load(): Config "../config\packages.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "../config\item_configs.cfg" not found! Using defaults...
[WARNING] packageLoader.__init__(): Template "BEE2_CUTOUT_TILE_FLOOR_SIDE_WORLD" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CUTOUT_TILE_FLOOR_SIDE_DETAIL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CUTOUT_TILE_FLOOR_PILLAR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_BTS_GRATING_TEMPLATE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FLOOR_BUTTON_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CUBE_BUTTON_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_BALL_BUTTON_BASE_BTS" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_EMBEDDED_VOXEL" has no config!
[WARNING] packageLoader.__init__(): Template "__TILING_TEMPLATE__" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_BOTTOM_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_TOP_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_TUNNEL_TILE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_BOTTOM_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_TOP_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_BOTTOM_PORTAL_1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_TOP_PORTAL_1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_RAIL_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_CONVEYOR_COVER_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FUTBOL_SURF_BACK" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FUTBOL_SURF_BACK_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FUTBOL_SURF_BACK_50S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_TOP" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_MIDDLE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_BOTTOM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_TRACK_PLAT_SINGLE" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_OVER" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_P1" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_WHITE_REV" has no config!
[WARNING] packageLoader.__init__(): Template "LAUTARO_PROTRUDING_PED_BASE_BTS_BLACK_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_FLAT_RETRO" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_WHITE_50S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_WHITE_80S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BLACK_50S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BLACK_70S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_BLACK_80S" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_FLAT_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_STATIC_PAN_ANGLED_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_DYNAMIC_PAN_ANGLED_P1" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_FLOOR_BUTTON_BASE_P1_WHITE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_BALL_BUTTON_BASE_P1_WHITE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_ROCKET_TURRET_CAP_CLEAN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_CLEAN_ARROW_WALL_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_RECT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_LONG_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_BTS_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_EXIT_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_50S_NUM_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_WALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_SIGN2_FLOOR_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_SIGNAGE_70s_ARROW_WALL_REV" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_CLEAN_SMALL" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_CLEAN_MEDIUM" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_CLEAN_LARGE" has no config!
[WARNING] packageLoader.__init__(): Template "BEE2_VACTUBE_CORNER_RETRO_MEDIUM" has no config!
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "F:\Git\srctools\srctools\property_parser.py", line 616, in __getitem__
  File "F:\Git\srctools\srctools\property_parser.py", line 402, in _get_value
srctools.property_parser.NoKeyError: No key language!

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 116, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 816, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 618, in __getitem__
IndexError: No key language!
"

**Comment by TeamSpen210** [comment] 2017-06-21 00:36
Could you attach a copy of `SteamApps/app_manifest_620.acf`?

**Comment by eloshima** [comment] 2017-06-22 18:52
Yep c: 
[appmanifest_620.zip](https://github.com/BEEmod/BEE2.4/files/1095855/appmanifest_620.zip)

**Comment by TeamSpen210** [comment] 2017-06-22 20:40
Ok, so that method I was using to get Portal 2's language won't work all the time. Try changing the language set for Portal 2.

**Comment by eloshima** [comment] 2017-06-22 21:43
Oh, Thanks, I'll try this

**Comment by eloshima** [comment] 2017-06-23 11:19
Okay, It's working, just need to put the language on English. Thanks @TeamSpen210

**Comment by Luke18033** [comment] 2017-06-23 14:56
Still a bug though, somebody might want to use a language other than English.

**Comment by TeamSpen210** [comment] 2017-06-23 22:26
Try swapping it back to French. Perhaps then it'll set the config values we want. Alternatively, manially do it - open that app_manifest file, and in the `UserConf` section in the braces add a line `"Language" "French"`.

**Comment by TeamSpen210** [comment] 2019-05-04 02:31
This is a duplicate of #927, and is fixed.

**Closed by TeamSpen210** 2019-05-04 02:31 UTC
Labels: Bug, Translation
