### ISSUE TITLE
An error occured failed to execute script bee2_lanch

### ISSUE THREAD

**Issue by Aleknor0222222** [BEEmod/BEE2.4#1208] opened 2019-11-21 16:05 UTC
im having a issue while its loading

failed to execute script bee2_lanch
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "F:\Git\BEE2.4\src\BEE2.py", line 110, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 1156, in init_trans
  File "F:\Git\BEE2.4\src\gameMan.py", line 1184, in load_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 395, in parse
srctools.property_parser.KeyValError: End of text reached with remaining open sections.

File ended with at least one property that didn't have an ending "}".
Error occurred with file "basemodui.txt".

**Comment by Voidliest** [comment] 2019-11-21 17:24
Same is happening to me!

**Comment by lukelane1984** [comment] 2019-11-21 21:11
Exact same thing here. It worked fine yesterday. stopped working today, and I didn't change anything.

**Comment by TeamSpen210** [comment] 2019-11-21 21:44
Duplicate of #1207

**Comment by TeamSpen210** [comment] 2019-11-21 21:44
There's instructions there on how to fix.

**Closed by TeamSpen210** 2019-11-21 21:44 UTC
Labels: Compile Error
