### ISSUE TITLE
Bee2.4 windows installer

### ISSUE THREAD

**Issue by ellingtonvengaboysmuseum** [BEEmod/BEE2.4#442] opened 2016-12-05 16:32 UTC
we need to have a Bee2.4 windows installer created that will do the following, we also need to merge the packages file into the main bee2.4 before this can happen. i recommend install forge for creating the main installer...

- [x] (prerequisite) merge the packages file into the main Bee2.4 file directory at each release (this is as easy as cake and should be considered already done)
- [ ] install the main program under the program files folder
- [ ] generate a shortcut to the desktop for the main bee2 exe file...

**Comment by TheDarkBomber** [comment] 2016-12-05 16:34
I think you should join the [BEE2.4 Gitter](https://gitter.im/BenVlodgi/BEE2.4)

**Comment by LautaroL20** [comment] 2016-12-05 17:15
I really like the idea of having an installer for this.

**Comment by TheDarkBomber** [comment] 2016-12-05 17:17
I prefer downloading BEE2.4 without an installer.

**Comment by LautaroL20** [comment] 2016-12-05 17:21
Well, personally i would preffer to have the packages and the interface in one file installer, but tastes are tastes i guess.

**Comment by TheDarkBomber** [comment] 2016-12-05 17:28
And flavours are flavours, which should be mostly a delicious variety.

**Comment by Byzarru** [comment] 2016-12-05 21:55
It's not too hard to unzip a package and look for bin/bee2.exe, but I do like my installers... :p

**Comment by Byzarru** [comment] 2016-12-05 21:57
This should definitely be something considered along with #78 to make the process a lot smoother.

**Comment by Luke18033** [comment] 2016-12-21 17:52
@ellingtonvengaboysmuseum Don't put it in Program Files by default. Give the user the option to install it somewhere else.

**Comment by Byzarru** [comment] 2017-01-01 23:57
BEE2 also needs an uninstaller as well.

**Comment by TheDarkBomber** [comment] 2017-02-28 20:18
Duplicate of #77

**Comment by LautaroL20** [comment] 2017-02-28 22:10
@ellingtonvengaboysmuseum - Ive merged your description inside the original suggestion (#77).

**Closed by LautaroL20** 2017-02-28 22:10 UTC
Labels: Duplicate, New Feature
