### ISSUE TITLE
Flamethrower piping in 1960s enrichment sphere in wrong position

### ISSUE THREAD

**Issue by JessicaTTG** [BEEmod/BEE2.4#1828] opened 2022-04-25 21:38 UTC
### BEE2 Application Version

4.41 64bit

### BEE2 Package Version

4.41

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

![20220425153244_1](https://user-images.githubusercontent.com/104395829/165179167-5740b057-41df-4d54-84f8-5c7b4917f6cd.jpg)
Flamethrower piping is in an irregular position.

### Expected behavior

Piping should not originate underneath structure and end out in the middle of nothing

### Steps to reproduce

1. Create a palette with 1960s style Enrichment Sphere and a flamethrower/crusher
2. Launch game, enter PuzzleMaker, place down flamethrower
3. Compile map
4. Observe the issue

**Comment by Luke18033** [comment] 2022-04-25 21:40
Duplicate of BEEmod/BEE2-items#4031

**Closed by Luke18033** 2022-04-25 21:40 UTC
Labels: Bug
