### ISSUE TITLE
Overgrown Style Missing Texture

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#779] opened 2017-11-08 23:06 UTC
I get a missing texture in the overgrown style. (I know this is the same as something else I just can't find the other thing(and I posted the same problem but that disappeared too.))

![20171108180241_1](https://user-images.githubusercontent.com/33005627/32579576-82f09ec2-c4af-11e7-9611-d036ac661102.jpg)
![20171108180247_1](https://user-images.githubusercontent.com/33005627/32579577-8304e558-c4af-11e7-92ad-ef58fdbe9c78.jpg)
![20171108180251_1](https://user-images.githubusercontent.com/33005627/32579578-831b872c-c4af-11e7-8c50-3818783d52b9.jpg)

**Comment by LautaroL20** [comment] 2017-11-09 10:43
You are opening issues in the wrong repository, this one is for reporting bugs related to the Bee2.4 interface, issues related to items must be posted here: https://github.com/BEEmod/BEE2-items/issues

This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2264

**Closed by LautaroL20** 2017-11-09 10:43 UTC
Labels: Duplicate, Item Issue

**Comment by Fazbear189** [comment] 2017-11-09 12:12
THANK YOU SO MUCH I have been looking for that post for days.

**Comment by LautaroL20** [comment] 2017-11-09 13:32
No problem.
