### ISSUE TITLE
Custom inputs and outputs

### ISSUE THREAD

**Issue by Kalail** [BEEmod/BEE2.4#1302] opened 2020-05-12 13:34 UTC
Why can't we build our own entrances and exits, that would be cool! For example you can put the Elevator itself or an introductory table!

**Comment by Flash4433** [comment] 2020-05-12 15:06
You're posting on the wrong repository, refer to [BEEmod/BEE2-Items](https://github.com/BEEmod/BEE2-items).
You can make your own entrances and exits, and even your own styles. You can learn that with some patience and determination with the help of the wiki.
What does the title have to do with the description? Just so you know we have some puzzlemaker's limitations, so check the FAQ on the wiki too.
And I guess this is kinda duplicate of [#3168](https://github.com/BEEmod/BEE2-items/issues/3168) and [#2313](https://github.com/BEEmod/BEE2-items/issues/2313).

**Comment by Luke18033** [comment] 2020-05-12 17:05
See [this comment](https://github.com/BEEmod/BEE2-items/issues/605#issuecomment-230186306) for why we can't really connect the elevator directly to the chamber. As for custom corridors, you can make those with Hammer and use them in BEE. In fact a lot of corridors in certain styles are still missing or in need of updates, so any contributions there would be appreciated.

**Closed by Luke18033** 2020-05-12 17:05 UTC
