### ISSUE TITLE
BTS Massive Leaks Incorrect Entry Door placements.

### ISSUE THREAD

**Issue by MrKrunk** [BEEmod/BEE2.4#244] opened 2016-03-15 03:32 UTC
![20160315185602_1](https://cloud.githubusercontent.com/assets/17092818/13766949/85320756-ea23-11e5-96ff-e3761478f2f2.jpg)

![20160315190049_1](https://cloud.githubusercontent.com/assets/17092818/13766981/b5acffbc-ea23-11e5-985f-02babb680cea.jpg)

**Comment by LautaroL20** [comment] 2016-03-15 07:57
I remember having tested BTS style in both SP and Co-op mode and never saw that nodraw from the first screenshot from up. Did you entered that room afther last door has closed with "Noclip" or so?

**Comment by MrKrunk** [comment] 2016-03-16 00:03
No. I walked through the entrance normally. No cheats of any sort.

**Comment by TeamSpen210** [comment] 2016-03-16 22:57
The broken exit door is actually the cause of the Norris's in the entry area. The misplaced door causes a leak, making the areaportal in the entry not work properly.

**Comment by Konclan** [comment] 2016-04-13 22:29
Yeah BTS is super broken atm, I suppose you could put a warning in the BTS style if its not fixed by next release

**Comment by LautaroL20** [comment] 2016-12-22 00:13
Moved to: https://github.com/BEEmod/BEE2-items/issues/1241

**Closed by LautaroL20** 2016-12-22 00:13 UTC
Labels: Bug, Item´s section
