### ISSUE TITLE
Bring back the cancel button

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#658] opened 2017-06-05 22:32 UTC
![capture](https://cloud.githubusercontent.com/assets/16567080/26806102/b6513e5e-4a14-11e7-8577-19648db227c2.PNG)

Its really annoying how this box doesn't have a cancel button to stop bee from opening Portal 2. Sometimes I export but like a second after hitting the button realize I need to change my pallet. It happens to me way too often.

**Comment by Konclan** [comment] 2017-06-05 22:32
Oh nvm there is are options for this...

**Comment by Konclan** [comment] 2017-06-05 22:33
Well still I want to export and launch the game and minimize Bee while having the option to back out.

**Comment by Luke18033** [comment] 2017-06-05 23:12
Duplicate of #553.

**Closed by Luke18033** 2017-06-05 23:12 UTC
