### ISSUE TITLE
Closed Solid Field not showing 

### ISSUE THREAD

**Issue by Wklaver** [BEEmod/BEE2.4#702] opened 2017-07-30 14:45 UTC
I wanted to use a Closed Solid Field in a test but the texture isn't showing for me.
Screenshot: http://steamcommunity.com/sharedfiles/filedetails/?id=1095205560

**Comment by ZombiePwner1** [comment] 2017-07-30 22:58
Duplicate of https://github.com/BEEmod/BEE2-items/issues/1918

**Closed by ZombiePwner1** 2017-07-30 22:58 UTC
Labels: Duplicate

**Comment by Wklaver** [comment] 2017-07-30 23:01
I didn't know that some one posted all the way back on May 7th about this
