### ISSUE TITLE
BEE 2.4 Error

### ISSUE THREAD

**Issue by S0ME0NERAND0M** [BEEmod/BEE2.4#1056] opened 2019-01-12 20:37 UTC
I was making a Portal 2 map with BEE and then I saved and left my map to finish the next day but when I tried to open BEE the next day I got and error message. I`ve been using BEE for more than 1 year and I have never got an error message before.
![bee 2 4 error](https://user-images.githubusercontent.com/46634050/51078211-fd181500-1705-11e9-9ab0-231f3f23ddfe.JPG) I would like to fix BEE as soon as possible because making Portal 2 maps is one of my favorite things to do I also made a map that got 221 downloads which is pretty big for me and I want to finish off my map.

**Comment by LautaroL20** [comment] 2019-01-12 20:48
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1055

**Closed by LautaroL20** 2019-01-12 20:48 UTC
Labels: Duplicate

**Comment by S0ME0NERAND0M** [comment] 2019-01-13 06:01
Alright i will try to get rid of one of them..

**Comment by S0ME0NERAND0M** [comment] 2019-01-13 06:12
Yeah it worked thanks
