### ISSUE TITLE
The app fails to start and work

### ISSUE THREAD

**Issue by TuAmigoFiel** [BEEmod/BEE2.4#1750] opened 2021-11-05 04:18 UTC
### BEE2 Application Version

4.40.2

### BEE2 Package Version

4.40.0

### What operating system are you running on?

Windows 10 (64bit)

### Logs and Reports

```shell
For an unknown reason, the error was not copied to the clipboard, but I uploaded an image with the error code. It is the first time it has been started and the program does not work. Versions like 4.36 or lower work on me, but the actual ones don't. I know because a time ago I was trying to install this but I got an error message similar to this, so I followed a friend's suggestion to download that version, because it was more stable and he was right. That version worked. The last 2 releases roughly did not work for me. I really want to use the last release but I can't get it to work.
```

### Additional information

![image](https://user-images.githubusercontent.com/50928552/140455202-474cebec-9235-4202-85cf-d071ff8abf57.png)

**Comment by Luke18033** [comment] 2021-11-05 04:19
Duplicate of #1624, it's pinned

**Comment by TuAmigoFiel** [comment] 2021-11-05 04:20
> Duplicate of #1624, it's pinned

I't have a solution?

**Closed by Luke18033** 2021-11-05 04:19 UTC
Labels: Bug, App Crash

**Comment by LautaroL20** [comment] 2021-11-05 04:58
> TuAmigoFiel said: "I't have a solution?"

Yes, it is already fixed for the next BEEmod release.
