### ISSUE TITLE
RIFF ID crashes

### ISSUE THREAD

**Issue by Some-Username-Available** [BEEmod/BEE2.4#1553] opened 2021-04-03 01:57 UTC
```
[ERROR] __init__.tk_error(): Uncaught Exception:
Traceback (most recent call last):
  File "pyglet\media\codecs\wave.py", line 58, in __init__
  File "wave.py", line 509, in open
  File "wave.py", line 163, in __init__
  File "wave.py", line 130, in initfp
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wave.py", line 107, in decode
  File "pyglet\media\codecs\wave.py", line 60, in __init__
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id
```

**Comment by LautaroL20** [comment] 2021-04-03 03:01
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1520

**Closed by LautaroL20** 2021-04-03 03:01 UTC
Labels: Duplicate
