### ISSUE TITLE
Editor Coop Exit door stays closed

### ISSUE THREAD

**Issue by CreatorLockyn** [BEEmod/BEE2.4#1061] opened 2019-01-19 15:45 UTC
So whenever I try to build a Coop map the exit door won't open no matter if something is connected to it or not.
In the Overgrown style it works totally fine but in for example the Clean style the Door just won't open at all no matter what I do.
I do not understand why I have this problem and I only found out after building a whole chamber with the clean style which I can't change to Overgrown since then the Sendificators won't work.
Does anyone have an Idea on what causes this problem and how to fix it?

I opened my console after standing infront of the activated yet closed door and it throws these errors at me:

Stats and achievements are disabled: cheats turned on in this app session
Weapon_portalgun has no owner when trying to upgrade!
Cannot verify load for invalid steam ID [A:1:0:1]
Weapon_portalgun has no owner when trying to upgrade!
!! ERROR: bad input/output link:
!! logic_choreographed_scene(@glados_enter,Trigger) doesn't match type from trigger_once()
An error occurred while attempting to download a file from the UGC server!
An error occurred while attempting to download a file from the UGC server!

**Comment by Luke18033** [comment] 2019-01-19 18:21
Duplicate of BEEmod/BEE2-items#2880

**Closed by Luke18033** 2019-01-19 18:21 UTC
