### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by SPAHI4** [BEEmod/BEE2.4#492] opened 2017-01-21 09:26 UTC
2.4.0pr24
Overgrown style. 
With clean style all works.
```
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[WARNING] cond.core.weighted_random(): Failed parsing weight! ([])
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting Coop Exit to 1
[INFO] vbsp.get_map_info(): Game Mode: COOP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (202 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.core.res_goo_debris(): GooDebris: 3/20 locations
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[ERROR] cond.core.check_all(): Error in condition:
Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 522, in check_all
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 343, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1651, in res_sub_condition
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 354, in test
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 343, in test_result
  File "<string>", line 1, in <lambda>
  File "F:\Git\BEE2.4\src\conditions\brushes.py", line 586, in res_import_template
  File "F:\Git\BEE2.4\src\conditions\__init__.py", line 1103, in import_template
KeyError: 'single'
```

**Comment by TheDarkBomber** [comment] 2017-01-21 10:14
Use Exit Corridor No. 3.

**Comment by SPAHI4** [comment] 2017-01-21 10:38
@TheDarkBomber still error. 
The map is coop.

**Comment by TheDarkBomber** [comment] 2017-01-21 10:44
Then use Single Player.

**Comment by SPAHI4** [comment] 2017-01-21 11:50
![image](https://cloud.githubusercontent.com/assets/1670998/22174174/e8fa5430-dfe8-11e6-9eff-cc3e81352f2c.png)

**Comment by LautaroL20** [comment] 2017-01-21 13:19
@SPAHI4 - Did you have the Protruding Pedestal Buttons anywhere in your map?

**Comment by SPAHI4** [comment] 2017-01-21 13:19
@LautaroL20 yes

**Comment by TheDarkBomber** [comment] 2017-01-21 13:21
He's implying to get rid of them.

**Comment by LautaroL20** [comment] 2017-01-21 13:22
@SPAHI4 - Thats the cause of your issue then - The "Right" and "Left" positions causes this problem, try using the "Middle" one instead.

**Comment by SPAHI4** [comment] 2017-01-21 13:25
@LautaroL20 thanks I'll try

**Comment by LautaroL20** [comment] 2017-01-21 13:26
This issue happens in Overgrown though. All the positions does work well in the rest of styles.

**Comment by LautaroL20** [comment] 2017-01-21 13:33
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1422

**Closed by LautaroL20** 2017-01-21 13:33 UTC
