### ISSUE TITLE
A stupidly cool idea

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2.4#616] opened 2017-05-10 10:21 UTC
could you make the portal 1 intro availiable for clean, overgrown, & portal 1 styles? It should be a option for the compiler but will not be a random choice if you click random. This would make it easier to make a series

**Comment by ZombiePwner1** [comment] 2017-05-10 12:57
This will definitely work for single player but not coop.

**Comment by Luke18033** [comment] 2017-05-10 13:53
Duplicate of BEEmod/BEE2-items#1245.

**Comment by Luke18033** [comment] 2017-05-10 13:54
Also a BEE2-items issue

**Closed by Luke18033** 2017-05-10 13:53 UTC
Labels: Suggestion

**Comment by TeamSpen210** [comment] 2017-05-10 20:13
And I don't think a PeTI 'series' would work very well. For that you need story and dialogue, which you can't really get without Hammer.
