### ISSUE TITLE
DONT FUCKING CLOSE THIS UNTIL YOU HAVE A REAL DAMN REASON TO, AND ALSO, I WANT ACTUAL HELP NOT "dUpLiCaTe!!!!!!!"

### ISSUE THREAD

**Issue by dsagfa** [BEEmod/BEE2.4#1672] opened 2021-08-18 00:05 UTC
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 113, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 331, in mkstemp
  File "tempfile.py", line 250, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\bradl\\AppData\\Roaming\\BEEMOD2\\config\\tmpqd7plvvw'

**Comment by CardsAndGamesYT** [comment] 2021-08-18 00:19
bro, chill with the tittle

**Comment by CardsAndGamesYT** [comment] 2021-08-18 00:20
To fix:
1.  Press WINDOWS+R
2.  Enter %AppData%\BEEMOD2
3. Make a new folder and name it Config

**Comment by CardsAndGamesYT** [comment] 2021-08-18 00:21
everyone has been having this issue, its just a problem with beemod. it should be fixed in the next update.

**Comment by CardsAndGamesYT** [comment] 2021-08-18 00:27
also when they say "duplicate" its because this is a problem someone has reported already and they always list the problem number. if you click it you will be sent to the issue that yours is a duplicate of. from there read the comments and see what's been going on with that one. chances are that your answer will be there.

**Comment by koerismo** [comment] 2021-08-18 00:38
Duplicate of #1624 ;)

**Comment by CardsAndGamesYT** [comment] 2021-08-18 00:38
XD

**Comment by ExoBot343** [comment] 2021-08-18 00:41
wow, it's almost as if they call it a "duplicate" because the issue has already been reported
almost as if you can see the solution in that issue instead

**Comment by DrMeepster** [comment] 2021-08-18 00:46
chill out lol, it's just girhub issues why are you getting so angry over this

**Comment by FrozenDragon0** [comment] 2021-08-18 01:02
Same as https://github.com/BEEmod/BEE2.4/issues/1624. Also your not going to get any help with an attitude like that.

**Closed by FrozenDragon0** 2021-08-18 01:02 UTC
Labels: Duplicate, App Crash
