### ISSUE TITLE
Grammar.txt error on mac?

### ISSUE THREAD

**Issue by bertram1isu** [BEEmod/BEE2.4#974] opened 2018-08-21 02:37 UTC
Hi,

I tried following the mac build instructions here https://github.com/BEEmod/BEE2.4#build-from-source-mac, but ran into an error when trying to launch the BEE2.4 binary.

I wasn't able to successfully get pipenv to work (the pipenv install requests command failed)... but I attempted to just use pip instead... this *mayyyybe* is part of my issue, but the error didn't seem to line up.

Anyway, using the 2.4.0.pr29 tag and building and running as follows:

python compile_BEE2.py build
python compile_VBSP_VRAD.py build
cd ../build_BEE2/bin
./BEE2

I have much sadness:

joshs-macbook:bin gretchee$ ./BEE2
[INFO] utils.setup_localisations(): Language: 'en_US'
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
Tcl_ServiceModeHook: Notifier not initialized
[ERROR] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/pyglet/__init__.py", line 378, in __getattr__
    return getattr(self._module, name)
AttributeError: 'NoneType' object has no attribute 'EventDispatcher'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/BEE2.4/src/BEE2.py", line 19, in <module>
    import UI
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/BEE2.4/src/UI.py", line 11, in <module>
    from itemPropWin import PROP_TYPES
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/BEE2.4/src/itemPropWin.py", line 10, in <module>
    import sound
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/BEE2.4/src/sound.py", line 51, in <module>
    import pyglet.media
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/pyglet/media/__init__.py", line 82, in <module>
    from .player import Player, PlayerGroup
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/pyglet/media/player.py", line 48, in <module>
    class Player(pyglet.event.EventDispatcher):
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/pyglet/__init__.py", line 384, in __getattr__
    __import__(import_name)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/pyglet/event.py", line 139, in <module>
    from past.builtins import basestring
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/past/__init__.py", line 88, in <module>
    from past.translation import install_hooks as autotranslate
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/site-packages/past/translation/__init__.py", line 42, in <module>
    from lib2to3.refactor import RefactoringTool
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/lib2to3/refactor.py", line 25, in <module>
    from .fixer_util import find_root
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/lib2to3/fixer_util.py", line 7, in <module>
    from .pygram import python_symbols as syms
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Users/gretchee/anaconda3/lib/python3.6/lib2to3/pygram.py", line 32, in <module>
    python_grammar = driver.load_grammar(_GRAMMAR_FILE)
  File "/Users/gretchee/anaconda3/lib/python3.6/lib2to3/pgen2/driver.py", line 124, in load_grammar
    g = pgen.generate_grammar(gt)
  File "/Users/gretchee/anaconda3/lib/python3.6/lib2to3/pgen2/pgen.py", line 385, in generate_grammar
    p = ParserGenerator(filename)
  File "/Users/gretchee/anaconda3/lib/python3.6/lib2to3/pgen2/pgen.py", line 15, in __init__
    stream = open(filename)
NotADirectoryError: [Errno 20] Not a directory: '/Users/gretchee/BEE2.4/build_BEE2/bin/lib/library.zip/lib2to3/Grammar.txt'

Is this maybe due to using anaconda rather than vanilla python?  Any other ideas?

Thanks and apologies if I've missed something obvious!
- J.

**Comment by bertram1isu** [comment] 2018-08-21 02:39
Oh, and I inspected library.zip in Finder and confirmed that Grammar.txt is not present in the file, though I don't think that was my original exception.

**Comment by TeamSpen210** [comment] 2019-05-04 00:58
This is fixed now.

**Closed** 2019-05-04 00:58 UTC

**Comment by LautaroL20** [comment] 2019-05-04 01:07
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
