### ISSUE TITLE
This is not another issue of PR25

### ISSUE THREAD

**Issue by Konata-Chan** [BEEmod/BEE2.4#608] opened 2017-05-07 02:51 UTC
![spencer](https://cloud.githubusercontent.com/assets/25024629/25777470/d00db998-32b4-11e7-8646-419b9ca6edee.png)

I have no idea if this is duplicated.

**Comment by ZombiePwner1** [comment] 2017-05-07 02:53
Get the config files from prl 24 and replace the the prl 25 ones with prl 24. Also duplicate of https://github.com/BEEmod/BEE2.4/issues/603

**Closed by ZombiePwner1** 2017-05-07 02:53 UTC
Labels: Bug, Crash, Duplicate

**Comment by Konata-Chan** [comment] 2017-05-07 03:01
Ok I re-downloaded it and now it works fine
