### ISSUE TITLE
Rocket Turret Problems

### ISSUE THREAD

**Issue by homelessturret** [BEEmod/BEE2.4#731] opened 2017-09-02 15:10 UTC
It seems the rocket turrets lock on, but they don't fire, the firing sound effect is made but no actual eplosion.

**Comment by LautaroL20** [comment] 2017-09-02 17:50
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/1984

**Closed by LautaroL20** 2017-09-02 17:50 UTC
Labels: Bug, Duplicate

**Comment by homelessturret** [comment] 2017-09-02 18:47
@LautaroL20 This isn't a duplicate, i can see the rocket turret and it (sort of) works, it just doesn't fire rockets.

**Comment by LautaroL20** [comment] 2017-09-02 19:18
Its a duplicate, the original post says "And if it appears in the map, its really buggy".

**Comment by homelessturret** [comment] 2017-09-02 20:59
Regardless, i hope this can be fixed in V26

**Comment by LautaroL20** [comment] 2017-09-02 21:57
I doubt, this item has been ignored for a while.
