### ISSUE TITLE
Portalable/Non-Portalable Piston Platform

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#266] opened 2016-03-31 02:25 UTC
Like the extending piston plateform, The extending panel would push in and out, except you can make it portable and non-portable.

**Comment by TeamSpen210** [comment] 2016-03-31 02:52
You mean a portalable/non-portalable piston platform, or using panel arms?

**Comment by Konclan** [comment] 2016-03-31 02:54
Piston plateform

**Comment by LautaroL20** [comment] 2016-12-22 00:14
This will gonna be implemented, and also this is a duplicate of the item´s list: https://github.com/BEEmod/BEE2-items/issues/95

**Closed by LautaroL20** 2016-12-22 00:14 UTC
Labels: duplicate, enhancement, Item´s section
