### ISSUE TITLE
Beemod crashes - Failed to Execute script BEE2_launch

### ISSUE THREAD

**Issue by dBianchii** [BEEmod/BEE2.4#1604] opened 2021-06-02 02:33 UTC
I downloaded both https://github.com/BEEmod/BEE2-items/releases/tag/v4.39.1
and also https://github.com/BEEmod/BEE2.4/releases/tag/2.4.39.1. (64x)

After placing package folder inside beemod, I get:

Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media__init.py", line 140, in load
  File "pyglet\media__init.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in init
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] The byte stream type of the given URL is unsupported

And another window says "Failed to Execute script BEE2_launch"

![image](https://user-images.githubusercontent.com/17372417/120415254-9d9c1d80-c331-11eb-86e3-4a7ccf49023b.png)

**Comment by Lieutenant-L-T-Smash** [comment] 2021-06-02 04:32
Take a look at this: https://github.com/BEEmod/BEE2.4/issues/1520#issuecomment-830832278

**Comment by LautaroL20** [comment] 2021-06-02 23:50
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521, the issue is even pinned.

**Closed by LautaroL20** 2021-06-02 23:50 UTC
Labels: App Crash
