### ISSUE TITLE
BEEMOD Shows up as a false positive in Avast Antivirus

### ISSUE THREAD

**Issue by ikifar2012** [BEEmod/BEE2.4#554] opened 2017-03-17 15:20 UTC
Avast said that beemod was acting malicious when I exported the second time to Portal 2

**Comment by Luke18033** [comment] 2017-03-17 16:03
Duplicate of #355. I don't think this can be fixed, unfortunately.

**Closed by Luke18033** 2017-03-17 16:03 UTC

**Comment by TeamSpen210** [comment] 2017-03-18 02:18
Well it does overwrite exe files, that might be seen as suspicious...
