### ISSUE TITLE
Srctools._math.Vec

### ISSUE THREAD

**Issue by TacticalMeme** [BEEmod/BEE2.4#1487] opened 2021-02-16 10:32 UTC
This popped up for some reason and I have not a slight clue as to why.

VBSP failed.

[I] vbsp.main(): BEE2 v4.38.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "F:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "F:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] texturing.load_config(): special: Unknown texture names edge_special, pedestalside
[I] cond.core.build_itemclass_dict(): Read 30 item IDs, with 48 embeds!
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (3 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting Coop Exit to 1
[I] vbsp.get_map_info(): Game Mode: COOP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (425 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.FLOOR.BLACK: 65 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.WHITE: 73 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.CEILING.BLACK: 73 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.WHITE: 101 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): NORMAL.WALL.BLACK: 101 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.FLOOR.BLACK: 65 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.CEILING.BLACK: 73 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.WHITE: 101 Clumps for 1519 tiles
[I] texturing.setup(): Generating texture clumps...
[I] texturing.setup(): PANEL.WALL.BLACK: 101 Clumps for 1519 tiles
[I] cond.core.check_all(): Checking Conditions...
[I] cond.core.check_all(): -----------------------
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE_PGUN_BASE", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_60", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_45", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_ANGLED_BLOCK_CORNER_30", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_QUARTER", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_HALF", which is no longer used.
[W] brushes.res_import_template_setup(): replaceBrush command used for template "BEE2_FLAT_THREE_QUARTER", which is no longer used.
[E] cond.core.check_all(): Error in <VALVE_GEOMETRY>/items/stairs:
Traceback (most recent call last):
  File "precomp\conditions\__init__.py", line 523, in check_all
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\__init__.py", line 1139, in res_sub_condition
  File "precomp\conditions\__init__.py", line 312, in test
  File "precomp\conditions\__init__.py", line 301, in test_result
  File "<string>", line 1, in <lambda>
  File "precomp\conditions\brushes.py", line 239, in res_set_texture
  File "precomp\template_brush.py", line 384, in rotate
  File "srctools\vmf.py", line 1275, in localise
TypeError: unsupported operand type(s) for @: 'srctools._math.Vec' and 'srctools._math.Vec'

**Comment by TeamSpen210** [comment] 2021-02-16 11:41
This is a duplicate of BEEmod/BEE2-items#3613

**Closed by TeamSpen210** 2021-02-16 11:41 UTC
