### ISSUE TITLE
Display a Text-Box Message when an update is available - Make it to choose between Yes / No

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#593] opened 2017-05-01 18:26 UTC
This would be a great thing and here´s why, i saw TOO MANY mappers who uses Beemod and they just keeps using an outdated as hell PRL 18 / 19 / 20 - I really don´t get it if they are just too lazy to check the Github Repository or they just don´t care about upgrading. There is a serious issue with this.....All their followers keeps playing the same buggy and outdated maps once and once again.

_____________________________________________________________________________________________

### If click "Yes", it will redirect to the Items and App download releases, or it can just directly start downloading both packages.

# Concept Art:

![Image](https://cloud.githubusercontent.com/assets/12244376/25589240/3ab4fcde-2e82-11e7-8c4d-a910e7c68ae6.jpg)

**Comment by hop193** [comment] 2017-05-03 19:50
abailable?

**Comment by LautaroL20** [comment] 2017-05-04 01:20
@hop193 - Well, it will be available with the PRL25 said TeamSpen210 via Discord.

**Comment by Konclan** [comment] 2019-08-28 22:42
Actually, this is a duplicate of #78

**Closed** 2019-08-28 22:43 UTC
Labels: Duplicate, Enhancement

**Comment by LautaroL20** [comment] 2019-08-28 23:11
Thanks for porting the picture.
