### ISSUE TITLE
Re-adding items from old BeeMOD back to the new one?

### ISSUE THREAD

**Issue by HumanPerson2** [BEEmod/BEE2.4#959] opened 2018-07-16 11:05 UTC
Things like catapult cubes, bomb droppers or breakable glass being re-added back to the new version? Since they proved very useful for building tests before and it would be cool to see them added back. Or maybe adding new items like the adhesion gel (if possible).

**Comment by HugoBDesigner** [comment] 2018-07-16 11:16
Duplicate of #95 
See also: [FAQ](https://github.com/BEEmod/BEE2-items/wiki/FAQ#can-you-add-bee22tspenaddons-items-to-bee24)

**Closed by HugoBDesigner** 2018-07-16 11:16 UTC
