### ISSUE TITLE
Portal Reloaded music Built into BEE2

### ISSUE THREAD

**Issue by TPEcool** [BEEmod/BEE2.4#1745] opened 2021-11-01 10:28 UTC
### Description of the feature

I think it would be nice to have Portal Reloaded music be built into BEE2, so you don't have to spend time importing it through BMMC2 and then manually configuring it.

### Why should this be implemented

It would be very comfortable as a built-in feature.

**Comment by CN1o2** [comment] 2021-11-01 12:03
Although I'm not a supporter of bee2, I think it would be a good idea to add them. Because the songs from Portal Reloaded are wonderful!

**Comment by Luke18033** [comment] 2021-11-01 13:59
Duplicate of BEEmod/BEE2-music#2

**Closed by Luke18033** 2021-11-01 13:59 UTC
Labels: Enhancement
