### ISSUE TITLE
Custom Soundscape Feature

### ISSUE THREAD

**Issue by LegendofZeldaBros** [BEEmod/BEE2.4#1740] opened 2021-10-13 21:14 UTC
### Description of the feature

this could be like a trigger, and you could set the radius of how large it would be (like in hammer). this item could just be a simple env_soundscape or env_soundscape_triggerable. and you could have multiple of them in a level.

### Why should this be implemented

while this might not be the most groundbreaking possible item, for possible maps with no music, this could help. in the selection category, you might be able to preset a couple of different soundscapes you want to use in your level, and then you could chose which ones you want in a little window in the selection menu.

### Additional information

this video might be helpful: [https://www.youtube.com/watch?v=N9TnPQUQi6w](url)

**Comment by Luke18033** [comment] 2021-10-13 22:08
Duplicate of BEEmod/BEE2-items#386

**Closed as completed by Luke18033** 2021-10-13 22:08 UTC
Labels: Duplicate, Enhancement
