### ISSUE TITLE
AttributeError: module 'srctools' has no attribute 'AtomicWriter'

### ISSUE THREAD

**Issue by torzod** [BEEmod/BEE2.4#890] opened 2018-04-08 22:06 UTC
when running `BEE2_config.py` on Arch Linux in Python 3.6.4, i am getting the following output:
```Traceback (most recent call last):
  File "BEE2_config.py", line 149, in <module>
    GEN_OPTS = ConfigFile('config.cfg', auto_load=False)
  File "BEE2_config.py", line 26, in __init__
    self.writer = srctools.AtomicWriter(self.filename)
AttributeError: module 'srctools' has no attribute 'AtomicWriter'
```

**Comment by TeamSpen210** [comment] 2018-04-09 01:38
Duplicate of #891

**Closed by TeamSpen210** 2018-04-09 01:38 UTC

**Comment by LautaroL20** [comment] 2018-04-11 14:27
@TeamSpen210 - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

Do not apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
