### ISSUE TITLE
PR25 is Broken!

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#604] opened 2017-05-07 00:11 UTC
Okay, I'm getting some really bad errors now:
![image](https://cloud.githubusercontent.com/assets/26728974/25784965/bb5a4892-332a-11e7-8bc5-b85140e1ab5e.png)

**Comment by LautaroL20** [comment] 2017-05-07 01:27
There are some few steps that all people who had previous beemod versions must do, ill coment on this in some minutes.

**Comment by hop193** [comment] 2017-05-07 04:16
> in some minutes.

*3 hours later*

**Comment by peefTube** [comment] 2017-05-07 04:44
> in some minutes.
> 3 hours later

I think he probably meant hours.

**Comment by LautaroL20** [comment] 2017-05-07 06:00
Okay, after 5 mileniums later, i came back with the comment:

What you should do first (and for anyone who had a previous Beemod version) is delete the "bee2" folder insisde the Portal 2 directory which contains all the bee materials & models, so the game doesn´t keep using the old resources from previous Beemod releases.

Since the PRL25 doesn´t override / delete the files in those folders anymore, now you have to do it manually.
After you delete those mentioned folders, launch the PRL25, then do what i call a "Full Export" that consist in having the option "Preserve game directories" unchecked. Then you should be able to enjoy it without major bugs.

**Comment by LautaroL20** [comment] 2017-05-07 06:00
BTW sorry for the wait, guys.

**Comment by peefTube** [comment] 2017-05-07 20:02
Thanks! I'll try it right now and tell you if it works 😄

**Comment by peefTube** [comment] 2017-05-07 20:06
Okay, I'm noticing that BEEMod is skipping the export of packages, etc. after deletion of the bee2 directory.

**Comment by peefTube** [comment] 2017-05-07 20:16
And... nothing. BEEMod appears to be, well, broken.

**Comment by peefTube** [comment] 2017-05-07 20:40
Okay, I'm getting some really bad errors now:
![image](https://cloud.githubusercontent.com/assets/26728974/25784965/bb5a4892-332a-11e7-8bc5-b85140e1ab5e.png)

What the heck is going on?! @TeamSpen210 @LautaroL20

**Comment by LautaroL20** [comment] 2017-05-07 22:37
Ah, thats another bug that was fixed in Dev, and now i see that in the PRL25 the bug is still there...... Well, in order to solve it, go to "File"-->"Options"---->"Development"-----> Here you must uncheck "Preserve game directories", that way Beemd will not skip the packages export.

**Comment by peefTube** [comment] 2017-05-07 23:03
> Ah, thats another bug that was fixed in Dev, and now i see that in the PRL25 the bug is still there...... Well, in order to solve it, go to "File"-->"Options"---->"Development"-----> Here you must uncheck "Preserve game directories", that way Beemd will not skip the packages export.

Did that several times, too. Never helped once.

**Comment by LautaroL20** [comment] 2017-05-07 23:27
> peefTube said: "Did that several times, too. Never helped once."

It is weird that this release got bugs that were supposedly be fixed a time ago, and they are present in this release. If you can´t export properly with PRL25, then i´d suggest you to keep with PRL24 for now, until a patch is release.

**Comment by peefTube** [comment] 2017-05-14 02:42
> peefTube said: "Did that several times, too. Never helped once."
> It is weird that this release got bugs that were supposedly be fixed a time ago, and they are present in this release. If you can´t export properly with PRL25, then i´d suggest you to keep with PRL24 for now, until a patch is released.

Will the PR25 packages work with PR24?

**Comment by TeamSpen210** [comment] 2017-05-14 05:59
@Lautaro, this isn't a BEE2 bug, it's a computer problem. I'm actually not sure what major bugs are returning again...

The packages will not work.

**Comment by LautaroL20** [comment] 2017-05-14 06:36
> TeamSpen210 Said: "I'm actually not sure what major bugs are returning again..."

* Bee2.4 is not using the letter from the first word on its "Export Button" (#606)
* Textures from Overgrown Rusted Pillars are missing (#1938)
* Overgrown Left - Right Protruding Buttons causes failure to compile (#1927)

These are the ones i am 100% sure who should have been entirely fixed in PRL25 but they aren´t. My small hypothesis is that Github has nothing to do with this, but before the uploading process, some old resources may got mixed up with the new ones and thats the cause for this.

**Comment by LautaroL20** [comment] 2017-10-28 17:02
@peefTube - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, it is very important you do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Closed by LautaroL20** 2017-10-28 17:02 UTC
Labels: Bug
