### ISSUE TITLE
The option "Door Cameras" does not work at all, the entry/exit doors will include cameras even with it unchecked, in Overgrown Style.

### ISSUE THREAD

**Issue by markd0811** [BEEmod/BEE2.4#894] opened 2018-04-12 18:03 UTC
Tested in PR28. PR29 change notes do not suggest fix.

The default entry and exit doors are rendered with cameras above them given space. If a door is placed on a wall at least 20 ft / 2 tiles high, the camera appears above it after an export in which "Door Cameras" is unchecked.

Awesome mod! Thank you for creating and supporting!

**Comment by LautaroL20** [comment] 2018-04-13 00:44
@TeamSpen210 - No, i do not think this is the case of an "item issue" since this directly involves an option from the user interface which is not working at all.

**Comment by TeamSpen210** [comment] 2018-04-13 02:17
Stylevars are entirely defined in the packages.

**Comment by Luke18033** [comment] 2018-07-13 17:46
Duplicate of BEEmod/BEE2-items#1798.

**Closed by Luke18033** 2018-07-13 17:46 UTC
Labels: Bug, Item Issue, Stylevar
