### ISSUE TITLE
BEE2.4 ERROR: can't play music when chossing via the export options.

### ISSUE THREAD

**Issue by ZonkedHobgoblin** [BEEmod/BEE2.4#1057] opened 2019-01-13 14:21 UTC
Whenever I try to use the export options to choose a soundtrack/song, I click the the play button to listen to it and crashes. The error is this: Traceback (most recent call last):
  File "F:\Git\BEE2.4\src\sound.py", line 200, in play_sample
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1429, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\__init__.py", line 1405, in load
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 238, in __init__
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\pyglet\media\avbin.py", line 196, in f
OSError: exception: access violation reading 0x00000000

**Comment by LautaroL20** [comment] 2019-01-13 22:14
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1035

**Closed by LautaroL20** 2019-01-13 22:14 UTC
Labels: Duplicate
