### ISSUE TITLE
[Portal 1 Style] Excursion funnel not properly rendering

### ISSUE THREAD

**Issue by SimplyJustDanny** [BEEmod/BEE2.4#1885] opened 2022-11-26 01:13 UTC
### BEE2 Application Version

4.42.0 64bit

### BEE2 Package Version

4.42.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

I dunno if this is a problem exclusive to the Portal 1 style, but basically the excursion funnel machines are not properly rendering. Instead of the usual revolving mechanism, in its place is just an octagon with null, artifact rendering inside of it.

### Expected behavior

That the excusion funnel be there.

### Steps to reproduce

Step 1. Export BEE with Portal 1 style and funnel
Step 2. add funnel to floor of a custom map and build
Step 3. See

**Comment by FrozenDragon0** [comment] 2022-11-26 01:19
Posted in the wrong section.
And this would seem to be a duplicate of https://github.com/BEEmod/BEE2-items/issues/4241, so I'll add the Portal 1 label to that.

**Closed by FrozenDragon0** 2022-11-26 01:19 UTC
Labels: Bug, Duplicate
