### ISSUE TITLE
Saving DXT1 Not implemented! (Portal 2 export crash)

### ISSUE THREAD

**Issue by ThaBluNate** [BEEmod/BEE2.4#1673] opened 2021-08-19 00:19 UTC
**BEE2 version: 4.40.2**
(i also tried a version that was compiled from src that also didn't work)

**Description of the bug:**
if you export to portal 2 it crashes

**Steps to reproduce:**
Try to export to portal 2 AT ALL
(i have even tried by just getting a new beemod install and just exporting)

**Error log:**
```
Traceback (most recent call last):
  File "app\UI.py", line 829, in export_editoritems
  File "app\gameMan.py", line 698, in export
  File "packages\signage.py", line 221, in export
  File "packages\signage.py", line 295, in build_texture
  File "srctools\vtf.py", line 842, in save
  File "srctools\_py_vtf_readwrite.py", line 129, in save
NotImplementedError: Saving DXT1 not implemented!
```

**Comment by Konclan** [comment] 2021-08-19 02:14
Duplicate of #1660

**Closed by Konclan** 2021-08-19 02:14 UTC
Labels: App Crash
