### ISSUE TITLE
P1 portal gun isn't working

### ISSUE THREAD

**Issue by Denver124** [BEEmod/BEE2.4#599] opened 2017-05-03 23:57 UTC
The portal gun from the portal 1 style isn't qworking everythime when i start testiomg the test chamber the portal gun was still at the ortiginal oen, cam you pleaze fix it dor me?

**Comment by Luke18033** [comment] 2017-05-04 00:27
Duplicate of BEEmod/BEE2-items#1099.

**Closed** 2017-05-04 00:32 UTC
Labels: BEE2-items Issue, Bug, Duplicate
