### ISSUE TITLE
Standing Laserfields

### ISSUE THREAD

**Issue by PieCreeper12** [BEEmod/BEE2.4#1206] opened 2019-11-16 04:40 UTC
BEE2 has standing fizzlers, so I thought why not also have standing laserfields? Standing laserfields would be the same as standing fizzlers but with a laserfield.

**Comment by TeamSpen210** [comment] 2019-11-16 07:02
I’m working on a revamp for that item which lets you make it any type of fizzler.

**Comment by Luke18033** [comment] 2019-11-16 07:08
Duplicate of BEEmod/BEE2-items#3013

**Closed by Luke18033** 2019-11-16 07:08 UTC
