### ISSUE TITLE
BEE crashes when trying to open Backup

### ISSUE THREAD

**Issue by Thedoczek** [BEEmod/BEE2.4#1498] opened 2021-02-21 16:37 UTC
```
Traceback (most recent call last):
  File "app\backup.py", line 557, in show_window
  File "app\backup.py", line 641, in ui_refresh_game
NameError: name 'gameMan' is not defined

```

**Comment by seagemgames** [comment] 2021-02-22 11:06
Duplicate of #1457

**Closed** 2021-02-23 05:26 UTC
Labels: App Crash, Duplicate
