### ISSUE TITLE
Music not playing in co-op chambers for my partner...

### ISSUE THREAD

**Issue by epicduck64** [BEEmod/BEE2.4#975] opened 2018-08-25 00:53 UTC
Whenever I load my levels, I notice my friend just only hears background noise from the ambient noise.
It doesn't even attempt to play in the console. No error. Just nothing about the sound failing to play.
If you could please help fix this, this would be great! Music means a lot to levels. I'm not saying this is an urgent update though, as music doesn't ruin gameplay.

**Comment by ZombiePwner1** [comment] 2018-08-26 05:57
@epicduck64 Does the music play for you tho? If so this bug is a pretty common bug as it has happened to me a few times when playing as p-body in coop chambers. I'm not sure if this is a bug with the source code though, If it is we can't fix it unfortunately.

**Comment by Luke18033** [comment] 2018-08-26 14:57
What music are you using? If it's custom (not from P2), it's probably not being packed into the map for some reason.

**Comment by epicduck64** [comment] 2018-08-29 05:56
It does play for me, sometimes it plays when my friend loads the level as blue, but I noticed that I played my friends sp level, and joined his mp level and the same music played, but he said it was different.

**Comment by epicduck64** [comment] 2018-10-01 04:18
bump

**Comment by epicduck64** [comment] 2018-10-08 23:12
I was playing music that was from Portal 2. I am pretty sure it was There She Is.

**Comment by epicduck64** [comment] 2019-01-04 10:54
bump?

**Comment by DogeIsCut** [comment] 2019-02-17 05:35
bumpity

**Comment by LautaroL20** [comment] 2019-02-17 06:09
So, doesn´t the Pre-Release 33.1 fix this issue yet? I should give it a test with my wheely parthner @ZombiePwner1 and see if it still persists then.

**Comment by ZombiePwner1** [comment] 2019-02-17 06:18
@LautaroL20 Says the wheely.

**Comment by Konclan** [comment] 2019-08-28 21:20
Duplicate of #912

**Closed** 2019-08-28 21:20 UTC
Labels: Bug, Duplicate
