### ISSUE TITLE
There was an error building the puzzle

### ISSUE THREAD

**Issue by deskill** [BEEmod/BEE2.4#727] opened 2017-08-31 13:41 UTC
Inside the portal 2 level editor, when I try to build the level I get this in the console

VBSP failed.

Traceback (most recent call last):
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 20, in <module>
zipimport.ZipImportError: not a Zip file

I'm using BEE2.4.0pr25
The Bee mod files are in documents.
Building the puzzle still doesn't work when there is no objects or/and the everything is set to default in BEE2.exe
I've tried reinstalling it before

**Comment by LautaroL20** [comment] 2017-08-31 17:05
This clearly seems to be an issue caused by the game for using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by TeamSpen210** [comment] 2017-08-31 19:56
I don't know if that'll fix the issue, it indicates something's wrong with the `python36.zip` file specifically.

**Comment by deskill** [comment] 2017-08-31 20:18
It doesn't fix it

**Comment by LautaroL20** [comment] 2017-08-31 21:52
@deskill - Take care that Linux or Mac os x versions do not work well, also make sure you are using the same pre-release versions from both the Application and Packages.

**Comment by deskill** [comment] 2017-09-01 07:37
I am on Windows 10 and I tried with BEE2.4_pr25.3_win.zip and BEE2.4.0pr25_packages.zip
I've installed bee 2.25 before

**Comment by deskill** [comment] 2017-09-01 16:02
Here is what the console says in it's entirety
http://steamcommunity.com/sharedfiles/filedetails/?id=1124859788

**Comment by LautaroL20** [comment] 2017-09-01 16:42
That does not help. Turn on developer 2, then to clear all the unnecesary data, type clear. Then build the puzzle and copy paste the full console log, here.

**Comment by deskill** [comment] 2017-09-01 18:51
Here it is.

[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 40 (ms)

VBSP failed.

Traceback (most recent call last):
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 20, in <module>
zipimport.ZipImportError: not a Zip file


An error occurred while attempting to download a file from the UGC server!

**Comment by LautaroL20** [comment] 2017-10-28 16:34
@deskill - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however, once you installed the latest version, you will have to do the following to ensure everything will work fine:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Closed by LautaroL20** 2017-10-28 16:34 UTC
Labels: Compile error
