### ISSUE TITLE
Error on Launch

### ISSUE THREAD

**Issue by LolekLiam** [BEEmod/BEE2.4#1593] opened 2021-05-23 20:07 UTC
**BEE2 version:** v4.39.2 (64-bit)

**Description of the bug:** 
Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] The byte stream type of the given URL is unsupported

**Steps to reproduce:** I just start the program and the error occurres.

**Additional information:** 
![error1](https://user-images.githubusercontent.com/63475764/119275014-089f7300-bc13-11eb-8d6a-3819a1698406.png)
![error2](https://user-images.githubusercontent.com/63475764/119275018-0ccb9080-bc13-11eb-92c5-9b67bce3706c.png)

**Comment by LautaroL20** [comment] 2021-05-23 21:35
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Comment by LautaroL20** [comment] 2021-05-23 21:35
The issue is even pinned...

**Closed by LautaroL20** 2021-05-23 21:35 UTC
Labels: App Crash
