### ISSUE TITLE
[Suggestion] Make it simpler to install BEEmod

### ISSUE THREAD

**Issue by RealDeadlyOne** [BEEmod/BEE2.4#930] opened 2018-06-07 17:05 UTC
I am currently having issues with installing the brand-new version of BEEmod, and it would be much easier for less tech-savvy people to have an installer.

**Comment by Konclan** [comment] 2018-06-07 17:18
Duplicate of #279

**Closed** 2018-06-07 17:19 UTC

**Comment by LautaroL20** [comment] 2018-06-09 03:03
@Konclan - Do not forget to apply the label after closing an issue; since although it may sounds unbelievable, there are some people who still checks inside the "closed issues" tab in order to see which issues were solved/closed and their reasons. So, having them shorted with the proper label after closing will help people to understand the real cause of its closure.

There is no need to apply aditional labels such as "enhancement", "new item" etc, when the issue is invalid/duplicate. The "invalid" or "duplicate" labels are just enough to clarify a reason for it.
