### ISSUE TITLE
error when launching on windows 8.1

### ISSUE THREAD

**Issue by maxdadigital-thedecoder** [BEEmod/BEE2.4#1583] opened 2021-05-07 23:16 UTC
`An error occurred: 
Traceback (most recent call last):
  File "pyglet\media\codecs\wave.py", line 58, in __init__
  File "wave.py", line 509, in open
  File "wave.py", line 163, in __init__
  File "wave.py", line 130, in initfp
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wave.py", line 107, in decode
  File "pyglet\media\codecs\wave.py", line 60, in __init__
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id`
and also failed to execute script bee2_launch
Any way to fix this

**Comment by LautaroL20** [comment] 2021-05-08 00:22
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1520, the issue is even pinned. There is currently a fix for this, check out the comments on that issue.

**Closed by LautaroL20** 2021-05-08 00:22 UTC
Labels: Duplicate
