### ISSUE TITLE
Crashes on launch

### ISSUE THREAD

**Issue by Egorrich9001** [BEEmod/BEE2.4#1605] opened 2021-06-02 23:59 UTC
I installed this using the instruction: Unzip BEE2 anywhere (i did it in the same hard drive my steam games are in + created a folder) and unzip BEE tools inside. When i launch it it goes:
 "Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -2147024891] Access denied"
as i understood, this is an issue with items. I tried out both the current and the previous releases. They give the same error message.

**Comment by LautaroL20** [comment] 2021-06-03 00:00
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Closed** 2021-06-02 23:59 UTC
