### ISSUE TITLE
BTS corridor textures don't connect properly.

### ISSUE THREAD

**Issue by corrupt21** [BEEmod/BEE2.4#361] opened 2016-06-27 06:43 UTC
![image](https://cloud.githubusercontent.com/assets/17777059/16370849/2c7417e8-3c86-11e6-87f0-2088bc242574.png)

**Comment by LautaroL20** [comment] 2016-12-22 00:09
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/244

**Closed by LautaroL20** 2016-12-22 00:09 UTC
Labels: Bug, duplicate, Item´s section
