### ISSUE TITLE
Make genuine palette icons for those items who are re-using other icons

### ISSUE THREAD

**Issue by xGARDYx** [BEEmod/BEE2.4#822] opened 2018-01-27 11:58 UTC
Some of the custom items that Bee2 has like:Half Glass Door,Unstationary Platforms,Bumbleball,Covered Panel and Chamberlock,are copying icons of another item.About the Chamberlock may be like adding a fizzler in it's back.

**Comment by CaliMari** [comment] 2018-01-27 11:59
In-game they look OK

**Comment by CaliMari** [comment] 2018-01-27 12:02
Oh and Logic Gates when put not like all in the same item they show a purple-black "mysterious" texture in-game.

**Comment by CaliMari** [comment] 2018-01-27 19:37
@LautaroL20 
@TeamSpen210 
@ZombiePwner1

**Comment by peefTube** [comment] 2018-01-27 19:43
I've seen this bug before, iirc has something to do with faulty installation or something like that. Myself, I'd stick with pr27 (if this is related to pr28), at least until you can work it out with one of the developers.

**Comment by LautaroL20** [comment] 2018-01-27 23:08
We are totally open to contributions for this subject, if anyone wants to make good looking palette icons under a resolution of 256x256 and in .PNG format, then we can implement it for Beemod, its up to you, guys.

**Comment by LautaroL20** [comment] 2018-01-27 23:10
Fixed the title.

**Comment by xGARDYx** [comment] 2018-01-28 08:46
Yey my first good issue :D

**Comment by LautaroL20** [comment] 2018-01-30 23:47
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2470

**Closed by LautaroL20** 2018-01-30 23:47 UTC
Labels: Enhancement, Help Wanted

**Comment by xGARDYx** [comment] 2018-02-10 14:41
@LauraroL20

**Comment by xGARDYx** [comment] 2018-02-10 14:41
@LautaroL20

**Comment by xGARDYx** [comment] 2018-02-17 17:39
@LautaroL20

**Comment by LautaroL20** [comment] 2018-02-17 20:15
It is a bit late to re-open this issue since all the containing material is already here: https://github.com/BEEmod/BEE2-items/issues/2470

**Comment by xGARDYx** [comment] 2018-02-17 22:17
IK but i just told you

**Comment by xGARDYx** [comment] 2018-02-17 22:18
At least remove Dublicate
