### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by G3neralGrant** [BEEmod/BEE2.4#591] opened 2017-05-01 03:19 UTC
VBSP failed.

[INFO] vbsp.main(): BEE2.4.0pr24 VBSP hook initiallised.
[INFO] cond.core.import_conditions(): Imported all conditions modules!
[INFO] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[INFO] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[INFO] vbsp.main(): Clearing inject/ directory..
[INFO] vbsp.main(): PeTI map detected!
[INFO] vbsp.main(): Loading settings...
[WARNING] vbsp_options.load(): Extra config options: {'use_screenshot': '1', 'bottomless_pit': '0'}
[INFO] vbsp.load_settings(): Settings Loaded!
[INFO] vbsp.load_map(): Parsing Map...
[INFO] vbsp.load_map(): Reading Map...
[INFO] vbsp.load_map(): Loading complete!
[INFO] vbsp.get_map_info(): Forcing elevator spawn!
[INFO] vbsp.mod_entryexit(): Setting SP Entry to 6
[INFO] vbsp.mod_entryexit(): Setting SP Exit to 3
[INFO] vbsp.get_map_info(): Game Mode: SP
[INFO] vbsp.get_map_info(): Is Preview: False
[INFO] brushLoc.read_from_map(): Analysed map, filling air... (509 starting positions..)
[INFO] brushLoc.read_from_map(): Air filled!
[INFO] cond.core.check_all(): Checking Conditions...
[WARNING] instanceLocs._resolve(): "item_bee2_fizzler_out_relay" not a valid item!
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05B0D150>, solid=<srctools.vmf.Solid object at 0x05ACD730>, normal=Vec(0, 0, 1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x03CCE770>, <srctools.vmf.Solid object at 0x03CCE7B0>, <srctools.vmf.Solid object at 0x03CCE7D0>], detail=None, overlay=[], orig_ids={1: 57, 2: 52, 39: 53, 41: 51, 42: 50, 43: 49, 44: 58, 46: 56, 47: 55, 48: 54, 49: 64, 50: 63, 51: 62, 52: 61, 53: 60, 54: 59}), 'rem_brush': False, 'additional': [1, 2], 'transfer_overlays': True}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05B0D390>, solid=<srctools.vmf.Solid object at 0x05ACD750>, normal=Vec(-1, 0, 0), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x03CCE8B0>, <srctools.vmf.Solid object at 0x03CCE8D0>, <srctools.vmf.Solid object at 0x03CCE850>], detail=None, overlay=[], orig_ids={1: 73, 2: 68, 39: 69, 41: 67, 42: 66, 43: 65, 44: 74, 46: 72, 47: 71, 48: 70, 49: 80, 50: 79, 51: 78, 52: 77, 53: 76, 54: 75}), 'rem_brush': False, 'additional': [1, 2], 'transfer_overlays': True}
[INFO] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[INFO] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x05288C10>: [False, False, False, False], <srctools.vmf.Entity object at 0x05296FB0>: [False, False, False, False], <srctools.vmf.Entity object at 0x052A2250>: [False, False, False, False], <srctools.vmf.Entity object at 0x052A2090>: [False, False, False, False], <srctools.vmf.Entity object at 0x05288CD0>: [False, False, False, False], <srctools.vmf.Entity object at 0x052CF8F0>: [False, False, False, False], <srctools.vmf.Entity object at 0x05288B50>: [False, False, False, False], <srctools.vmf.Entity object at 0x0528FC90>: [False, False, False, False], <srctools.vmf.Entity object at 0x05288D90>: [False, False, False, False], <srctools.vmf.Entity object at 0x052CF9B0>: [False, False, False, False], <srctools.vmf.Entity object at 0x0528FBD0>: [False, False, False, False], <srctools.vmf.Entity object at 0x0528FD50>: [False, False, False, False]}
[INFO] cond.catwalks.res_make_catwalk(): Markers: {'catw90': <srctools.vmf.Entity object at 0x05296FB0>, 'catw51': <srctools.vmf.Entity object at 0x05288D90>, 'catw131': <srctools.vmf.Entity object at 0x052CF9B0>, 'catw68': <srctools.vmf.Entity object at 0x0528FBD0>, 'catw50': <srctools.vmf.Entity object at 0x05288CD0>, 'catw96': <srctools.vmf.Entity object at 0x052A2250>, 'catw69': <srctools.vmf.Entity object at 0x0528FC90>, 'catw130': <srctools.vmf.Entity object at 0x052CF8F0>, 'catw48': <srctools.vmf.Entity object at 0x05288B50>, 'catw70': <srctools.vmf.Entity object at 0x0528FD50>, 'catw49': <srctools.vmf.Entity object at 0x05288C10>, 'catw91': <srctools.vmf.Entity object at 0x052A2090>}
[INFO] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[INFO] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[INFO] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[INFO] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05819390>, solid=<srctools.vmf.Solid object at 0x058130F0>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x052EEC50>, <srctools.vmf.Solid object at 0x052EECD0>, <srctools.vmf.Solid object at 0x052EED30>, <srctools.vmf.Solid object at 0x052EED90>, <srctools.vmf.Solid object at 0x052EEBF0>, <srctools.vmf.Solid object at 0x052EEA30>, <srctools.vmf.Solid object at 0x052EEA70>, <srctools.vmf.Solid object at 0x052EEAF0>, <srctools.vmf.Solid object at 0x052EEB50>, <srctools.vmf.Solid object at 0x052EEBB0>, <srctools.vmf.Solid object at 0x052EEA10>], detail=None, overlay=[], orig_ids={1259: 1447, 1260: 1446, 1261: 1445, 1241: 1459, 1391: 1456, 1382: 1409, 1319: 1401, 1320: 1402, 1321: 1403, 1322: 1404, 1323: 1405, 1324: 1406, 1201: 1423, 1202: 1422, 1203: 1421, 1204: 1420, 1205: 1419, 1206: 1428, 1207: 1427, 1208: 1426, 1209: 1425, 1210: 1424, 1211: 1433, 1212: 1432, 1213: 1431, 1214: 1430, 1215: 1429, 1216: 1438, 1217: 1437, 1218: 1436, 1219: 1435, 1220: 1434, 1383: 1408, 1251: 1443, 1238: 1462, 1239: 1461, 1240: 1460, 1380: 1411, 1242: 1458, 1243: 1457, 1381: 1410, 1250: 1444, 1379: 1412, 1252: 1442, 1253: 1441, 1254: 1440, 1255: 1439, 1384: 1407, 1385: 1418, 1386: 1417, 1387: 1416, 1388: 1415, 1389: 1414, 1390: 1413, 1393: 1454, 1392: 1455, 1256: 1450, 1394: 1453, 1395: 1452, 1396: 1451, 1257: 1449, 1258: 1448}), 'rem_brush': True, 'additional': (), 'transfer_overlays': True}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05721ED0>, solid=<srctools.vmf.Solid object at 0x056F9530>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x052EE630>, <srctools.vmf.Solid object at 0x052EE670>, <srctools.vmf.Solid object at 0x052EE6F0>, <srctools.vmf.Solid object at 0x052EE750>, <srctools.vmf.Solid object at 0x052EE7B0>, <srctools.vmf.Solid object at 0x052EE610>, <srctools.vmf.Solid object at 0x052EEEB0>, <srctools.vmf.Solid object at 0x052EE450>, <srctools.vmf.Solid object at 0x052EE0D0>, <srctools.vmf.Solid object at 0x052EE510>, <srctools.vmf.Solid object at 0x052EE570>], detail=None, overlay=[], orig_ids={1259: 1509, 1260: 1508, 1261: 1507, 1241: 1521, 1391: 1518, 1382: 1471, 1319: 1463, 1320: 1464, 1321: 1465, 1322: 1466, 1323: 1467, 1324: 1468, 1201: 1485, 1202: 1484, 1203: 1483, 1204: 1482, 1205: 1481, 1206: 1490, 1207: 1489, 1208: 1488, 1209: 1487, 1210: 1486, 1211: 1495, 1212: 1494, 1213: 1493, 1214: 1492, 1215: 1491, 1216: 1500, 1217: 1499, 1218: 1498, 1219: 1497, 1220: 1496, 1383: 1470, 1251: 1505, 1238: 1524, 1239: 1523, 1240: 1522, 1380: 1473, 1242: 1520, 1243: 1519, 1381: 1472, 1250: 1506, 1379: 1474, 1252: 1504, 1253: 1503, 1254: 1502, 1255: 1501, 1384: 1469, 1385: 1480, 1386: 1479, 1387: 1478, 1388: 1477, 1389: 1476, 1390: 1475, 1393: 1516, 1392: 1517, 1256: 1512, 1394: 1515, 1395: 1514, 1396: 1513, 1257: 1511, 1258: 1510}), 'rem_brush': True, 'additional': (), 'transfer_overlays': True}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x058D2390>, solid=<srctools.vmf.Solid object at 0x0589D610>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x052EE430>, <srctools.vmf.Solid object at 0x052EE1B0>, <srctools.vmf.Solid object at 0x052EE5D0>, <srctools.vmf.Solid object at 0x052EE130>, <srctools.vmf.Solid object at 0x052EE490>, <srctools.vmf.Solid object at 0x052EEF10>, <srctools.vmf.Solid object at 0x052EEC10>, <srctools.vmf.Solid object at 0x052F2D30>, <srctools.vmf.Solid object at 0x052F2DB0>, <srctools.vmf.Solid object at 0x052DEF70>, <srctools.vmf.Solid object at 0x052DEEB0>], detail=None, overlay=[], orig_ids={1259: 1571, 1260: 1570, 1261: 1569, 1241: 1583, 1391: 1580, 1382: 1533, 1319: 1525, 1320: 1526, 1321: 1527, 1322: 1528, 1323: 1529, 1324: 1530, 1201: 1547, 1202: 1546, 1203: 1545, 1204: 1544, 1205: 1543, 1206: 1552, 1207: 1551, 1208: 1550, 1209: 1549, 1210: 1548, 1211: 1557, 1212: 1556, 1213: 1555, 1214: 1554, 1215: 1553, 1216: 1562, 1217: 1561, 1218: 1560, 1219: 1559, 1220: 1558, 1383: 1532, 1251: 1567, 1238: 1586, 1239: 1585, 1240: 1584, 1380: 1535, 1242: 1582, 1243: 1581, 1381: 1534, 1250: 1568, 1379: 1536, 1252: 1566, 1253: 1565, 1254: 1564, 1255: 1563, 1384: 1531, 1385: 1542, 1386: 1541, 1387: 1540, 1388: 1539, 1389: 1538, 1390: 1537, 1393: 1578, 1392: 1579, 1256: 1574, 1394: 1577, 1395: 1576, 1396: 1575, 1257: 1573, 1258: 1572}), 'rem_brush': True, 'additional': (), 'transfer_overlays': True}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05A72A50>, solid=<srctools.vmf.Solid object at 0x05A43610>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x052EEE30>, <srctools.vmf.Solid object at 0x052EE070>, <srctools.vmf.Solid object at 0x052EE9D0>, <srctools.vmf.Solid object at 0x052EE890>, <srctools.vmf.Solid object at 0x052EE970>, <srctools.vmf.Solid object at 0x052EE830>, <srctools.vmf.Solid object at 0x03CBEB50>, <srctools.vmf.Solid object at 0x03CBE9F0>, <srctools.vmf.Solid object at 0x03CBEA50>, <srctools.vmf.Solid object at 0x03CBEB30>, <srctools.vmf.Solid object at 0x03CBEA70>], detail=None, overlay=[], orig_ids={1259: 1633, 1260: 1632, 1261: 1631, 1241: 1645, 1391: 1642, 1382: 1595, 1319: 1587, 1320: 1588, 1321: 1589, 1322: 1590, 1323: 1591, 1324: 1592, 1201: 1609, 1202: 1608, 1203: 1607, 1204: 1606, 1205: 1605, 1206: 1614, 1207: 1613, 1208: 1612, 1209: 1611, 1210: 1610, 1211: 1619, 1212: 1618, 1213: 1617, 1214: 1616, 1215: 1615, 1216: 1624, 1217: 1623, 1218: 1622, 1219: 1621, 1220: 1620, 1383: 1594, 1251: 1629, 1238: 1648, 1239: 1647, 1240: 1646, 1380: 1597, 1242: 1644, 1243: 1643, 1381: 1596, 1250: 1630, 1379: 1598, 1252: 1628, 1253: 1627, 1254: 1626, 1255: 1625, 1384: 1593, 1385: 1604, 1386: 1603, 1387: 1602, 1388: 1601, 1389: 1600, 1390: 1599, 1393: 1640, 1392: 1641, 1256: 1636, 1394: 1639, 1395: 1638, 1396: 1637, 1257: 1635, 1258: 1634}), 'rem_brush': True, 'additional': (), 'transfer_overlays': True}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x05738ED0>, solid=<srctools.vmf.Solid object at 0x056F97F0>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x052DEFF0>, <srctools.vmf.Solid object at 0x052EE850>, <srctools.vmf.Solid object at 0x052EEDD0>, <srctools.vmf.Solid object at 0x052EEF70>, <srctools.vmf.Solid object at 0x03CCE710>, <srctools.vmf.Solid object at 0x03CCE050>, <srctools.vmf.Solid object at 0x03CCE2F0>, <srctools.vmf.Solid object at 0x03CBBBF0>, <srctools.vmf.Solid object at 0x03CBB330>, <srctools.vmf.Solid object at 0x03CBB210>, <srctools.vmf.Solid object at 0x03CBBBB0>], detail=None, overlay=[], orig_ids={1259: 1695, 1260: 1694, 1261: 1693, 1241: 1707, 1391: 1704, 1382: 1657, 1319: 1649, 1320: 1650, 1321: 1651, 1322: 1652, 1323: 1653, 1324: 1654, 1201: 1671, 1202: 1670, 1203: 1669, 1204: 1668, 1205: 1667, 1206: 1676, 1207: 1675, 1208: 1674, 1209: 1673, 1210: 1672, 1211: 1681, 1212: 1680, 1213: 1679, 1214: 1678, 1215: 1677, 1216: 1686, 1217: 1685, 1218: 1684, 1219: 1683, 1220: 1682, 1383: 1656, 1251: 1691, 1238: 1710, 1239: 1709, 1240: 1708, 1380: 1659, 1242: 1706, 1243: 1705, 1381: 1658, 1250: 1692, 1379: 1660, 1252: 1690, 1253: 1689, 1254: 1688, 1255: 1687, 1384: 1655, 1385: 1666, 1386: 1665, 1387: 1664, 1388: 1663, 1389: 1662, 1390: 1661, 1393: 1702, 1392: 1703, 1256: 1698, 1394: 1701, 1395: 1700, 1396: 1699, 1257: 1697, 1258: 1696}), 'rem_brush': True, 'additional': (), 'transfer_overlays': True}
[INFO] cond.core.steal_from_brush(): Steal: {'brush_group': solidGroup(face=<srctools.vmf.Side object at 0x0586DA50>, solid=<srctools.vmf.Solid object at 0x05813AF0>, normal=Vec(0, 0, -1), color=<MAT_TYPES.black: 0>), 'temp_data': Template(world=[<srctools.vmf.Solid object at 0x03CBB0D0>, <srctools.vmf.Solid object at 0x03CBBC50>, <srctools.vmf.Solid object at 0x03CBB1B0>, <srctools.vmf.Solid object at 0x03CBBC70>, <srctools.vmf.Solid object at 0x052CFAD0>, <srctools.vmf.Solid object at 0x052CFAB0>, <srctools.vmf.Solid object at 0x03CBEA10>, <srctools.vmf.Solid object at 0x03CB23B0>, <srctools.vmf.Solid object at 0x03CB2F90>, <srctools.vmf.Solid object at 0x03CB2470>, <srctools.vmf.Solid object at 0x03CB2450>], detail=None, overlay=[], orig_ids={1259: 1757, 1260: 1756, 1261: 1755, 1241: 1769, 1391: 1766, 1382: 1719, 1319: 1711, 1320: 1712, 1321: 1713, 1322: 1714, 1323: 1715, 1324: 1716, 1201: 1733, 1202: 1732, 1203: 1731, 1204: 1730, 1205: 1729, 1206: 1738, 1207: 1737, 1208: 1736, 1209: 1735, 1210: 1734, 1211: 1743, 1212: 1742, 1213: 1741, 1214: 1740, 1215: 1739, 1216: 1748, 1217: 1747, 1218: 1746, 1219: 1745, 1220: 1744, 1383: 1718, 1251: 1753, 1238: 1772, 1239: 1771, 1240: 1770, 1380: 1721, 1242: 1768, 1243: 1767, 1381: 1720, 1250: 1754, 1379: 1722, 1252: 1752, 1253: 1751, 1254: 1750, 1255: 1749, 1384: 1717, 1385: 1728, 1386: 1727, 1387: 1726, 1388: 1725, 1389: 1724, 1390: 1723, 1393: 1764, 1392: 1765, 1256: 1760, 1394: 1763, 1395: 1762, 1396: 1761, 1257: 1759, 1258: 1758}), 'rem_brush': True, 'additional': (), 'transfer_overlays': True}
[INFO] vbsp.set_elev_videos(): Elevator type: FORCE
[INFO] voiceLine.add_voice(): Adding Voice Lines!
[WARNING] BEE2_config.load(): Config "bee2\voice.cfg" not found! Using defaults...
[WARNING] BEE2_config.load(): Config "bee2\mid_voice.cfg" not found! Using defaults...
[INFO] voiceLine.add_voice(): Quote events: []
[INFO] voiceLine.add_voice(): No responses data..
[INFO] voiceLine.add_voice(): 0 Mid quotes
[INFO] voiceLine.add_voice(): Done!
[INFO] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[INFO] vbsp.set_player_portalgun(): Setting Portalgun:
[INFO] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[INFO] vbsp.set_player_portalgun(): Done!
[INFO] cond.core.check_all(): Map has attributes: ['cubesphere', 'laseremitter', 'catapult', 'cubereflection', 'glass', 'piston', 'cubedropperreflection', 'laser', 'panel', 'spawn_dual', 'cube', 'faithplate', 'bridge', 'hardlight', 'cubebutton', 'goo', 'cubedroppersphere', 'funnel', 'laserrelay', 'cubedropper', 'weightedbutton', 'floorbutton', 'lasercatcher', 'deadly', 'pistonplatform', 'buttonacceptsball', 'faith', 'buttonacceptscube', 'excursionfunnel']
[INFO] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=71729, misses=320, maxsize=256, currsize=256)
[INFO] cond.core.check_all(): Style Vars: {'unlockdefault': True, 'rexcubepelletfizzle': True, 'restartonexit': False, 'multiversecave': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'nomidvoices': False, 'bee_show_trigger': True, 'fixfizzlerbump': False, 'doorcameras': True}
[INFO] cond.core.check_all(): Global instances: {'instances/BEE2/clean/global_ents.vmf'}
[INFO] vbsp.add_extra_ents(): Adding Music...
[INFO] vbsp.add_extra_ents(): Adding Global PTI Ents
[INFO] vbsp.change_ents(): Editing Other Entities...
[INFO] vbsp.fixup_goo_sides(): Changing goo sides...
[INFO] vbsp.fixup_goo_sides(): Done!
[INFO] vbsp.change_brush(): Editing Brushes...
[INFO] vbsp.change_brush(): Make Bottomless Pit: False
[INFO] vbsp.change_overlays(): Editing Overlays...
[INFO] vbsp.change_trig(): Editing Triggers...
[INFO] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[INFO] vbsp.collapse_goo_trig(): Done!
[INFO] vbsp.change_func_brush(): Editing Brush Entities...
[INFO] vbsp.remove_static_ind_toggles(): Removing static indicator toggles...
[INFO] vbsp.remove_static_ind_toggles(): Done!
[INFO] vbsp.fix_worldspawn(): Editing WorldSpawn
[INFO] vbsp.make_packlist(): Making Pack list...
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/black_ceiling_metal.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/black_floor_metal.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/black_floor_metal.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/bullseye/bullseye_glow.vtf"
[INFO] vbsp.make_packlist(): "materials/BEE2/glass_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/grate_player_clip.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/models/props_overgrown/catwalk_rusty.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/signage_arrow_world.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/signage_catapult1_world.vmt"
[INFO] vbsp.make_packlist(): "materials/BEE2/no_paint/signage_catapult2_world.vmt"
[INFO] vbsp.make_packlist(): "models/BEE2/catwalk/factory_hanging_stairs_128_extended.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/faith_plate_toggle.mdl"
[INFO] vbsp.make_packlist(): "models/BEE2/props_ingame/square_light_64.mdl"
[INFO] vbsp.make_packlist(): "scripts/vscripts/BEE2/video_splitter_specific.nut"
[INFO] vbsp.make_packlist(): Packlist written!
[INFO] vbsp.save(): Saving New Map...
[INFO] vbsp.save(): Complete!
[INFO] vbsp.run_vbsp(): Calling original VBSP...
[INFO] vbsp.run_vbsp(): Arguments: "C:\Program Files (x86)\Steam\steamapps\common\Portal 2\bin\vbsp_original.exe" -game "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/" "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[ERROR] <Valve>.run_vbsp(): Valve Software - vbsp.exe (Aug 26 2015)
 | 4 threads
 | materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
 | Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
 | ConVarRef gpu_level doesn't point to an existing ConVar
 | Could not open instance file instances/BEE2/logic/bee/trigger_multiple.vmf
 | 
 |_

[ERROR] vbsp.run_vbsp(): VBSP failed! (1)

**Comment by Luke18033** [comment] 2017-05-01 03:30
Duplicate of BEEmod/BEE2-items#1550.

**Closed by Luke18033** 2017-05-01 03:30 UTC
