### ISSUE TITLE
Annoying Signage bug

### ISSUE THREAD

**Issue by Deitz578** [BEEmod/BEE2.4#1953] opened 2023-05-27 18:15 UTC
### BEE2 Application Version

4.43.0

### BEE2 Package Version

4.43.0

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

Signage doesn't export sometimes randomly

### Expected behavior

I expected bee mod to export the signage i set

### Steps to reproduce

Step 1:Change current signage
Step 2: Export to game

### Logs and Reports

```shell
[D] BEE2.start_main(): Starting Trio loop.
[D] BEE2.app_main(): Opening nursery...
[D] BEE2.init_app(): Starting loading screen...
[I] gameMan.refresh_cache(): Deleting: c:\program files (x86)\steam\steamapps\common\portal 2\bee2\materials\bee2\models\props_map_editor\signage\signage.vtf
[I] BEE2_config.save(): Saving changes in config "C:\Users\My pc\AppData\Roaming\BEEMOD2\config\games.cfg"!
[I] gameMan.export(): Optimizing editor models...
[I] gameMan.export(): Writing bee2/materials/BEE2/models/props_map_editor/signage/signage.vtf...
[I] BEE2_config.save(): Saving changes in config "C:\Users\My pc\AppData\Roaming\BEEMOD2\config\games.cfg"!
[I] paletteLoader.save(): Saving "<Last Export>"!
```

### Additional information

This is a reoccurring bug that needs to be fixed as soon as possible as it happened 3 times in a row for me and then happened to my friend

**Comment by THECOOLKID-boop** [comment] 2023-12-17 18:38
This still needs to be fixed

**Comment by TeamSpen210** [comment] 2023-12-17 19:28
What exactly is happening? What part "isn't exporting"? The legend, the actual signs ingame? How are you changing them, by swapping palette or by opening the menu? Do the ones you changed to appear when reopening the application?

**Comment by THECOOLKID-boop** [comment] 2023-12-18 07:06
Upon putting custom signage and exporting to game new signage doesnt export ends up being the default signageSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Spencer Brown ***@***.***> Date: 12/17/23  1:29 PM  (GMT-06:00) To: "BEEmod/BEE2.4" ***@***.***> Cc: THEOCULUSDRAGON ***@***.***>, Author ***@***.***> Subject: Re: [BEEmod/BEE2.4] Annoying Signage bug (Issue #1953) 
What exactly is happening? What part "isn't exporting"? The legend, the actual signs ingame? How are you changing them, by swapping palette or by opening the menu? Do the ones you changed to appear when reopening the application?

**Comment by vrad-exe** [comment] 2024-05-12 04:44
Can't reproduce, closing due to lack of info

**Closed by vrad-exe** 2024-05-12 04:44 UTC
Labels: Bug, More Info Needed
