### ISSUE TITLE
Cant open BEE2.exe

### ISSUE THREAD

**Issue by hay-dude007** [BEEmod/BEE2.4#1758] opened 2021-11-07 12:18 UTC
I dunno why but it keeps "crashing"! 
![Screenshot (8)](https://user-images.githubusercontent.com/92254330/140644580-c503fb80-d4d4-4f88-a80e-71fc151f2a8e.png)
:(

**Comment by FrozenDragon0** [comment] 2021-11-07 12:27
Duplicate of: https://github.com/BEEmod/BEE2.4/issues/1624 The issue is even pinned.

**Closed by FrozenDragon0** 2021-11-07 12:27 UTC
Labels: Duplicate
