### ISSUE TITLE
Logic gates cause compiler errors

### ISSUE THREAD

**Issue by mjcox244** [BEEmod/BEE2.4#1441] opened 2020-12-27 13:27 UTC
when i use logic gates (the rainbow icon and strip icon) even if i have them hookded up conectly (2 inputs 1 output) it causes a compiler error on the building geomitry part

Im useing stock portal 2 with the compressed pre-set with logic gates added

(the game im patching is stock portal 2)

**Comment by mjcox244** [comment] 2020-12-27 13:35
Visual gates work

**Comment by LautaroL20** [comment] 2020-12-27 13:45
You have posted in the wrong section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

The section where you have posted is for things related to the Bee´s user interface, only. Also, this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3359

**Closed by LautaroL20** 2020-12-27 13:45 UTC
Labels: Done, Duplicate
