### ISSUE TITLE
exit co-op not open with all ✅

### ISSUE THREAD

**Issue by MischaGer** [BEEmod/BEE2.4#1241] opened 2020-01-20 18:05 UTC
have bind my exit with
1x cube button
1x Ball button
2x laser catcher
and 3 x laser relay

**Comment by LautaroL20** [comment] 2020-01-20 18:15
You are posting in the worng section. Anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post things related to the Bee´s user interface, only.
Also, this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/3205

**Closed by LautaroL20** 2020-01-20 18:15 UTC
Labels: Duplicate, Invalid
