### ISSUE TITLE
Error Building Puzzle

### ISSUE THREAD

**Issue by thatboy6000** [BEEmod/BEE2.4#1233] opened 2020-01-07 17:02 UTC
Whenever I make a puzzle using bee2 items the puzzle won't build. But when I make one without bee2 items it works! any ideas on how to fix this?

Error Log Thing:
VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 3
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (19 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 0/0 locations
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_B" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_CORNER_C" does not exist!
[W] packing.pack_list(): Packlist "VACTUBE_128_STRAIGHT_GLASS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_DESTROYED_64" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: RAND
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
  | 	{
 | 	"ID" "ENTRY_GEN_FUTURE_STARTER"
 | 	"Choreo" "npc/announcer/prehub17.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "EXIT_GEN_RESTART"
 | 	"Choreo" "npc/announcer/mp_hub_return06.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 0/4 quotes..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] vbsp.anti_fizz_bump(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['collapsedexitstairs', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=5451, misses=381, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': False, 'multiversecave': True, 'fixfizzlerbump': True, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/global_ents.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 0 <- Counter()
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 4 threads
[I] <valve>.vbsp(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/over/items/tSpen/coop_checkpoint_sep.vmf
[I] <valve>.vbsp():

**Comment by Flash4433** [comment] 2020-01-07 19:05
I think your message cut the log a little bit at the end... Anyways, it might be the coop checkpoint.

**Comment by Luke18033** [comment] 2020-01-07 19:14
This would be a duplicate of BEEmod/BEE2-items#2263

**Closed by Luke18033** 2020-01-07 19:14 UTC

**Comment by thatboy6000** [comment] 2020-01-07 19:41
It's not just the coop door thing it's any bee2 item

**Comment by Luke18033** [comment] 2020-01-07 19:48
Can you remove the checkpoint, and post one of the other error logs?

**Comment by thatboy6000** [comment] 2020-01-07 19:56
The errors only happen when I used bee2 items so removing the check point won't give me an error

**Comment by Luke18033** [comment] 2020-01-07 20:00
...then it's caused by the checkpoint, and this is a duplicate of BEEmod/BEE2-items#2263. The BEE2 modifies lots of default items, not to mention that the Overgrown style is completely custom. If everything was missing, it would be failing no matter what.
