### ISSUE TITLE
BEEmod crash while exporting: "NotImplementedError: Saving DXT1 not implemented!"

### ISSUE THREAD

**Issue by IDy8I** [BEEmod/BEE2.4#1660] opened 2021-08-01 23:05 UTC
**BEE2 version:**
4.40.2 - 32 and 64 Bit versions

**Description of the bug:**
BEEmod can sometimes crash while exporting items with the following error message: "NotImplementedError: Saving DXT1 not implemented!"

**Steps to reproduce:**
1.- Export Items with "original clean" style for the first time
2.-Wait to load and the error appears

**Additional information:**
![SCREENSHOT](https://user-images.githubusercontent.com/78465012/127787797-2625f411-57f8-40e5-bfea-b2be0f728310.png)

**Comment by IDy8I** [comment] 2021-08-01 23:13
sorry i put enter while im writing

**Comment by LautaroL20** [comment] 2021-08-01 23:50
> IDy8I said: "sorry i put enter while im writing"

No problem.

**Comment by IDy8I** [comment] 2021-08-06 19:15
I have more info so I update the "steps to reproduce"

**Comment by TwoKrazy** [comment] 2021-08-17 23:07
The same thing happens with the "Clean" style

**Comment by TwoKrazy** [comment] 2021-08-17 23:12
Also I think the problem is a typo in the code, it says DXT1, rather than DXT_11_. I haven't looked at the source code for any of the versions so I can't confirm this.

**Comment by ThaBluNate** [comment] 2021-08-19 14:24
this happens with every style for me even when i use default portal 2 stuff
it just happens every time exporting

**Comment by TeamSpen210** [comment] 2021-08-19 20:44
Are you using the 32-bit or 64-bit application?

**Comment by IDy8I** [comment] 2021-08-20 03:37
64-bit App

**Comment by TwoKrazy** [comment] 2021-08-20 19:01
64-bit

**Comment by TwoKrazy** [comment] 2021-08-20 19:07
I just tested it. The same error occurs with the 32-bit version

**Comment by MoonstreamJustNotInSpace** [comment] 2021-08-29 23:38
What's the latest version that still works?

**Comment by FrozenDragon0** [comment] 2021-08-29 23:40
@MoonstreamJustNotInSpace V4.36

**Comment by MoonstreamJustNotInSpace** [comment] 2021-08-29 23:41
Thanks so much!

**Comment by ThaBluNate** [comment] 2021-09-01 06:47
this is still an issue in the src build

**Comment by Luke18033** [comment] 2021-09-01 06:50
Does it happen consistently when using a certain style and/or item?

**Comment by TeamSpen210** [comment] 2021-09-01 07:08
It won’t, this always executes to generate the colouriser and signage editor textures. I’ve got a workaround, but I do want to know why it’s not loading since the app would be slower.

**Comment by slambo312** [comment] 2021-10-01 10:45
Idea: For a temporary fix, I got some ideas i got randomly

- Disabling the colouriser's customizability, and make it just the default colours (Toggleable)
- Disabling the entire signage part of signs (Toggleable)
I recommend making the signage toggle not a temporary thing though, It might be useful in levels where the creator of the test doesn't want you to know what you're getting into. Or, y'know, just because nobody will go around looking at signs until Portal 2 Community Edition releases something (That reminds me, I've been constantly thinking of you guys and the Community Edition team working together, improving each other's prefabs and stuff).

**Comment by slambo312** [comment] 2021-10-01 10:48
Idk much about coding, so it might not be possible.

**Comment by Luke18033** [comment] 2021-11-03 18:20
Did you manage to properly fix this?

**Comment by TeamSpen210** [comment] 2021-11-03 20:30
It should hopefully be fixed by me rearranging how the C extensions are compiled.

**Closed** 2021-11-16 08:06 UTC
Labels: Bug, App Crash, Done
