### ISSUE TITLE
Workaround solution for the BEEmod crash: "FileNotFoundError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by ThaBluNate** [BEEmod/BEE2.4#1645] opened 2021-07-22 06:14 UTC
**BEE2 version: 4.40.2**

**The Error:**

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Epicg\\AppData\\Roaming\\BEEMOD2\\config\\tmp********'

**Steps to reproduce:**

1. Delete %AppData%/BEEMOD2
2. Open a fresh copy of BEEmod 2

**Workaround**

1. Press WINDOWS+R
2. Enter %AppData%\BEEMOD2
3. Press Enter
4. Make a new folder and name it "Config"

BEEmod Should now work correctly!

_Edit: This issue still currently persists as of **8/18/2021** on a new source compile_

**Comment by Epicgamernate** [comment] 2021-07-22 06:22
This is an error detailed to help people workaround an error on the latest version (4.40.2)
It is not currently updated to fix this, however there was a commit to fix this on an issue 8 days ago
If you have any questions post them, I'll probably respond
Thanks!

**Comment by Luke18033** [comment] 2021-08-29 06:57
Duplicate of #1624, I moved the workaround there.

**Closed by Luke18033** 2021-08-29 06:57 UTC
Labels: App Crash, Contribution
