### ISSUE TITLE
Failed to execute scipt BEE2_launch

### ISSUE THREAD

**Issue by EvonShift** [BEEmod/BEE2.4#1540] opened 2021-03-14 12:51 UTC
**BEE2 version:** 4.39.2

**Description of the bug:**
App crushes after launch and shows error: "Failed to execute script BEE2_launch"
Log:
Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] Тип байтового потока данного URL не поддерживается

(Type of byte thread of the following URL is not supported)

**Additional information:**
I am using Windows 10 x64

**Comment by TuAmigoFiel** [comment] 2021-03-18 14:52
I have the same problem here.

**Comment by LautaroL20** [comment] 2021-03-21 09:03
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Closed by LautaroL20** 2021-03-21 09:03 UTC
Labels: App Crash, Duplicate

**Comment by FYvw** [comment] 2021-04-06 12:43
It seems to be a problem with the sounds, in the beginning it works, but if a specific sound is played (it happened to me when clicking on the "more info" button on an item), it crashes and doesn't open anymore. Reinstalling BEE Mod and disabling sounds in the settings did work for me.
