### ISSUE TITLE
Exit door doesn't take you to the orange and blue deconstruction tubes. (BTS Theme)

### ISSUE THREAD

**Issue by PKYXYZ** [BEEmod/BEE2.4#710] opened 2017-08-10 04:51 UTC
Hey! I'm using the BTS theme (my favorite) and it seems that on this theme the exit door is open by default instead of waiting for both players to stand in front of the door. It also lead to another door that will not open, thus leaving levels unbeatable.

So upon opening Portal 2 to take screenshots of this issue, It seems the door is located on the floor?
![preview0001](https://user-images.githubusercontent.com/16485135/29154908-e4806096-7d4c-11e7-8c30-8bc722bbd139.jpg)
![preview0002](https://user-images.githubusercontent.com/16485135/29154909-e48190ec-7d4c-11e7-820b-cacd4d18cca7.jpg)
![preview0006](https://user-images.githubusercontent.com/16485135/29154910-e483024c-7d4c-11e7-94e2-175878109814.jpg)

**Comment by ZombiePwner1** [comment] 2017-08-10 07:16
BTS has alot of issues with coop mode right we do not recommend you use it until the coop issues are fixed. Also duplicate of another issue.

**Closed by ZombiePwner1** 2017-08-10 07:16 UTC
Labels: Duplicate
