### ISSUE TITLE
Crash when trying to launch BEE2 just after downloaded

### ISSUE THREAD

**Issue by CsakiTheOne** [BEEmod/BEE2.4#1696] opened 2021-09-04 12:05 UTC
Labels until not added: [App Crash] and probably [Windows]

I get this error when trying to launch BEE2.exe. No matter if it's the 32bit or 64bit version. Also there is no `C:\\Users\\jocka\\AppData\\Roaming\\BEEMOD2\\config` folder whatsoever. I have never used BEEmod on this computer before. I don't think it's important, but I use Windows 11 22449.1000. And yes, this is the latest version, I just downloaded it today.
```
Traceback (most recent call last):
  File "BEE2_launch.pyw", line 50, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\BEE2.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\gameMan.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\optionWindow.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\contextWin.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\itemconfig.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\UI.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
  File "app\CompilerPane.py", line 78, in <module>
  File "BEE2_config.py", line 180, in set_defaults
  File "BEE2_config.py", line 170, in save_check
  File "BEE2_config.py", line 163, in save
  File "contextlib.py", line 113, in __enter__
  File "atomicwrites\__init__.py", line 166, in _open
  File "atomicwrites\__init__.py", line 183, in get_fileobject
  File "tempfile.py", line 331, in mkstemp
  File "tempfile.py", line 250, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jocka\\AppData\\Roaming\\BEEMOD2\\config\\tmp_33pyst7'
```

**Comment by LautaroL20** [comment] 2021-09-04 12:16
This is a duplicate of: #1624, the issue is even pinned, you need to pay more attention before opening an issue.

**Closed by LautaroL20** 2021-09-04 12:16 UTC
Labels: Duplicate, App Crash

**Comment by LautaroL20** [comment] 2021-09-04 13:54
This will be fixed in next release though.

**Comment by CsakiTheOne** [comment] 2021-09-04 16:40
Sorry for not paying enough attention, I didn't find this issue first.
Thank you for your answer and keep up the good work!



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality9&>
09/04/21,
06:38:28 PM

Lautaro ***@***.***> ezt írta (időpont: 2021. szept. 4., Szo,
15:55):

**Comment by LautaroL20** [comment] 2021-09-04 16:53
No problem!
