### ISSUE TITLE
Building Error when Trying to Publish Map

### ISSUE THREAD

**Issue by beewyka819** [BEEmod/BEE2.4#671] opened 2017-06-22 16:35 UTC
Whenever I try to publish my map to the workshop (works fine if I compile via rebuild), I get an error and this error in the console:
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF E:/Steam/steamapps/common/Portal 2/sdk_content\maps/1498142955.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (25,25,24)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 286 (ms)
[PORTAL2 PUZZLEMAKER]  Compilation time (after VBSP): 34546 (ms)

VVIS failed.

Valve Software - vvis.exe (Aug 26 2015)
4 threads
reading e:\steam\steamapps\common\portal 2\sdk_content\maps\1498142955.bsp
reading e:\steam\steamapps\common\portal 2\sdk_content\maps\1498142955.prt
LoadPortals: couldn't read e:\steam\steamapps\common\portal 2\sdk_content\maps\1498142955.prt

**Comment by beewyka819** [comment] 2017-06-22 16:36
Here is an image of the map: 
![image](https://user-images.githubusercontent.com/8059789/27445340-60d1fd8e-5747-11e7-9a74-d5d99699b670.png)

**Comment by Luke18033** [comment] 2017-06-23 14:58
There's a leak in your map somewhere.

**Comment by beewyka819** [comment] 2017-06-23 15:58
That's what I was thinking when I saw another post like this. Is there a way to locate it?

**Comment by beewyka819** [comment] 2017-06-23 15:59
Also ignore that tiny empty room floating in the middle of nowhere, I removed that.

**Comment by beewyka819** [comment] 2017-06-23 16:20
The pointfile is showing me that it's right in front of the entrance. strange. It's not the coop points, I tried removing them with no luck

**Comment by beewyka819** [comment] 2017-06-23 16:41
Figured it out, apparently the coop entrance cant go at the map limits

**Comment by beewyka819** [comment] 2017-06-23 16:42
Woah hold up, when I moved the entrance and exit and put them back it suddenly works. Im really confused

**Comment by Luke18033** [comment] 2017-06-23 16:45
Illuminati confirmed.

**Comment by beewyka819** [comment] 2017-06-23 16:46
Valve make a more reliable engine

**Comment by LautaroL20** [comment] 2017-10-28 16:15
This clearly seems to be an issue in the game caused by using old resources from past Beemod releases, to solving this annoyance, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Comment by LautaroL20** [comment] 2017-10-28 16:16
@beewyka819 - Get Pre-Release 27 (Packages & Application), since this is most likely fixed now, however once you installed the latest version, you will have to do the following:

1. Open Beemod and click on: `File ----> Uninstall From Selected Game ----> "Are you sure you want to delete "PORTAL 2"? ----> YES`.

2. Wait 1 minute while beemod removes their resources from Portal 2.

3. Verify the Game Cache Files. 

4. Make sure to have downloaded and unzipped the latest packages & application version of beemod, and both must have to be from the same pre-release version, otherwise bugs may occur. Also, if you are running beemod on Linux or Mac Os X, issues can occur. Beemod currently works well only on Windows 7, 8 and 10.

5. Click on: `File ----> Options ----> Development`, and now uncheck the option: `Preserve Game Directories`.

6. Now choose your favorite Items & Style, and export your palette to the game.

7. Happy mapmaking!

**Closed by LautaroL20** 2017-10-28 16:15 UTC
Labels: Invalid
