### ISSUE TITLE
No models at the door in the editor!

### ISSUE THREAD

**Issue by Frostygames0** [BEEmod/BEE2.4#914] opened 2018-05-09 10:37 UTC
I have two problems with door models.
1. In the style of 1950-1980 I have an invisible entrance door. She does not have a model.
2. When I put the door (not the gateway) it appears as an error.
There is no model either.
------
I do not know, but I recently broke bee mod 2 and I reinstalled it and portal 2. But not to version 28, but to version 29 and then there was an error. How can I fix it? Used Google Translate

**Comment by LautaroL20** [comment] 2018-05-09 13:06
You are always talking in the case of Editor Models, or in point 2 you reffer to the In-game models?
Point 1 is fixed for next release.

**Comment by King0191** [comment] 2018-05-09 15:48
If you place a normal Old Aperture Door, not a chamberlock, a Normal door. It will have an error model for the Puzzlemaker, That is what he means Lautaro

**Comment by LautaroL20** [comment] 2018-05-09 19:36
Then Point 1 and 2 are identical, which means that this is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2626

**Closed by LautaroL20** 2018-05-09 19:36 UTC
Labels: Duplicate

**Comment by LautaroL20** [comment] 2018-05-09 19:42
And also, this is the wrong repository to report something related to items, for items: https://github.com/BEEmod/BEE2-items/issues
