### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by Fazbear189** [BEEmod/BEE2.4#769] opened 2017-10-31 21:04 UTC
can you add clear water that you can swim in? with things that drop water into places to fill them up with water?

**Comment by HugoBDesigner** [comment] 2017-10-31 21:15
Duplicate of #46 item 16

**Comment by Luke18033** [comment] 2017-10-31 21:26
Don't forget to close the issue.

**Closed by Luke18033** 2017-10-31 21:26 UTC
Labels: Duplicate

**Comment by HugoBDesigner** [comment] 2017-10-31 21:28
I waited for some confirmation before closing, just to make sure I could. So thanks 👍
