### ISSUE TITLE
Error opening "BEE2"

### ISSUE THREAD

**Issue by MoreCactus** [BEEmod/BEE2.4#1075] opened 2019-02-10 00:05 UTC
![screenshot_159](https://user-images.githubusercontent.com/47488232/52527844-50f72900-2cc7-11e9-89fc-79024a410dfa.png)

I tried to go in every but I did not find what caused the mistake

**Comment by LautaroL20** [comment] 2019-02-10 03:29
This was fixed since a time ago already, and it is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1055

**Closed by LautaroL20** 2019-02-10 03:29 UTC
Labels: Duplicate, Fixed

**Comment by MoreCactus** [comment] 2019-02-10 07:57
Where is this duplicate?
And thanks for the attention! ^-^
