### ISSUE TITLE
PRL31 BUG(paint fizzler doesn't work)

### ISSUE THREAD

**Issue by quantumfield7** [BEEmod/BEE2.4#1023] opened 2018-11-12 11:26 UTC
If gel(through funnel) pass the paint fizzler, It should be blocked. But It just passed

**Comment by LautaroL20** [comment] 2018-11-13 12:58
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.

**Comment by TeamSpen210** [comment] 2018-11-18 06:53
@Lautaro, Github has added a new feature that enables transferring issues. I think only I can do it though.

**Comment by TeamSpen210** [comment] 2018-11-18 06:54
It's a duplicate of BEEmod/BEE2-items#2860 though.

**Closed** 2018-11-18 06:54 UTC
Labels: Packages Issue
