### ISSUE TITLE
Music preview does not appear.

### ISSUE THREAD

**Issue by zooz8882** [BEEmod/BEE2.4#1622] opened 2021-07-02 22:11 UTC
I was using the newest version of Beemod, 4.40, when I encountered this bug.

Upon going to the music selection page, I could not preview the music in the way it was possible in older versions of Beemod.  The play button that allows you to hear the music wasn’t there.  After troubleshooting with some people in the discord, I was advised to install all runtime installers.  Installing them did not solve the problem.  I then restarted my computer.  This did not fix it either.

I expected to be able to preview the music for a chamber with the small play button next to the title of the track.

I’m not sure if it's possible to reproduce this bug.  For most people, it seems to work fine.  Spen told me it should be fixed and I haven’t seen anyone else with the problem.

A screenshot of the music selection screen showing how the play button does not appear: 

![Screenshot 2021-07-02 181000](https://user-images.githubusercontent.com/52897089/124332945-cdbd2300-db60-11eb-9738-8da668757611.png)

**Comment by LautaroL20** [comment] 2021-07-03 16:56
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1351

**Closed by LautaroL20** 2021-07-03 16:56 UTC
Labels: Bug, Duplicate
