### ISSUE TITLE
Lasefield causes failure to compile!

### ISSUE THREAD

**Issue by BETTEREXTENEDEDITORMOD** [BEEmod/BEE2.4#1014] opened 2018-11-03 07:54 UTC
Here's the log only happens with laserfields
VBSP failed.

[I] vbsp.main(): BEE2.4.0pr30 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'glass_scale': '0.15', 'voice_pack': 'BEE2_ANNOUNCER_APOC'}
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_low" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[W] instanceLocs.get_subitems(): Invalid custom instance name - "piston_grate_high" for <item_rex_pellet_destroyer> (Valid: {'head': 'instances/bee2/clean/items/rex/pellet_dest/head.vmf', 'common': 'instances/bee2/clean/items/rex/pellet_dest/common.vmf', 'piston_bottom_0': 'instances/bee2/clean/items/rex/pellet_dest/pist_0.vmf', 'piston_bottom_1': 'instances/bee2/clean/items/rex/pellet_dest/pist_1.vmf', 'piston_bottom_2': 'instances/bee2/clean/items/rex/pellet_dest/pist_2.vmf', 'piston_bottom_3': 'instances/bee2/clean/items/rex/pellet_dest/pist_3.vmf', 'piston_static_0': 'instances/bee2/clean/items/rex/pellet_dest/static_0.vmf', 'piston_static_1': 'instances/bee2/clean/items/rex/pellet_dest/static_1.vmf', 'piston_static_2': 'instances/bee2/clean/items/rex/pellet_dest/static_2.vmf', 'piston_static_3': 'instances/bee2/clean/items/rex/pellet_dest/static_3.vmf', 'piston_static_4': 'instances/bee2/clean/items/rex/pellet_dest/static_4.vmf', 'piston_logic_0': 'instances/bee2/clean/items/rex/pellet_dest/logic_0.vmf', 'piston_logic_1': 'instances/bee2/clean/items/rex/pellet_dest/logic_1.vmf', 'piston_logic_2': 'instances/bee2/clean/items/rex/pellet_dest/logic_2.vmf', 'piston_logic_3': 'instances/bee2/clean/items/rex/pellet_dest/logic_3.vmf'})
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 2
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (231 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.add_item_inputs(): LOGIC counter: lg66
[I] connections.add_item_inputs(): LOGIC counter: lg116
[I] connections.add_item_inputs(): LOGIC counter: lg75
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] brushes.res_import_template(): IDS: {'1'}
[I] brushes.res_import_template(): IDS: {'1'}
[I] brushes.res_import_template(): IDS: {'24'}
[I] brushes.res_import_template(): IDS: {'24'}
[I] brushes.res_import_template(): IDS: {'24'}
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1337 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1554 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] template.retexture_template(): Realign face in template "bee2_static_stairs_clean_extended" (1649 in final) is not on grid!
[W] template.get_scaling_template(): Template "BEE2_STATIC_STAIRS_STATIC_BEAMS_TEMP" used as scaling template, but is not really one!
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "ENTRY": 3/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "ENTRY_GEN_FUTURE_STARTER"
 | 	"Choreo" "npc/announcer/prehub17.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): "EXIT": 2/5 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line_SP"
 | 	{
 | 	"ID" "EXIT_GEN_INTERVIEW"
 | 	"Choreo" "npc/announcer/prehub20.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "??" is disabled..
[I] voiceLine.find_group_quotes(): Line "Passed Through a Grid" is disabled..
[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 3/4 quotes..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.anti_fizz_bump(): Adding Portal Bumpers to fizzlers...
[I] vbsp.anti_fizz_bump(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'laserfield', 'laser', 'deadly', 'fizzler', 'glass', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'cubefranken', 'cubedropperfranken', 'funnel', 'excursionfunnel', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'cubebutton', 'gel', 'geldropper', 'portalgel', 'whitegel', 'pedestalbutton', 'lasercatcher', 'pistonplatform', 'piston', 'panel', 'laseremitter', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=37145, misses=371, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'doorcameras': True, 'restartonexit': False, 'multiversecave': False, 'fixfizzlerbump': True, 'nomidvoices': True, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: set()
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 352.0 <- Counter({352.0: 7})
[I] vbsp.clump_walls(): Clumping: 560 clumps (+ 0 special)
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/portal2/', 'C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <Valve>.run_compiler(): Valve Software - vbsp.exe (Oct 26 2018)
[I] <Valve>.run_compiler(): 12 threads
[I] <Valve>.run_compiler(): materialPath: C:\Program Files (x86)\Steam\steamapps\common\Portal 2\portal2\materials
[I] <Valve>.run_compiler(): Loading C:/Program Files (x86)/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <Valve>.run_compiler(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <Valve>.run_compiler(): Could not open instance file instances/bee2/clean/items/fizzler/barrier_hazard_base.vmf
[I] <Valve>.run_compiler(): 
[I] BEE2_config.save(): Saving changes in config "C:\Users\Admin\Desktop\Bee2\config/compile.cfg"!

**Comment by LautaroL20** [comment] 2018-11-04 01:50
Try removing the laserfield item from your map and it will compile fine. This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/2846

**Comment by LautaroL20** [comment] 2018-11-04 01:51
You are posting in the worng section, anything related to items & styles must be posted on the item´s page, here: https://github.com/BEEmod/BEE2-items/issues

This section is for post anything related to the Bee´s user interface, only.

**Closed by LautaroL20** 2018-11-04 01:50 UTC
Labels: Compile Error, Duplicate
