### ISSUE TITLE
Can you please add a setup wizard like with Bee 1? The instructions aren't clear, so can you add an option to have the setup automated?

### ISSUE THREAD

**Issue by SirAxolot** [BEEmod/BEE2.4#978] opened 2018-08-25 17:07 UTC
Can you please add a setup wizard like with Bee 1?
I'm 12 years old, and the instructions aren't clear, so can you add an option to have the setup automated?

**Comment by LautaroL20** [comment] 2018-08-26 12:31
Yes, it would be good.

**Comment by Luke18033** [comment] 2018-08-26 14:48
Duplicate of #77.

**Closed by Luke18033** 2018-08-26 14:48 UTC
Labels: Enhancement
