### ISSUE TITLE
Error in BTS style, help me please

### ISSUE THREAD

**Issue by sasha155** [BEEmod/BEE2.4#1533] opened 2021-03-05 17:59 UTC
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.1 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] texturing.load_config(): overlays: Unknown texture names faithfling, faithland
[W] options.load(): Extra config options: {'glass_scale': '0.05'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] antlines.parse_antlines(): Parsing antlines...
[I] antlines.parse_antlines(): Done! (0 antlines)
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 2
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (11 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1897, in main
  File "precomp\texturing.py", line 706, in setup
  File "srctools\vmt.py", line 120, in parse
  File "srctools\_tokenizer.pyx", line 151, in srctools._tokenizer.Tokenizer.__init__
TypeError: Expected unicode, got Special
[11776] Failed to execute script compiler_launch

**Comment by H2ofiremaster** [comment] 2021-03-05 18:05
Duplicate of #1511

**Comment by LautaroL20** [comment] 2021-03-05 18:24
Indeed.

**Closed by LautaroL20** 2021-03-05 18:24 UTC
Labels: Bug, Compile Error, Duplicate
