### ISSUE TITLE
Build error for no reasons

### ISSUE THREAD

**Issue by Badpoolinator** [BEEmod/BEE2.4#1578] opened 2021-05-02 10:14 UTC
I am on BTS style and even with the default test chamber (empty 4x6 room) it just gives me an error. Any fixes? 

error.p2c: https://drive.google.com/file/d/1BQYcql5QZetdu3YjZCHJYLUgsdP8gdmE/view?usp=sharing

**Comment by HeimlichLaboratories** [comment] 2021-05-02 10:21
I think this was already reported? #3739 in the items section

**Comment by HeimlichLaboratories** [comment] 2021-05-02 10:21
https://github.com/BEEmod/BEE2-items/issues/3739

**Comment by FrozenDragon0** [comment] 2021-05-02 10:24
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3720 Also you have posted in the wrong section.

**Closed by FrozenDragon0** 2021-05-02 10:24 UTC
Labels: Bug, Compile Error, Duplicate
