### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Onism02** [BEEmod/BEE2.4#1516] opened 2021-02-28 00:27 UTC
VBSP failed.

[I] vbsp.main(): BEE2 v4.39.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "E:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "E:/SteamLibrary/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] options.load(): Extra config options: {'remove_pedestal_plat': '1', 'music_location_sp': '-2824 2040 -768', 'voice_pack': 'BEE2_CAVE_60s'}
[E] (unknown file).(unknown function)(): Uncaught Exception:
Traceback (most recent call last):
  File "compiler_launch.py", line 13, in <module>
  File "vbsp.py", line 1860, in main
  File "vbsp.py", line 158, in load_settings
FileNotFoundError: [Errno 2] No such file or directory: 'bee2/pack_list.cfg'
[17340] Failed to execute script compiler_launch

I don't know how to solve this mistake. Please help me

**Comment by FrozenDragon0** [comment] 2021-02-28 01:32
What version is this?

**Comment by seagemgames** [comment] 2021-02-28 02:11
4.39.0, it says so in the log, this is also a duplicate of #1501

**Closed** 2021-02-28 02:31 UTC
Labels: Duplicate
