### ISSUE TITLE
Detect if portal 2 is already open

### ISSUE THREAD

**Issue by Konclan** [BEEmod/BEE2.4#542] opened 2017-03-08 00:52 UTC
Each time I export it asks me if I want to open the game even if its already open

**Comment by LautaroL20** [comment] 2017-03-08 03:54
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/934 (although they are in different sections, but i think i should move mine to this section.)

**Closed by LautaroL20** 2017-03-08 03:54 UTC
Labels: Duplicate, Enhancement
