### ISSUE TITLE
The Monitor Started Glitching

### ISSUE THREAD

**Issue by WonderlandWar** [BEEmod/BEE2.4#469] opened 2017-01-07 17:06 UTC
http://steamcommunity.com/profiles/76561198025615709/screenshot/185044915415227735

**Comment by Luke18033** [comment] 2017-01-07 17:14
Put issues about items on the [BEE2-items repository](https://github.com/BEEmod/BEE2-items). This is a duplicate of an issue there, BEEmod/BEE2-items#1083.

**Closed by Luke18033** 2017-01-07 17:14 UTC
