### ISSUE TITLE
Conversion Gel crashes game when used in BTS_style 

### ISSUE THREAD

**Issue by Wklaver** [BEEmod/BEE2.4#706] opened 2017-08-05 18:09 UTC
after a while of using Conversion Gel in the Behind The Scenes style the game crashes to desktop.

**Comment by Luke18033** [comment] 2017-08-11 02:49
Do you mean like BEEmod/BEE2-items#347?

**Comment by LautaroL20** [comment] 2017-10-28 16:37
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/347

**Closed by LautaroL20** 2017-10-28 16:37 UTC
Labels: Duplicate
