### ISSUE TITLE
beemod 32bit crash

### ISSUE THREAD

**Issue by thefurrywolf** [BEEmod/BEE2.4#1547] opened 2021-03-29 11:21 UTC
**tried it**

Traceback (most recent call last):
  File "pyglet\media\codecs\wave.py", line 58, in __init__
  File "wave.py", line 510, in open
  File "wave.py", line 164, in __init__
  File "wave.py", line 131, in initfp
wave.Error: file does not start with RIFF id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wave.py", line 109, in decode
  File "pyglet\media\codecs\wave.py", line 60, in __init__
pyglet.media.codecs.wave.WAVEDecodeException: file does not start with RIFF id

**Comment by thefurrywolf** [comment] 2021-03-29 11:25
and this happens if i make it not respond and force close it:
Traceback (most recent call last):
  File "tkinter\__init__.py", line 804, in callit
  File "loadScreen_daemon.py", line 589, in check_queue
  File "multiprocessing\connection.py", line 257, in poll
  File "multiprocessing\connection.py", line 328, in _poll
BrokenPipeError: [WinError 109] The pipe has been ended

**Comment by LautaroL20** [comment] 2021-03-29 13:46
This would be a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1520, as it gives you the same error that i had reported.

**Closed by LautaroL20** 2021-03-29 13:46 UTC
Labels: App Crash, Duplicate
