### ISSUE TITLE
[Bug] Piston doesn't move downwards

### ISSUE THREAD

**Issue by KonnBonn23** [BEEmod/BEE2.4#916] opened 2018-05-10 17:30 UTC
Whenever I try to use piston, they work just fine when extending. but when i want them to retract, they won't move, even with "Autodrop first cube" unchecked. I'm using Pre-Release 29:
![image](https://user-images.githubusercontent.com/6296061/39885259-83771c8e-5462-11e8-88e8-3b54a0469b1f.png)

**Comment by Nikita74Russian** [comment] 2018-05-12 06:37
Close this issue, it's a item issue. While this repository is only for Application itself.

**Comment by PSIGuy** [comment] 2018-07-13 16:05
I personally have had this very same problem.  Apparently the new piston logic for the PR 29 release doesn't work properly for platforms that are supposed to move downward.  What you have to do is place a NOT gate in and set the piston platform to move up instead of down.  This way, when the map loads, the platform will move up automatically and move back down whenever the output is fired (whether that be a button, a laser catcher or whatever else).

**Comment by Luke18033** [comment] 2018-07-13 17:51
Duplicate of BEEmod/BEE2-items#2636.

**Closed by Luke18033** 2018-07-13 17:51 UTC
Labels: Bug
