### ISSUE TITLE
Autosave doesn't save portal gun upgrade

### ISSUE THREAD

**Issue by Jojokesuke** [BEEmod/BEE2.4#828] opened 2018-02-02 03:44 UTC
If you reach an autosave after getting a portal gun upgrade, then die. Upon respawn you go back to whatever you started the map with. Same thing happens if you start out with no portal gun.
Example: https://youtu.be/GvBtreMtkUU

**Comment by Luke18033** [comment] 2018-02-03 18:54
Duplicate of BEEmod/BEE2-items#2436

**Closed by Luke18033** 2018-02-03 18:54 UTC
