### ISSUE TITLE
I'm on a sugar crash

### ISSUE THREAD

**Issue by Swino4ka** [BEEmod/BEE2.4#1577] opened 2021-04-28 05:45 UTC
**BEE2 version: 4.39.1**

**Description of the bug:
![image](https://user-images.githubusercontent.com/83330628/116352528-998e5480-a7f5-11eb-8ff5-924f375c067e.png)
**

**Steps to reproduce: Just launching the app**

**Additional information: Nothing**

**Comment by LautaroL20** [comment] 2021-04-28 05:53
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Closed by LautaroL20** 2021-04-28 05:53 UTC
Labels: App Crash, Duplicate

**Comment by HRudyPlayZ** [comment] 2021-05-07 18:20
Even if this issue is a duplicate, it had a good title so i had to:
https://imgur.com/HUMfXJf
