### ISSUE TITLE
[geometry] BEE2.py attempts to locate bee2.ico in C:/Users/

### ISSUE THREAD

**Issue by koerismo** [BEEmod/BEE2.4#1288] opened 2020-04-19 19:32 UTC
(geometry branch) On launch, BEE2.py crashes after failing to load C:/Users/bee2.ico which does not exist.

**Comment by TeamSpen210** [comment] 2020-04-27 05:34
Do you have the full traceback? Sounds like it might have a space-in-path issue maybe?

**Comment by Luke18033** [comment] 2020-05-18 23:17
Can't reproduce this, closing due to lack of info.

**Closed by Luke18033** 2020-05-18 23:17 UTC
Labels: App Crash, Development Build
