### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by ja39** [BEEmod/BEE2.4#1560] opened 2021-04-10 13:38 UTC
**BEE2 Version: v4.39.2**

<details>
<summary>Error Log</summary>

Traceback (most recent call last):
  File "app\sound.py", line 136, in ticker
  File "pyglet\media\__init__.py", line 140, in load
  File "pyglet\media\__init__.py", line 130, in load
  File "pyglet\media\codecs\wmf.py", line 882, in decode
  File "pyglet\media\codecs\wmf.py", line 498, in __init__
pyglet.media.exceptions.MediaDecodeException: [WinError -1072875836] Verilen URL'nin bayt akışı türü desteklenmiyor

</details>

**Additional information: I can't enter bee2, it gives error**

**Comment by LautaroL20** [comment] 2021-04-10 13:44
This is a duplicate of: #1521

**Closed by LautaroL20** 2021-04-10 13:44 UTC
Labels: Bug, Compile Error, Duplicate

**Comment by ja39** [comment] 2021-04-10 13:50
> This is a duplicate of: #1521

not same???

**Comment by LautaroL20** [comment] 2021-04-10 13:53
Yes, it is the same. If you pay attention to his log, it says: "pyglet.media.exceptions.MediaDecodeException" - that is the same issue as yours.

**Comment by ja39** [comment] 2021-04-10 13:57
ok ty anyways
