### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by nahoJ974** [BEEmod/BEE2.4#853] opened 2018-03-04 05:53 UTC
when i place the neurotoxin vent and the neurotoxin timer in the same test then there are not texture for the goo

If you don't understand watch the video

https://user-images.githubusercontent.com/34785425/36942623-68722bb0-1f90-11e8-8208-202ad7983fac.jpg
https://user-images.githubusercontent.com/34785425/36942624-7a3a403a-1f90-11e8-9b28-2c319ffcb079.jpg

https://www.youtube.com/watch?v=vgk7cE7Rd7M&feature=youtu.be

**Comment by nahoJ974** [comment] 2018-03-04 06:17
FACT: only affect overgrown style

**Comment by TeamSpen210** [comment] 2018-03-17 07:31
Duplicate of #867

**Closed by TeamSpen210** 2018-03-17 07:31 UTC
Labels: Bug
