### ISSUE TITLE
portalgun stand

### ISSUE THREAD

**Issue by anymaker3333** [BEEmod/BEE2.4#1574] opened 2021-04-24 05:57 UTC
you cant spin the portalgun stand. 
if you try to connect, it will say that you have an error in building puzzle

**Comment by FrozenDragon0** [comment] 2021-04-24 06:34
Duplicate of https://github.com/BEEmod/BEE2-items/issues/3667 Also you have posted in the wrong section.

**Closed by FrozenDragon0** 2021-04-24 06:34 UTC
Labels: Bug, Compile Error, Duplicate
