### ISSUE TITLE
BTS Level Exit Door Bug

### ISSUE THREAD

**Issue by Nikita74RU** [BEEmod/BEE2.4#873] opened 2018-03-21 14:45 UTC
When the exit door is activated, it won't open.

**Comment by King0191** [comment] 2018-03-21 15:16
Oh that's actually a bug? I thought I just messed up the wiring

**Comment by cartman1337** [comment] 2018-03-21 15:28
Is this with exit corridor 3 or 4 selected? If so, I've already opened an issue for it in BEE2 Items: https://github.com/BEEmod/BEE2-items/issues/2481

If you have exit corridor 3 or 4 selected, just change it to 1 or 2, and the exit should work normally.

**Comment by LautaroL20** [comment] 2018-03-23 01:05
This repro is only for issues related to the BEE2.4 application itself; anything else goes on [BEE2-items](https://github.com/BEEmod/BEE2-items/issues).

Also, i am sure that this could be a duplicate of cartman´s issue.

**Closed by LautaroL20** 2018-03-23 01:05 UTC
Labels: Duplicate, Item Issue
