### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by Byzarru** [BEEmod/BEE2.4#438] opened 2016-12-03 19:52 UTC
First, the fact that the loading screens will jump in front of all windows is very annoying. See #418.

However, I would like to suggest a new splash screen for BEE. I made a mock-up this morning:
![beesplash copy](https://cloud.githubusercontent.com/assets/22107242/20861800/7aa8e754-b95e-11e6-8c78-6b419de0f6a4.png)

This is inspired by the splash screens for MS Office and Adobe Creative Suite, as well as various mods and tools for other games. Instead of appearing as a set of progress bars, the progress itself would read at the bottom left corner. The version number appears at the bottom right. Below the logos, credits for the mod would appear line by line as the resources load. The splash background would be a random image from a set of screenshots that feature the various styles and items associated with the mod. I can either make a few maps to take screenshots for or we could showcase various maps in the community made with BEE.

Most importantly, the splash screen would hide behind windows if it were so desired.

The fonts used are DIN 1451 Mittelschrift (used for the logos) and Segoe UI (the system font).

If there is interest in this, I can put together some backgrounds and post them here.

**Comment by Jadeygaming** [comment] 2016-12-03 20:59
Looking Good

**Comment by Byzarru** [comment] 2016-12-04 03:59
![rexaura](https://cloud.githubusercontent.com/assets/22107242/20863955/7c4ae46e-b9a3-11e6-873f-f2ae7477d0d1.png)
Background images would showcase the various styles and items you can use.

**Comment by TeamSpen210** [comment] 2016-12-04 06:43
This does sound like a nice idea.

**Comment by ellingtonvengaboysmuseum** [comment] 2016-12-05 16:35
good idea, also check out my issue #442 on a windows installer

**Comment by Byzarru** [comment] 2016-12-06 23:16
I call this one 'Turrets'. It's an exploration of how we're all devices acting on simply-expressed directives, inflicting pain despite our own desires.
![turrets](https://cloud.githubusercontent.com/assets/22107242/20948014/67f8c1bc-bbd7-11e6-8da0-dc57cc2beeab.png)
The observation room has been edited to look darker.

**Comment by LautaroL20** [comment] 2016-12-09 16:28
Yep, the idea is good, but it is clearly visible you weren´t using High Settings video while taking these screenshots. I would recommend to use at least 4x MSAA, Anisotropic X16 video settings to make these look nicer.

**Comment by Luke18033** [comment] 2016-12-21 18:02
@LautaroL20 It's just an example.

**Comment by Byzarru** [comment] 2016-12-21 18:16
I have the .psd if anyone wants to use my template.

**Comment by LautaroL20** [comment] 2016-12-21 19:18
Bee2.4 does not have support for splash screen templates atm, so we could´t use it.

**Comment by TheDarkBomber** [comment] 2016-12-21 19:20
@LautaroL20 It doesn't have support for splash screen templates, because it hasn't been edited yet.

**Comment by LautaroL20** [comment] 2016-12-21 19:26
Ik just telling him we can´t use it atm.

**Comment by TheDarkBomber** [comment] 2017-01-03 21:19
@LautaroL20 He means for image editing a splash screen. @Byzarru I'll take the `.psd`

**Comment by TeamSpen210** [comment] 2017-01-03 21:21
It'd probably be best to not include the text in the image- I'd generate it on top. That way it's easy to change, and can be translated.

**Comment by Byzarru** [comment] 2017-01-03 21:41
The font used in the logo and description is DIN 1451 Mittelschrift, which is used on road signs in Germany. DIN 1451 is a free font family and the predecessor to DIN Pro, the font that Portal 2 uses for its typography. The other font is Segoe UI, which is the system font for Windows 8 and 10. 
@TheDarkBomber, I have the .psd on Google Drive because apparently I can't post it here. [Enjoy](https://drive.google.com/file/d/0BwkksH5z0I7ob2FNOGhlVGJBYU0/view?usp=sharing). 
@TeamSpen210, I have attached a copy of the typographic logo used in the mockups. The logo uses a gradient fill while the description is purely white.
![logographic](https://cloud.githubusercontent.com/assets/22107242/21624013/b8f4d8a4-d1ca-11e6-8244-54919d1205b6.png)

**Comment by TeamSpen210** [comment] 2017-01-07 03:51
Could you attach copies of the various screenshots (no text)?

**Comment by TeamSpen210** [comment] 2017-01-07 05:04
Here's a WIP version of the splash screen implemented.
![image](https://cloud.githubusercontent.com/assets/8453732/21739595/85a4ed04-d4ea-11e6-9e80-d5d91a92f333.png)

**Comment by Byzarru** [comment] 2017-01-07 05:06
Do you want the original files or the cropped versions? I'd like to send you some HD pictures.

**Comment by TeamSpen210** [comment] 2017-01-07 05:17
Originals mainly would be good, just as long as they aren't too big file size-wise (since everyone will need to download them).

**Comment by Byzarru** [comment] 2017-01-07 06:20
I'm currently in the process of doing HD images, but here's the original two, uncropped.
![20161206170157_1](https://cloud.githubusercontent.com/assets/22107242/21739935/09e982ae-d46f-11e6-8020-f084bb68f952.jpg)
![20161203212753_1](https://cloud.githubusercontent.com/assets/22107242/21739936/09eb6f24-d46f-11e6-9139-6ab1e5e8a2ee.jpg)

**Comment by Byzarru** [comment] 2017-01-07 06:28
"Turrets"
Original:
![20170106235430_1](https://cloud.githubusercontent.com/assets/22107242/21739981/216eef62-d470-11e6-9af1-cefa31f4355a.jpg)
Cropped and adjusted:
![turrets](https://cloud.githubusercontent.com/assets/22107242/21739982/2497ae9a-d470-11e6-83f7-d5654832cb63.png)

**Comment by Byzarru** [comment] 2017-01-07 06:30
"Square Root of Minus Portal + Portals"
Original:
![20170106235956_1](https://cloud.githubusercontent.com/assets/22107242/21739988/60cf520a-d470-11e6-9745-e9ddb5670375.jpg)
Cropped and adjusted:
![squareroot](https://cloud.githubusercontent.com/assets/22107242/21739990/6752288c-d470-11e6-8b9a-2d86143ca3e8.png)

**Comment by Byzarru** [comment] 2017-01-07 22:26
"Cube Altar"
![20170107161401_1](https://cloud.githubusercontent.com/assets/22107242/21745656/ee54c878-d4f5-11e6-8d82-58c0f0c63639.jpg)

**Comment by TheDarkBomber** [comment] 2017-01-07 22:32
Needs `Confirmed` label.

**Comment by TeamSpen210** [comment] 2017-01-07 22:36
Anyone can feel free to post more screenshots.

**Comment by TeamSpen210** [comment] 2017-01-07 22:37
Image-wise they should be about regular screen resolution, JPEG compresses it down nicely.

**Comment by TheDarkBomber** [comment] 2017-01-07 22:38
I'll post more screenshots.

**Comment by Byzarru** [comment] 2017-01-07 22:55
Have them at the highest quality, too.

>  I would recommend to use at least 4x MSAA, Anisotropic X16 video settings to make these look nicer.

And don't forget:
```
sv_cheats 1
noclip 1
god 1
portal_draw_ghosting 0
r_drawviewmodel 0
cl_drawhud 0
notarget
```

**Comment by Byzarru** [comment] 2017-01-08 00:12
"Behind a Scene"
![20170107180808_1](https://cloud.githubusercontent.com/assets/22107242/21746283/d18e448a-d504-11e6-898d-d740ff6e8c1e.jpg)

**Comment by TheDarkBomber** [comment] 2017-01-08 12:32
Fling
[!fling](http://i.imgur.com/2o0NfTj.jpg)

**Comment by Luke18033** [comment] 2017-01-08 16:40
Why does that look like Portal 2 Beta?

**Comment by TheDarkBomber** [comment] 2017-01-08 16:41
I manipulated the image in GIMP as an attempt to make it look better.

**Comment by Byzarru** [comment] 2017-01-08 16:43
Do you have the original .jpg screenshot? Apparently TeamSpen's using those (He already has a splash screen format to work with).

**Comment by TheDarkBomber** [comment] 2017-01-08 16:45
"Fling" Original:
![20170108120927_2](https://cloud.githubusercontent.com/assets/17354045/21751605/cbd3f52c-d5c1-11e6-83f3-e79a4e006440.jpg)
"Fling" Manipulated:
![fling](https://camo.githubusercontent.com/862b24eef1d1b2bbc042c89477c8da747d0271ca/687474703a2f2f692e696d6775722e636f6d2f326f304e66546a2e6a7067)

**Comment by Luke18033** [comment] 2017-01-08 16:56
And is that the Closed Solid Field?

**Comment by TheDarkBomber** [comment] 2017-01-08 16:57
And the Protruding Pedestal Button.

**Comment by Luke18033** [comment] 2017-01-08 16:58
So your fizzlers have been merged into `dev`?

**Comment by TheDarkBomber** [comment] 2017-01-08 16:59
No, but they will be in the next update. BTW, what should the next update be called? The Content Update? The Item Update? The Feature Update?

**Comment by Luke18033** [comment] 2017-01-08 17:00
I think The Content Update would be best.

**Comment by TheDarkBomber** [comment] 2017-01-08 17:03
I agree.

**Comment by Luke18033** [comment] 2017-01-08 17:03
Somebody should make something like this for the update:
![mc1.9](https://hydra-media.cursecdn.com/minecraft.gamepedia.com/6/6d/Combat_Update.png?version=cc4742d32d327a9555b306596c3692d2)
Except with the BEE2 logo and a test chamber containing all the new items.

**Comment by TheDarkBomber** [comment] 2017-01-08 17:04
**All** the new items?

**Comment by Luke18033** [comment] 2017-01-10 16:06
> And don't forget

Additionally, if you're using an old version of he test chamber, you'll also need `r_drawvgui` to get rid of "This view is not current". You shouldn't need to do that though, I only had to since my chamber was made in the dev version which no longer works for me.

**Comment by Luke18033** [comment] 2017-01-10 16:07
"The Abandoned Testing Track"
![abandoned-testing-track](https://cloud.githubusercontent.com/assets/19228201/21813654/c6f9cedc-d70b-11e6-82aa-1f550aedabbc.jpg)

**Comment by TheDarkBomber** [comment] 2017-01-10 17:14
@TeamSpen210 Is the next release PR24 or R1?

**Comment by Luke18033** [comment] 2017-01-16 02:43
The splash screen looks nice! Now you just need to make it stop overlapping everything.

Seriously, why did you make it do that originally?

**Comment by TeamSpen210** [comment] 2017-01-16 06:01
It's not really that fixable. The application is busy doing all the file reading and parsing while the loading screen is displayed, so it actually won't respond to you moving the window around. It's also not a normal window (since it doesn't have a title bar and other bits), which makes Windows behave oddly with it.

**Comment by LautaroL20** [comment] 2017-01-16 13:42
@TheDarkBomber - I seriously doubt that the next release will be the R1. It will be a PRL24 for sure (and afther will probably be a PRL25 too). Just see the numerous problems that the BTS Style is having.... A Release 1 would have at least all the current features fixed, wich isn´t the case.

**Comment by Luke18033** [comment] 2017-01-16 22:15
@TeamSpen210 If that's the case, then shouldn't #418 be closed?

**Comment by LautaroL20** [comment] 2017-01-16 22:43
@Luke18033 - I saw that post and i think if that guy is complaining about that little exporting panel overlapping his desktop, then he don´t want to know what is to come then.... lol! But if it's any consolation for him, it will include some nice screenshots.

**Closed** 2017-01-21 07:32 UTC
Labels: enhancement, Implemented for next release, New Feature

**Comment by TheDarkBomber** [comment] 2017-02-23 15:38
Don't stop posting screenshots for the Splash Screen!

**Comment by Byzarru** [comment] 2017-02-23 17:53
The ones we have are enough.
