### ISSUE TITLE
Ceiling/Floor Observation Rooms Non-Functional

### ISSUE THREAD

**Issue by peefTube** [BEEmod/BEE2.4#628] opened 2017-05-16 21:24 UTC
Any time I try to place a ceiling or floor observation room Portal 2 refuses to build the map. As soon as I remove said room(s) it begins working again. I'm not 100% sure but I think I've tried it in every style.

**Comment by Luke18033** [comment] 2017-05-17 16:46
Duplicate of BEEmod/BEE2-items#1423.

**Closed by Luke18033** 2017-05-17 16:46 UTC
