### ISSUE TITLE
Voice Lines Not Implemented

### ISSUE THREAD

**Issue by ZFM2004** [BEEmod/BEE2.4#617] opened 2017-05-10 10:30 UTC
It does not have some voice lines (sometimes none) for caroline, portal 1 glados, BTS announcer, & I think that is it.

**Comment by ZombiePwner1** [comment] 2017-05-10 12:58
Portal 1 GLaDOS's voicelines haven't been included yet

**Comment by iEnderMan06** [comment] 2017-05-19 00:45
Then don't add it to a release if it's not even in there. 👎

**Comment by Konclan** [comment] 2019-08-29 02:27
Duplicate of BEEmod/BEE2-items#389

**Closed by Konclan** 2019-08-29 02:27 UTC
Labels: Bug
