### ISSUE TITLE
"ensure the PORTAL2 is not running"

### ISSUE THREAD

**Issue by homelessturret** [BEEmod/BEE2.4#729] opened 2017-09-01 17:55 UTC
Everytime i export this happens 
![well this is happening](https://user-images.githubusercontent.com/31522977/29981841-2fe6c962-8f1d-11e7-86c5-83889f7fbffc.PNG)

**Comment by LautaroL20** [comment] 2017-09-01 19:41
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/728

**Closed by LautaroL20** 2017-09-01 19:41 UTC
Labels: Bug, Duplicate
