### ISSUE TITLE
"Invalid position error" (if you put more than one item on same block)

### ISSUE THREAD

**Issue by sf3d-dk** [BEEmod/BEE2.4#1504] opened 2021-02-22 19:48 UTC

**Comment by sf3d-dk** [comment] 2021-02-22 19:54
BEMOD 4.39.0., 
link to a video:
https://youtu.be/UAJFWZqxEFE

**Comment by Luke18033** [comment] 2021-02-22 20:01
Duplicate of BEEmod/BEE2-items#3652

**Closed by Luke18033** 2021-02-22 20:01 UTC
