### ISSUE TITLE
Make more choices for elevator coming direction 

### ISSUE THREAD

**Issue by SpyyZ158** [BEEmod/BEE2.4#791] opened 2017-12-16 11:52 UTC
For example normal elevator goes from down to up on start of map , why not make it also from up to down direction , same for exit elevator from up to down , this would make few sense like going in underground for people making series of maps
It can be chosen by Bee 2.4 app in compile options for example.

**Comment by TeamSpen210** [comment] 2017-12-16 22:15
I'm explicitly not supporting map series, the PeTI has no business doing that. But yes this is desirable, probably a random option.

**Comment by SpyyZ158** [comment] 2017-12-17 08:17
and is it doable?

**Comment by LautaroL20** [comment] 2017-12-21 14:29
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/757

**Closed by LautaroL20** 2017-12-21 14:29 UTC
Labels: Duplicate
