### ISSUE TITLE
Suggestion: PotatOS Portal Gun

### ISSUE THREAD

**Issue by WafflesAndSyrup** [BEEmod/BEE2.4#848] opened 2018-02-27 01:33 UTC
![maxresdefault](https://user-images.githubusercontent.com/36249695/36705647-3ff7fc3e-1ba1-11e8-9c6a-d4c3ec99e516.jpg)
![c08_11](https://user-images.githubusercontent.com/36249695/36705652-435cb9e6-1ba1-11e8-9ca9-a881647b28e0.jpg)

**Comment by LautaroL20** [comment] 2018-02-27 08:16
This is a duplicate of: https://github.com/BEEmod/BEE2-items/issues/418

**Closed by LautaroL20** 2018-02-27 08:16 UTC
Labels: Duplicate
