### ISSUE TITLE
Display error message if BEE2 is installed in the P2 folder

### ISSUE THREAD

**Issue by Luke18033** [BEEmod/BEE2.4#1799] opened 2022-01-21 00:35 UTC
Some people download BEE2 and install it to `Portal 2/bee2/`, not realizing that this is used as the BEE2 search path when exporting. Rather than letting this happen, resulting in a cryptic "access denied" message appearing later when exporting/compiling, BEE2 should detect this on startup and display a message that it needs to be installed somewhere else, then exit.

**Comment by flarn2006** [comment] 2022-05-22 23:18
This is exactly where I was planning on installing it. Glad I saw this.

**Comment by flarn2006** [comment] 2022-05-22 23:20
Actually isn't this a duplicate of #1258? Did you forget you posted that one?

**Comment by Luke18033** [comment] 2022-05-22 23:27
Yeah it is, I wish TeamSpen would implement this because people do this really often and it's easy to deal with...

**Closed** 2022-10-18 03:35 UTC
Labels: Enhancement, Done
