### ISSUE TITLE
Bee2.4 crashes on startup

### ISSUE THREAD

**Issue by RadioactiveTurtle** [BEEmod/BEE2.4#954] opened 2018-07-12 04:29 UTC
Ive been troubleshooting this for a few hours now but every time i try to run BEE2.4 it crashes when it gets to "initializing ui" and spits out this error message

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "C:\Users\Spencer Brown\.virtualenvs\BEE2\lib\site-packages\cx_Freeze\initscripts\Console.py", line 24, in <module>
  File "BEE2_launch.pyw", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "F:\Git\BEE2.4\src\BEE2.py", line 115, in <module>
  File "F:\Git\BEE2.4\src\gameMan.py", line 989, in init_trans
  File "F:\Git\srctools\srctools\property_parser.py", line 360, in parse
srctools.property_parser.KeyValError: Block opening ("{") required, but hit EOF!
A "name" line was located at the end of the file, which needs a {} block to follow.
Error occurred with file "appmanifest_620.acf".

**Comment by TeamSpen210** [comment] 2018-07-12 08:42
This is a duplicate of #927. Here's the fix:
> Go to your start menu, and search "environment variables". Select the user option. Then add a variable named BEE2_P2_LANG, with a value of english (or whatever preferred language for Portal 2).

**Comment by RadioactiveTurtle** [comment] 2018-07-12 13:22
Thanks! it actually worked!

**Closed** 2018-07-13 03:54 UTC
Labels: Crash, Duplicate, Fixed
