### ISSUE TITLE
Beemod causes "Failure To Compile" - Could not open instance file instances/BEE2/50s/items/screen/monitor.vmf

### ISSUE THREAD

**Issue by CaveJohnsonOfApertureScience** [BEEmod/BEE2.4#1367] opened 2020-08-05 09:37 UTC
Could not open instance file `instances/BEE2/50s/items/screen/monitor.vmf`

So any sort of style i choose (for example old aperture: 1950) and build a level, and to to play test it, i get a build error. So i go to steam and validate files and it says anywhere from 8-15 files were missing. I let them install again, but then the style doesn't work anymore. What do i do? Here isa screenshot for context or something its 5 am i dont know the word to use honestly. 

![Screenshot (11)](https://user-images.githubusercontent.com/69241355/89397315-b5891d80-d6dd-11ea-9864-5a553ae3b59f.png)

**Comment by FrozenDragon0** [comment] 2020-08-05 09:42
Open console and give us the error log so we can see what it's saying.

**Comment by CaveJohnsonOfApertureScience** [comment] 2020-08-05 09:48
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/change_this
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
--- Missing Vgui material vgui/hud/commands/gesture_sitspin_orange
--- Missing Vgui material vgui/hud/commands/gesture_Spinjump
--- Missing Vgui material vgui/hud/commands/gesture_headspin
--- Missing Vgui material vgui/hud/commands/gesture_pretzelwave
Hud element 'CHUDVSScorePanel' doesn't have an entry 'VSScorePanel' in scripts/HudLayout.res
Hud element 'CHUDPaintAmmo' doesn't have an entry 'PaintAmmo' in scripts/HudLayout.res
Hud element 'CHudSubtitles' doesn't have an entry 'HudSubtitles' in scripts/HudLayout.res
Hud element 'CHudSaveStatus' doesn't have an entry 'HudSaveStatus' in scripts/HudLayout.res
--- Missing Vgui material vgui/hud/commands/gesture_smallwave
Unknown command "cl_thirdperson"
Unknown command "joy_no_accel_scale"
Using joystick 'Xbox360 controller' configuration
Advanced joystick settings initialized for joystick 1
------------
joy1 x axis:  strafe (absolute)
joy1 y axis:  forward (absolute)
joy1 z axis:  unmapped
joy1 r axis:  pitch (absolute)
joy1 u axis:  yaw (absolute)
joy1 v axis:  unmapped
Advanced joystick settings initialized for joystick 2
------------
joy2 x axis:  strafe (absolute)
joy2 y axis:  forward (absolute)
joy2 z axis:  unmapped
joy2 r axis:  pitch (absolute)
joy2 u axis:  yaw (absolute)
joy2 v axis:  unmapped
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: lock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: unlock_cmd
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Activate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Out_Deactivate
[PORTAL2 PUZZLEMAKER]  Unrecognised connection type: Force
Unknown command "cl_thirdperson"
C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control

**Comment by FrozenDragon0** [comment] 2020-08-05 09:53
Is this the bottom of the log?

**Comment by CaveJohnsonOfApertureScience** [comment] 2020-08-05 09:54
yeah, i just cut out the file location and ip

**Comment by FrozenDragon0** [comment] 2020-08-05 09:56
File location for the instances?

**Comment by CaveJohnsonOfApertureScience** [comment] 2020-08-05 09:57
Parent cvar in client.dll not allowed (movement_anim_playback_minrate)
Game supporting (2) split screen players
maxplayers set to 1
Steam config directory: D:\Steam\steamapps\common\Portal 2\portal2.exe\platform\config
-

**Comment by FrozenDragon0** [comment] 2020-08-05 09:59
Hmmm not sure.

**Comment by CaveJohnsonOfApertureScience** [comment] 2020-08-05 10:00
Darn

**Comment by FrozenDragon0** [comment] 2020-08-05 10:02
I'll let one of the others try see what the issue is.

**Comment by CaveJohnsonOfApertureScience** [comment] 2020-08-05 17:09
it happened again but the console has a different error. What confuses me is that it was just working but all the sudden it doesn't work ;-;

C_GameInstructor::ReadSaveData failed to read GI.lesson.Swap_Split_Screen_Control
[PORTAL2 PUZZLEMAKER]  New chamber!
Unknown command "cl_puzzlemaker_activate"
CGameUIConVarRef mp_gamemode doesn't point to an existing ConVar
maxplayers set to 1
---- Host_NewGame ----
Network: IP 192.168.0.8, mode SP, dedicated No, ports 0 SV / 0 CL
Opened Steam Socket NS_SERVER ( socket 3288 )
Opened Steam Socket NS_CLIENT ( socket 3300 )
Network: IP 192.168.0.8, mode MP, dedicated No, ports 27015 SV / 27005 CL
Couldn't get HDR 'maps\newchamber/c-1904_2096_-48.hdr' -- Trying non HDR 'maps\newchamber/c-1904_2096_-48'
Failed, using default cubemap 'engine/defaultcubemap'
Couldn't get HDR 'maps\newchamber/c-2032_-2032_-31.hdr' -- Trying non HDR 'maps\newchamber/c-2032_-2032_-31'
Failed, using default cubemap 'engine/defaultcubemap'
Host_NewGame on map puzzlemaker\newchamber
exec: couldn't exec skill1.cfg
==== calling mapspawn.nut
Unable to load sprite material materials/sprites/gunsmoke.vmt!
Unable to load sprite material materials/sprites/bubble.vmt!
Attempted to create unknown entity type playtest_manager!
Can't init playtest_manager
Couldn't find any entities named doorentry0-player_start_teleport, which point_template @player_start_template is specifying.
Commentary: Could not find commentary data file 'maps/puzzlemaker\newchamber_commentary.txt'. 
1.000:  Sending UDP connect to public IP 127.0.0.1:27015
Server using '<none>' lobbies, requiring pw no, lobby id 0
RememberIPAddressForLobby: lobby 0 from address loopback
Connection to Steam servers successful.
   VAC secure mode is activated.
Can't find factory for entity: wearable_item
NULL Ent in UTIL_PrecacheOther
[PORTAL2 PUZZLEMAKER]  --------START loading assets--------

[PORTAL2 PUZZLEMAKER]  ---------END loading assets---------

==== calling mapspawn.nut
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
Parent cvar in client.dll not allowed (r_shadowlod)
***********************************
*         NO GAME SESSION         *
* some features might be disabled *
* (achievements, stats, UI, etc.) *
***********************************
Redownloading all lightmaps
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf ...
[PORTAL2 PUZZLEMAKER]  CVoxelTestChamber::Export VMF success, chamber size: (8,6,4)
[PORTAL2 PUZZLEMAKER]  Compilation time (after export): 35 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "D:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[W] vbsp_options.load(): Extra config options: {'music_location_sp': '-2824 2040 -768', 'voice_pack': 'BEE2_CAVE_50s'}
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 1
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (101 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] instanceLocs.get_subitems(): Invalid custom instance name - "single" for <item_rail_platform> (Valid: {'static': 'instances/bee2/50s/items/track/static.vmf'})
[W] packing.pack_list(): Packlist "PACK_PELLET" does not exist!
[W] cond.connections.res_locking_output(): MarkLocking is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] vbsp.set_elev_videos(): Elevator type: NONE
[W] cond.connections.res_locking_input(): LockingIO is no longer used. Configure locking items in the enhanced editoritems configuration.
[I] voiceLine.add_voice(): Adding Voice Lines!
[W] BEE2_config.load(): Config "bee2/voice.cfg" not found! Using defaults...
[W] BEE2_config.load(): Config "bee2/mid_voice.cfg" not found! Using defaults...
[I] voiceLine.add_voice(): Adding Base instance!
[I] voiceLine.add_voice(): Quote events: ['bee2_monitor_shatter']
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.find_group_quotes(): "ENTRY": 1/6 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "WELCOME_APER"
 | 	"Bullseye" "cave_a3_03_lift_shaft"
 | 	"Choreo" "npc/cavejohnson/fifties_intro01.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "EXIT": 1/7 quotes..
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "GREAT_JOB_ASTRONAUT"
 | 	"Bullseye" "@cave_exit_lift"
 | 	"Choreo" "npc/cavejohnson/seventies_test_a_complete06.vcd"
 | 	}
 | 
 |___

[I] voiceLine.find_group_quotes(): "MIDCHAMBER": 2/2 quotes..
[I] voiceLine.add_voice(): Using microphones...
[I] voiceLine.add_voice(): 1 Mid quotes
[I] voiceLine.add_quote(): Adding quote: "Line"
 | 	{
 | 	"ID" "CAVE_LOITER"
 | 	"Quote_Name" "@cave_catwalks"
 | 	"Bullseye" "cave_crazy_box_2nd_chamber"
 | 	"Choreo"
 | 		{
 | 		"1" "npc/cavejohnson/fifties_fifth_test_intro01.vcd"
 | 		"2" "npc/cavejohnson/fifties_fifth_test_intro03.vcd"
 | 		}
 | 	}
 | 
 |___

[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'grating', 'cube', 'cubestandard', 'cubedropper', 'cubedropperstandard', 'cubenotcompanion', 'monitor', 'pellet', 'pelletlauncher', 'pedestalbutton', 'pelletcatcher', 'obsworldportal', 'observationgrate', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=10310, misses=341, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': True, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True, 'retro_voice_pre_line': False}
[I] cond.core.check_all(): Global instances: set()
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 96.0 <- Counter({96.0: 27})
[I] vbsp.clump_walls(): Clumping: 155 clumps (+ 0 special)
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'D:/Steam/steamapps/common/Portal 2/portal2/', 'D:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 8 threads
[I] <valve>.vbsp(): materialPath: D:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading D:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Error! Variable "$envmap" is multiply defined in material "metal/underground_wall_metal004a_bottom"!
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/50s/items/screen/monitor.vmf
[I] <valve>.vbsp(): 


[PORTAL2 PUZZLEMAKER]  Saved puzzle: D:/Steam/steamapps/common/Portal 2/portal2/puzzles\76561198800352252\autosave.p2c
Child is a Terrorist unpaused the game
[PORTAL2 PUZZLEMAKER]  Saved puzzle: puzzles\76561198800352252\1596647111.p2c
Unable to remove d:\steam\steamapps\common\portal 2\portal2\puzzles\76561198800352252\autosave.p2c! (errno 2)
Unknown command "cl_puzzlemaker_deactivate"
Dropped LITTLE BABY MAN HAHA from server (Server shutting down)

**Comment by LautaroL20** [comment] 2020-08-06 14:00
The cause of your issue is the 50s monitor item: `Could not open instance file instances/BEE2/50s/items/screen/monitor.vmf`

**Comment by Luke18033** [comment] 2020-08-06 17:32
Duplicate of BEEmod/BEE2-items#3269

**Closed by Luke18033** 2020-08-06 17:32 UTC
Labels: Compile Error
