### ISSUE TITLE
Every time I try to export to portal i get this error: "FileNotFoundError: [Errno 2] No such file or directory: \\AppData\\Roaming\\BEEMOD2\\Screenshot.jpg"

### ISSUE THREAD

**Issue by NocoReal** [BEEmod/BEE2.4#1592] opened 2021-05-22 23:34 UTC
So every time I try to export to portal I get this error, it doesn't cause any problems but its annoying
![bee2error](https://user-images.githubusercontent.com/84647255/119243422-3e8b1b80-bb6f-11eb-9c99-35c47a8787e2.png)
I just want to know if there is a fix

**Comment by LautaroL20** [comment] 2021-08-02 03:21
The cause of this error might be similar or identical to: https://github.com/BEEmod/BEE2.4/issues/1624, so closing this in favor of that issue. By the way, this will be fixed in the next BEE2 release.

**Closed by LautaroL20** 2021-08-02 03:21 UTC
Labels: App Crash, Done
