### ISSUE TITLE
Compile Error on Overgrown Theme only.

### ISSUE THREAD

**Issue by keifersisawesome** [BEEmod/BEE2.4#1289] opened 2020-04-21 22:53 UTC
We've got a compile error boys. Here's what the dev console turned up for me. It failed at the building stage.

TAL2 PUZZLEMAKER]  Compilation time (after export): 115 (ms)

VBSP failed.

[I] vbsp.main(): BEE2 v4.36.0 VBSP hook initiallised.
[I] cond.core.import_conditions(): Imported all conditions modules!
[I] vbsp.main(): Map path is "E:/Steam/steamapps/common/Portal 2/sdk_content\maps/preview.vmf"
[I] vbsp.main(): New path: "E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf"
[I] vbsp.main(): Clearing inject/ directory..
[I] vbsp.main(): PeTI map detected!
[I] vbsp.main(): Loading settings...
[I] cubes.parse_conf(): Parsed 7 cube types, 1 dropper types and 4 addons.
[W] fizzler.parse(): No base instance set! for "BEE2_PRO_LIFEFORM_SENSOR"!
[I] fizzler.read_configs(): Loaded 14 fizzlers.
[I] vbsp.load_settings(): Settings Loaded!
[I] vbsp.load_map(): Parsing Map...
[I] vbsp.load_map(): Reading Map...
[I] vbsp.load_map(): Loading complete!
[I] vbsp.get_map_info(): Forcing elevator spawn!
[I] vbsp.mod_entryexit(): Setting SP Entry to 1
[I] vbsp.mod_entryexit(): Setting SP Exit to 4
[I] vbsp.get_map_info(): Game Mode: SP
[I] vbsp.get_map_info(): Is Preview: False
[I] brushLoc.read_from_map(): Analysed map, filling air... (675 starting positions..)
[I] brushLoc.read_from_map(): Air filled!
[I] cond.core.check_all(): Checking Conditions...
[I] cubes.link_cubes(): SPLAT File: ['instances/bee2/logic/gel_splat.vmf']
[I] cond.catwalks.res_make_catwalk(): Starting catwalk generator...
[I] cond.catwalks.res_make_catwalk(): Connections: {<srctools.vmf.Entity object at 0x05DF5E50>: <conditions.catwalks.Link object at 0x04C301C0>, <srctools.vmf.Entity object at 0x05DF5F10>: <conditions.catwalks.Link object at 0x04C300A8>, <srctools.vmf.Entity object at 0x05DF5FD0>: <conditions.catwalks.Link object at 0x04C306E8>, <srctools.vmf.Entity object at 0x05DFF0B0>: <conditions.catwalks.Link object at 0x04C30EB8>, <srctools.vmf.Entity object at 0x05DFF170>: <conditions.catwalks.Link object at 0x04C30B98>}
[I] cond.catwalks.res_make_catwalk(): Markers: {'catw87': <srctools.vmf.Entity object at 0x05DF5E50>, 'catw88': <srctools.vmf.Entity object at 0x05DF5F10>, 'catw89': <srctools.vmf.Entity object at 0x05DF5FD0>, 'catw90': <srctools.vmf.Entity object at 0x05DFF0B0>, 'catw91': <srctools.vmf.Entity object at 0x05DFF170>}
[I] cond.catwalks.res_make_catwalk(): Finished catwalk generation!
[I] cond.monitor.mon_camera_link(): Bullseye defaultdict(<class 'int'>, {})
[I] connections.gen_item_outputs(): Generating item IO...
[I] connections.gen_item_outputs(): Item IO generated.
[I] cond.core.res_goo_debris(): GooDebris: 31/94 locations
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1426 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1464 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1579 in final) is not on grid!
[W] template.retexture_template(): Realign face in template "bee_door_cowl_clean" (1516 in final) is not on grid!
[I] cond.scaffold.res_unst_scaffold(): Running Scaffold Generator (BEE2_SCAFFOLD)...
[I] cond.scaffold.res_unst_scaffold(): Finished Scaffold generation!
[I] cond.vactubes.res_make_vactubes(): Running Generator (BEE2_VACTUBES)...
[W] packing.pack_list(): Packlist "PACK_BEE2_MODERN_DROPPER_WRECKED" does not exist!
[W] cond.core.resolve_value(): Invalid fixup ($color) in the "cd95" instance:
 | <Entity>: 
 | {
 | 	 classname = "func_instance"
 | 	 targetname = "cd95"
 | 	 file = "instances/BEE2/over/items/cube/dropper.vmf"
 | 	 origin = "64 1344 704"
 | 	 angles = "0 180 180"
 | 	 $connectioncount = "1"
 | 	 $item_fall_straight_down = "1"
 | 	 $disable_autodrop = "1"
 | 	 $disable_autorespawn = "0"
 | }
 | 
 | {'connectioncount': FixupTuple(var='connectioncount', value='1', id=1), 'item_fall_straight_down': FixupTuple(var='item_fall_straight_down', value='1', id=5), 'disable_autodrop': FixupTuple(var='disable_autodrop', value='1', id=4), 'disable_autorespawn': FixupTuple(var='disable_autorespawn', value='0', id=3)}
 |___

[W] packing.pack_list(): Packlist "PACK_BEE2_OVER_CATWALK_SP_ELEVATOR" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_RUSTY_TRUSS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_C" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_ELEVATOR_DIRTY" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_A" does not exist!
[W] packing.pack_list(): Packlist "PACK_GEL_DROPPER_OVER" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_B" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_CORNER_C" does not exist!
[W] packing.pack_list(): Packlist "VACTUBE_128_STRAIGHT_GLASS" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_B" does not exist!
[W] packing.pack_list(): Packlist "PACK_BEE2_TRIPLE_WALLPIPE_STRAIGHT_c" does not exist!
[I] vbsp.set_elev_videos(): Elevator type: FORCE
[I] voiceLine.add_voice(): Adding Voice Lines!
[I] voiceLine.add_voice(): Quote events: []
[I] voiceLine.add_voice(): No responses data..
[I] voiceLine.add_voice(): 0 Mid quotes
[I] voiceLine.add_voice(): Done!
[I] vbsp.set_player_portalgun(): Setting Portalgun:
[I] vbsp.set_player_portalgun(): Blue: Y, Orange: Y
[I] vbsp.set_player_portalgun(): Done!
[I] cond.core.check_all(): Map has attributes: ['goo', 'grating', 'glass', 'cube', 'cubestandard', 'cubedropperlessstandard', 'cubenotcompanion', 'cubedropper', 'cubedropperstandard', 'weightedbutton', 'floorbutton', 'buttonacceptscube', 'buttonacceptsball', 'gel', 'bouncegel', 'bluegel', 'geldropper', 'water', 'watergel', 'cleargel', 'pedestalbutton', 'spawn_dual']
[I] cond.core.check_all(): instanceLocs cache: CacheInfo(hits=84258, misses=392, maxsize=256, currsize=256)
[I] cond.core.check_all(): Style Vars: {'bee2_goo_debris': True, 'overfunnelflicker': False, 'restartonexit': True, 'multiversecave': True, 'fixfizzlerbump': False, 'nomidvoices': False, 'unlockdefault': False, 'allowgoomist': True, 'funnelallowswitchedlights': True, 'enableshapesignageframe': True}
[I] cond.core.check_all(): Global instances: {'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1.vmf', 'instances/BEE2/over/global_ents.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_blue.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_2.vmf', 'instances/BEE2/over/elevator_sp/wp_holes/wp_hole_1_cube.vmf'}
[I] vbsp.add_extra_ents(): Adding Music...
[I] vbsp.add_extra_ents(): Adding global ents...
[I] vbsp.add_extra_ents(): Adding Global PTI Ents
[I] vbsp.change_ents(): Editing Other Entities...
[I] vbsp.fixup_goo_sides(): Changing goo sides...
[I] vbsp.fixup_goo_sides(): Done!
[I] vbsp.change_brush(): Editing Brushes...
[I] vbsp.change_brush(): Make Bottomless Pit: False
[I] vbsp.change_brush(): Goo heights: 224.0 <- Counter({224.0: 94})
[I] vbsp.change_brush(): Adding Goo Mist...
[I] vbsp.change_brush(): Done!
[I] vbsp.change_overlays(): Editing Overlays...
[I] vbsp.collapse_goo_trig(): Collapsing goo triggers...
[I] vbsp.collapse_goo_trig(): Done!
[I] vbsp.change_func_brush(): Editing Brush Entities...
[I] vbsp.fix_worldspawn(): Editing WorldSpawn
[I] vbsp.save(): Saving New Map...
[I] vbsp.save(): Complete!
[I] <Valve>.run_compiler(): Calling original VBSP...
[I] <Valve>.run_compiler(): Args: '-game', 'E:/Steam/steamapps/common/Portal 2/portal2/', 'E:/Steam/steamapps/common/Portal 2/sdk_content\\maps\\styled\\preview.vmf'
[I] <valve>.vbsp(): Valve Software - vbsp.exe (Nov 12 2019)
[I] <valve>.vbsp(): 16 threads
[I] <valve>.vbsp(): materialPath: E:\Steam\steamapps\common\Portal 2\portal2\materials
[I] <valve>.vbsp(): Loading E:/Steam/steamapps/common/Portal 2/sdk_content\maps\styled\preview.vmf
[I] <valve>.vbsp(): ConVarRef gpu_level doesn't point to an existing ConVar
[I] <valve>.vbsp(): Could not open instance file instances/BEE2/clean/items/tSpen/chamberlock_black.vmf
[I] <valve>.vbsp():

**Comment by Flash4433** [comment] 2020-04-21 22:58
Missing the black surface variant of the Chamberlock. What most likely happened here, if it works on other styles, is that the Clean Chamberlock was updated, and the overgrown version wasn't changed to fit that.

**Comment by keifersisawesome** [comment] 2020-04-21 23:01
It does work on other stiles. That's definitely it then.

**Comment by Luke18033** [comment] 2020-04-21 23:17
Duplicate of BEEmod/BEE2-items#2962, and wrong repository.

**Closed by Luke18033** 2020-04-21 23:17 UTC
