### ISSUE TITLE
Discord link inside the Beemod´s help menu leads to a 404 page error...

### ISSUE THREAD

**Issue by LautaroL20** [BEEmod/BEE2.4#1115] opened 2019-05-17 21:42 UTC
The link inside the Beemod´s interface leads to a 404 page error, here is a screenshot:
![Trouble](https://user-images.githubusercontent.com/12244376/57957437-a3517280-78d2-11e9-9143-7a4e217ff2e7.png)

**Comment by Luke18033** [comment] 2019-05-17 21:51
Discord.me decided to remove our invite link, I've changed all the links on GitHub to use a generic discord.gg invite but the link in the app still needs to be updated.

**Comment by TeamSpen210** [comment] 2019-05-19 22:58
Technically a duplicate of BEEmod/BEE2-items#2954, but that should probably be closed in favour of this since it's on the right repo.

**Closed** 2019-06-05 20:40 UTC
Labels: Bug, Fixed
