### ISSUE TITLE
Hidden Floor Button Doesn't Work in Portal 1 Style

### ISSUE THREAD

**Issue by JVGRYT** [BEEmod/BEE2.4#1843] opened 2022-06-05 21:50 UTC
### BEE2 Application Version

4.41.0 64bit (I'm pretty sure)

### BEE2 Package Version

4.40.0 (I think)

### What operating system are you running on?

Windows 10 (64bit)

### Description of the bug

So, for some reason, when I go into the settings and change the style to Portal 1, then place a hidden floor button (the one that has panels that close over it), I can't connect anything to it  and vice versa. Even when I fix it in another style, then go back to Portal 1, all the connections are removed! Fix?

### Expected behavior

It should probably be able to connect with other objects for power. For some reason, hidden pedestal buttons work just fine.

### Steps to reproduce

1. Go into Portal 1 style
2. Add hidden floor button
3. Try to connect it to anything.

### Logs and Reports

```shell
I'll... uh... get back to you on that. Sorry, I haven't had a chance to check the log, I'm writing this issue on my phone.
```

### Additional information

Using Portal 1 style.

**Comment by Luke18033** [comment] 2022-06-05 22:35
Duplicate of BEEmod/BEE2-items#3962, does it really only happen in P1 though? I thought it happened in every style.

**Closed by Luke18033** 2022-06-05 22:35 UTC
Labels: Bug

**Comment by JVGRYT** [comment] 2022-06-05 22:36
> Duplicate of [BEEmod/BEE2-items#3962](https://github.com/BEEmod/BEE2-items/issues/3962), does it really only happen in P1 though? I thought it happened in every style.

Yes. It worked in other styles.
