### ISSUE TITLE
BEE2_v4.39.2_win64 ERROR

### ISSUE THREAD

**Issue by megamoster** [BEEmod/BEE2.4#1565] opened 2021-04-22 15:24 UTC
**BEE2 version: BEE2_v4.39.2_win64**

**Description of the bug: the program does not start**

**Steps to reproduce: I downloaded Bee mod 2 (Includes all packages and patch), unzipped and ran "BEE2.exe". After that I saw it: 
![ErrorAnd  (1)](https://user-images.githubusercontent.com/52428534/115740220-481a3b80-a397-11eb-9b16-3bb1b307ea4d.png)
**

**Additional information: 

then decided to try to specify the file "Portal2.exe":

![Select (2)](https://user-images.githubusercontent.com/52428534/115740527-929bb800-a397-11eb-8fdf-1e7ba81aa755.png)

I pointed to the file and saw:

 
![And agarin Error (3)](https://user-images.githubusercontent.com/52428534/115740560-9c252000-a397-11eb-8f80-e377b2c6f1c0.png)

Tell me what the problem is?

PS here is the folder:
![Folder](https://user-images.githubusercontent.com/52428534/115740573-a0e9d400-a397-11eb-99e0-f19f9c72d66b.png)

**

**Comment by LautaroL20** [comment] 2021-04-22 15:54
This is a duplicate of: https://github.com/BEEmod/BEE2.4/issues/1521

**Closed by LautaroL20** 2021-04-22 15:54 UTC
Labels: App Crash, Duplicate
